### ISSUE TITLE
wrong estimation of coverage bamCoverage normalizeTo1x

### ISSUE THREAD

**Issue by fidelram** [fidelram/deepTools#100]
From deepTools mailing list:

I use commands like this:
 bamcoverage --normalizeTo1x 4641652 --fragmentLength 300  --outFileFormat bedgraph --binSize 50 -o XXX.bg -b XXX.bam

My data is pair-end, read length 150, fragment length ~300

When I use 50 as bin size, most bins have values around 1 and the median is about 1, which I think is as expected.
But, when I use 200 as bin size, the median goes up to 1.5
When I use 500 as bin size, the median is about 2.5.

**Comment by fidelram** [comment]
The problem could be produced by the estimation of coverage (num reads * fragment length) / effective genome size. For larger bins the coverage is higher as they will contain more reads. 

A solution that will also get rid of the effective genome size parameter is to first compute the coverage and then apply an appropriate scaling factor.

**Comment by dpryan79** [comment]
There's no reason to expect a median of 1, regardless of the bin size, even in input samples. That modifying the bin size results in different values is (A) not a suprise and (B) not a problem since everyone should always use the same bin size when doing comparisons.
