### ISSUE TITLE
Which normalization method is more suitable for normalization in bamCoverage for Chip-seq experiments

### ISSUE THREAD

**Issue by apastore** [fidelram/deepTools#103]
Hi,

I would like to know which parameter would you suggest for the normalization of multiple bigWig using bamCoverage.

Thanks!

**Comment by fidelram** [comment]
Hi,

I would recommend the option of: normalizeTo1x for several bam files if you
know the effective genome size.

Furthermore, I recommend you to use our mailing list for such questions:
https://groups.google.com/forum/#!forum/deeptools



On Sun, Sep 27, 2015 at 6:40 PM, apastore <notifications@github.com> wrote:

> Hi,
>
> I would like to know which parameter would you suggest for the
> normalization of multiple bigWig using bamCoverage.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/103>.
>



-- 

Fidel Ramirez

**Comment by apastore** [comment]
Thanks! I am normally using a bin of 1bp so I was doing RPKM but thanks!

I will use the mailing list!

Best,
Alessandro

**Comment by fidelram** [comment]
If you use RPKM or normalizeTo1x consistently to all your samples it is no problem. I just find the interpretation of the 1x values easier to understand.
