### ISSUE TITLE
bamCoverage crashes for deepTools v1.6

### ISSUE THREAD

**Issue by sukhdeepsingh** [fidelram/deepTools#105]
Hi, 
the bamCoverage crashes for the v1.6.
I can reproduce the error using several bam files though with v1.5.9, it works smoothly.

Cheers

Traceback (most recent call last):
  File "/share/apps/deeptools/1.6/bin/bamCoverage", line 248, in <module>
    main(args)
  File "/share/apps/deeptools/1.6/bin/bamCoverage", line 244, in main
    format=args.outFileFormat, smooth_length=args.smoothLength)
  File "/share/apps/deeptools/1.6/lib/python2.7/site-packages/deeptools/writeBedGraph.py", line 137, in run
    numberOfProcessors=self.numberOfProcessors)
  File "/share/apps/deeptools/1.6/lib/python2.7/site-packages/deeptools/mapReduce.py", line 123, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File "/share/apps/python/2.7.8/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AttributeError: 'pysam.csamtools.AlignedRead' object has no attribute 'reference_end'

**Comment by fidelram** [comment]
can you type `pip freeze` to check the version number of pysam? The version
that I have is 0.8.3 and  the `reference_end` is part of the new names in
the API (check http://pysam.readthedocs.org/en/latest/api.html)

On Tue, Oct 6, 2015 at 12:12 PM, Sukhdeep Singh <notifications@github.com>
wrote:

> Hi,
> the bamCoverage crashes for the v1.6.
> I can reproduce the error using several bam files though with v1.5.9, it
> works smoothly.
>
> Cheers
>
> Traceback (most recent call last):
> File "/share/apps/deeptools/1.6/bin/bamCoverage", line 248, in
> main(args)
> File "/share/apps/deeptools/1.6/bin/bamCoverage", line 244, in main
> format=args.outFileFormat, smooth_length=args.smoothLength)
> File
> "/share/apps/deeptools/1.6/lib/python2.7/site-packages/deeptools/writeBedGraph.py",
> line 137, in run
> numberOfProcessors=self.numberOfProcessors)
> File
> "/share/apps/deeptools/1.6/lib/python2.7/site-packages/deeptools/mapReduce.py",
> line 123, in mapReduce
> res = pool.map_async(func, TASKS).get(9999999)
> File "/share/apps/python/2.7.8/lib/python2.7/multiprocessing/pool.py",
> line 558, in get
> raise self._value
> AttributeError: 'pysam.csamtools.AlignedRead' object has no attribute
> 'reference_end'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/105>.
>



-- 

Fidel Ramirez

**Comment by sukhdeepsingh** [comment]
pysam==0.8.3
How should we solve this then?

**Comment by fidelram** [comment]
Let's confirm first that the pysam 0.8.3 version is the one used by
deepTools.

Do you have by chance pip at `/share/apps/deeptools/1.6/bin/` If yes, try: `
/share/apps/deeptools/1.6/bin/pip freeze | grep pysam`

Alternatively you can try to sent me the output of:

`head /share/apps/deeptools/1.6/bin/bamCoverage`

Since the release 1.6 code is working fine for us I suspect that the
problem has something to do with your installation. The pysam version that
you report could be the one installed globally but may not be the one
installed with deepTools in your /share/apps/deeptools/1.6/ folder


On Tue, Oct 6, 2015 at 12:29 PM, Sukhdeep Singh <notifications@github.com>
wrote:

> pysam==0.8.3
> How should we solve this then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/105#issuecomment-145816435>.
>



-- 

Fidel Ramirez

**Comment by sukhdeepsingh** [comment]
Hey, I dont have the pip there.

head -n 10 /share/apps/deeptools/1.6/bin/bamCoverage
#!/share/apps/python/2.7.8/bin/python
#-*- coding: utf-8 -*-

# own tools
import argparse
from deeptools import writeBedGraph
from deeptools import parserCommon
from deeptools import bamHandler

debug = 0

So, should we compile the deeptools again with system pysam.

**Comment by fidelram** [comment]
now try the following:

execute /share/apps/python/2.7.8/bin/python

then type in the python shell

>>> import pysam
>>> print pysam.__version__



On Tue, Oct 6, 2015 at 4:02 PM, Sukhdeep Singh <notifications@github.com>
wrote:

> Hey, I dont have the pip there.
>
> head -n 10 /share/apps/deeptools/1.6/bin/bamCoverage
> #!/share/apps/python/2.7.8/bin/python
> #-*- coding: utf-8 -*-
> own tools
>
> import argparse
> from deeptools import writeBedGraph
> from deeptools import parserCommon
> from deeptools import bamHandler
>
> debug = 0
>
> So, should we compile the deeptools again with system pysam.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/105#issuecomment-145865189>.
>



-- 

Fidel Ramirez

**Comment by sukhdeepsingh** [comment]
You are right, its an old version

/share/apps/python/2.7.8/bin/python
Python 2.7.8 (default, Oct  9 2014, 15:55:07) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> print pysam.__version__
0.7.5

**Comment by sukhdeepsingh** [comment]
Thanks, I will ask the admin to fix it.
