### ISSUE TITLE
computeMatrix on scale-regions could be unscaled nearby start/end

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#108]
Hi,

some paper show metagene profile with scaled region and unscalled region in the body of region like this figures from this paper (Kruesi, et al. “Condensin Controls Recruitment of RNA Polymerase II to Achieve Nematode X-Chromosome Dosage Compensation.” eLife 2 (January 18, 2013): e00808. doi:10.7554/eLife.00808.): 
![metagene_partially_scaled_body](https://cloud.githubusercontent.com/assets/10290456/10661839/ec857c80-789f-11e5-93f7-a15d15146e9d.png)

I think it should be a good approach to see some effect because you can see "true" signal around TSS and TES and a scaled vision of the center of body all in one figure. In this review (Ferrari, et al. “Transcriptional Control of a Whole Chromosome: Emerging Models for Dosage Compensation.” Nature Structural & Molecular Biology 21, no. 2 (February 1, 2014): 118–25. doi:10.1038/nsmb.2763.) autors explain (in box3) why this kind of visualisation is better than a "simple"  scaled version.

I think if you can implement this and the "rna-seq mode" (which join all exon) then deeptools will be an essential and powerfull tool.

Many thanks to your work.

**Comment by friedue** [comment]
Hi,
I don't completely understand the issue - isn't `computeMatrix scale-regions` already doing what you're asking if you use the `-b` and `-a` options?

**Comment by lelouar** [comment]
Hi,

sorry, I don't explain well the issue. Indeed, the option -a and -b is used for flanking region (outside body) and all te body is scalled. The proposal is to add unscalled region **in the body** (downstream of TSS and upstream of TES, like figure in my previous post).

Now, the way to do so is to process 3 computeMatrix step - 2 reference-point (TSS, TES) and 1 scale-regions (body) - with at least two different bedfiles. A "normal" bed file like protein_coding_genes and a cutted version of this bed file with all the region cutted at 3' downstream and 5' upstream (500 bp if we want to make the same figure like in previous post). The result is: unscalled flanking regions (outside body), unscalled end (3'/5') inside the body and scaled region in the "center of body".

For the joining of all exons it is not possible yet even with 1.6 release. Because information of splicing regions is contained in bed12 format not in bed6/bed3 format. I just check if the result of the two kind of bed format is the same and unfortunately it is. We can do this with ngs.plot in rna-seq mode but it is not as modular as deeptools.

I hope I explain better than before.

**Comment by dpryan79** [comment]
I've started adding the code needed for this in this PR #294

At the moment things seem to mostly work, but this could use some testing. I've not yet tested writing text output from plotProfile/plotHeatmap with this, though presumably that works. I've also not ensured that the values are actually correct yet (i.e., we need an automated test for this). Having said that, have a look and feel free to play around with this while I get it finished.

**Comment by dpryan79** [comment]
That PR now works properly, both with computeMatrix and plotProfile/plotHeatmap. The only thing left to do is add this to the Galaxy wrapper.

**Comment by lelouar** [comment]
wow it's a very good news. thx a lot

**Comment by dpryan79** [comment]
This is now merged. I wouldn't be surprised if the next version is out within a week.
