### ISSUE TITLE
add region labels to the heatmap

### ISSUE THREAD

**Issue by friedue** [fidelram/deepTools#110]
Currently, the information about which region is plotted is only shown in the profiler plots. I.e., if one chooses to only show the heatmap plus colorbar, this information is lost/not visible. 
Perhaps adding an extra bar/line on top of the heatmap (not making it part of the heatmap itself) might help solve this issue?

**Comment by dpryan79** [comment]
I think this is fixed in the `devon_changes` branch, which will hopefully get merged today.

**Comment by fidelram** [comment]
It is now merged. Friederike, do you still have the problem?

On Tue, Dec 8, 2015 at 11:49 AM, Devon Ryan <notifications@github.com>
wrote:

> I think this is fixed in the devon_changes branch, which will hopefully
> get merged today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/110#issuecomment-162846920>.
>



-- 

Fidel Ramirez
