### ISSUE TITLE
-ignore not working for bamCoverage (branch 1.6)

### ISSUE THREAD

**Issue by vivekbhr** [fidelram/deepTools#111]
Hi
In the **Multiheatmapper branch** the --ignoreForNormalization (aka -ignore) option is not working. I compared results from different versions and found this issue in the branch 1.6 only. Moreover, you can also see it in the output log.

```bash
deeptools-multiheatmapper/bin/bamCoverage -b mySortedBam.bam --normalizeTo1x 2150570000 -o dt-multi.bw -bs 10 -p 20 -ignore "chrM, chrX, chrY"
```
```r
ignoreDuplicates: False
numberOfProcessors: 20
samFlag_exclude: None
verbose: False
samFlag_include: None
extendPairedEnds: False
region: None
maxPairedFragmentLength: 1000
binLength: 10
numberOfSamples: None
stepSize: 10
defaultFragmentLength: 1
bedFile: None
center_read: False
chrsToSkip: []
bamFilesList: ['mySortedBam.bam']
smoothLength: 0
minMappingQuality: None
zerosToNans: False
```

**Comment by fidelram** [comment]
I introduced some changes in the latest commits to address this issue. However, in the output that you added, there is nothing related to the option ignoreForNormalization. What you see is chrToSkip which just removes any output from the given chromosomes.

**Comment by fidelram** [comment]
The latest commit fddcf4a56811b4e972a2f3c175294cc98cfc4838 addresses the problem. It was caused not but --ignoreForNormalization but because of commit 7e8975e5d1f0d77bdf1b0a9794db95841afca6cd in which the --fragmentLength as not longer required.
