### ISSUE TITLE
1-99% transparency on heatmapper

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#112]
Dears,

Is it possible to use a transparency flag on heatmapper so that the png produced has a transparency range from 0 to 99%? Thx.

**Comment by fidelram** [comment]
the heatmap is plotted using the imshow() method from matplotlib. Maybe is possible to pass a colormap with transparency.

**Comment by dpryan79** [comment]
FYI, imshow() takes a Colormap, which is an RGB(A). So, this should be doable.

**Comment by dpryan79** [comment]
The code for this is essentially done, I'm just testing it now. Currently, the heatmap and colorbar can be affected with the `--alpha` parameter but the profile isn't touched. I suppose that that could be modified as well if really needed.

**Comment by dpryan79** [comment]
This has been tested and merged in and will appear in the 2.3 release.
