### ISSUE TITLE
overlay two or more bw in heatmaper plot profile

### ISSUE THREAD

**Issue by apastore** [fidelram/deepTools#116]
Hi I am wondering if it is possible to plot more than one bw in the same plot. 

e.g I have two chip-seq for the same PTM maker and I want to plot the sign on all TSS for the two Chip-seq in the same plot (profile) and in two heatmap.

Thanks for you suggestion

**Comment by fidelram** [comment]
Please use release-1.6 branch. That branch allows plotting more than one bigWig.
