### ISSUE TITLE
error computeMatrix with bw file from hs38DH

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#120]
I get the following error when running computeMatrix below with a `.bw` file of reads aligned to the hs38DH reference. Any ideas?

```
 
 computeMatrix scale-regions --regionsFileName /data/group/test/TESTP/TESTWGBS0001.chr.cpgs.250.bed --scoreFileName /data/group/test/TEST_Run001/TEST_Run001-12345678/TST36_89_10-12345678/Data/Intensities/BaseCalls/TST36-89-10_S1_L001_R1_001.cutB.sorted.mrgd.standard.bam.bw --beforeRegionStartLength 50 --afterRegionStartLength 50 --regionBodyLength 250 --binSize 10 --outFileName /data/group/test/TEST_Run001/TEST_Run001-12345678/TST36_89_10-12345678/Data/Intensities/BaseCalls/TST36-89-10_S1_L001_R1_001.cutB.sorted.mrgd.standard.bam.dtmat.tab.gz --missingDataAsZero --sortRegions no
 Exception found. Message: 'BinaryFileReader' object has no attribute 'read_bits64'
 Exception found. Message: 'BinaryFileReader' object has no attribute 'read_bits64'
 Traceback (most recent call last):
   File "/data/apps/python/2.7.3/bin/computeMatrix", line 157, in <module>
       main(args)
         File "/data/apps/python/2.7.3/bin/computeMatrix", line 139, in main
             Exception found. Message: 'BinaryFileReader' object has no attribute 'read_bits64'
             parameters, verbose=args.verbose)
               File "/data/apps/python/2.7.3/lib/python2.7/site-packages/deeptools/heatmapper.py", line 97, in computeMatrix
                   mp_args).get(9999999)
                     File "/data/apps/python/2.7.3/lib/python2.7/multiprocessing/pool.py", line 528, in get
                         Exception found. Message: 'BinaryFileReader' object has no attribute 'read_bits64'
                         Exception found. Message: 'BinaryFileReader' object has no attribute 'read_bits64'
                         raise self._value
                         UnboundLocalError: local variable 'bw_array' referenced before assignment
                         Exception found. Message: 'BinaryFileReader' object has no attribute 'read_bits64'
```

**Comment by dpryan79** [comment]
Is this in version 1.5.11?

**Comment by dpryan79** [comment]
For what it's worth, this is likely an error arising in bx-python where it's reading the bigWig file. It's impossible to tell if this is a bx-python error or a problem with the bigWig file itself. You might try the release-1.6 branch, which no longer uses bx-python. If you get an error with that too (N.B., the error would be completely different) then the problem is the file itself.

**Comment by avilella** [comment]
Indeed it's computeMatrix 1.5.11, I will try to install 1.6.

**Comment by dpryan79** [comment]
@avilella: Have you had a chance to try 1.6?

**Comment by avilella** [comment]
I did, and it still crashes. I sanitized the ref names, and it still
crashes, presumably due to a limit in the number of contigs in a reference
file. I resorted to turn the hs38DH bam into a filtered out karyotype bam,
and then it works as it used to be.

Sadly no straight solution...

**Comment by dpryan79** [comment]
I assume the error message is different at least (it'd have to be). Could you provide us with the BED and bigWig files so we can fix this?

**Comment by avilella** [comment]
Here is a small example:

If I run the commands in the deeptools_heatmap.sh command with the
*.mrgd.bam file, it fails.

If I run the same commands with the *.mrgd.karyotype.bam file, it works.

https://cloud.curoverse.com/collections/download/qr1hi-4zz18-4vctm1bt5f76dan/48dhtbven3q7wxj1newlzrnzujuc0hy5ynm1iyqbvujv0ghw6m/

**Comment by dpryan79** [comment]
Great, thanks, I'll have a look and get this fixed!

**Comment by dpryan79** [comment]
Did you include the wrong BED file or is the shell script just incorrect there?

**Comment by avilella** [comment]
One is just a 'head -n 1000' of the other...

**Comment by dpryan79** [comment]
Ah, OK :)

**Comment by avilella** [comment]
For the karyotype.bam file, when it works, the three commands are the ones
below:

# /bi/home/rocks-av/.local/bin//computeMatrix scale-regions
--regionsFileName /bi/group/cegx/CEGXP/NIMBP001B000.nnn.targ.250.bed
--scoreFileName
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.bw
--beforeRegionStartLength 50 --afterRegionStartLength 50 --regionBodyLength
250 --binSize 10 --outFileName
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.tab.gz
--missingDataAsZero --sortRegions no
 1>WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.computematrix.log
2>/dev/null
# /bi/home/rocks-av/.local/bin//heatmapper --heatmapWidth 7.5 --matrixFile
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.tab.gz
--sortUsing mean --outFileName
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.heatmap.alignment_overview.pdf
--plotTitle "WBGS-oxBS-vB-1000ng-PCR06-R02 -- NIMBP001B000 -- t250 p50"
--whatToShow "plot, heatmap and colorbar" --regionsLabel targets
--missingDataColor "#FFFFFF" --zMin 0 --zMax 30
1>WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.heatmapper.log
2>WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.heatmapper.err
# Output file (size: [33006]):
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.heatmap.alignment_overview.pdf
# /bi/home/rocks-av/.local/bin//heatmapper --heatmapWidth 7.5 --matrixFile
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.tab.gz
--sortUsing mean --outFileName
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.heatmap.alignment_overview.png
--plotTitle "WBGS-oxBS-vB-1000ng-PCR06-R02 -- NIMBP001B000 -- t250 p50"
--whatToShow "plot, heatmap and colorbar" --regionsLabel targets
--missingDataColor "#FFFFFF" --zMin 0 --zMax 30
1>WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.heatmapper.log
2>WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.heatmapper.err
# Output file (size: [72812]):
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam.dtmat.heatmap.alignment_overview.png

**Comment by dpryan79** [comment]
Could you post the updated error message that you get?

**Comment by dpryan79** [comment]
This seems to work now in the current release-1.6 branch. The original error was from bx-python, which has been replaced in the interim.
