### ISSUE TITLE
Add better explaination of behaviour of bamPEFragmentSize

### ISSUE THREAD

**Issue by asrichter** [fidelram/deepTools#139]
The output mean, std, min and max deviate from the results of Picard CollectInsertSizeMetrics. It seems that only properly paired reads considered (max. length of 1000 suggests this). Correct? If yes, this should be specified on the help page.

Furthermore, the `--verbose` option seems to be without function.

**Comment by vivekbhr** [comment]
@asrichter I fixed it in my PR #196
