### ISSUE TITLE
--missingDataAsZero is not a boolean

### ISSUE THREAD

**Issue by bgruening** [fidelram/deepTools#144]
@fidelram @dpryan79 do we want to take the opportunity and make a boolean out of it? Maybe `--disableMissingDataAsZero`? It's long and ugly, but the `yes`/`no` is not intuitive either.

```
    optional.add_argument('--missingDataAsZero',
                          default="yes",
                          choices=["yes", "no"],
                          help='Default is "yes". This parameter determines '
                          'if missing data should be treated as zeros. '
                          'If set to "no", missing data will be ignored '
                          'and not included in the output file. Missing '
                          'data is defined as those regions for which '
                          'both BAM files have 0 reads.')
```

**Comment by bgruening** [comment]
Especially because in computeMatrix we have this: https://github.com/fidelram/deepTools/blob/release-1.6/deeptools/computeMatrix.py#L248

**Comment by vivekbhr** [comment]
That's right I would vote for the boolean option..

**Comment by vivekbhr** [comment]
@bgruening @fidelram @dpryan79 the option can be named : --keepMissingData , and we can edit the help to say what it means

**Comment by bgruening** [comment]
@vivekbhr I like `--keepNAs`.
This option is in many places, even referenced in other parameters so we need to grep through the code once we agreed on a way forward.

**Comment by fidelram** [comment]
we should make this boolean!
