### ISSUE TITLE
Setting pdf/eps/svg as output type results in wrong data type

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#170]
It turns out that at least for `plotCorrelation`, you can have the tool output a PDF or SVG file, but Galaxy will still set the datatype to PNG.

**Comment by thomasmanke** [comment]
actually the tool can also do EPS

**Comment by bgruening** [comment]
@dpryan79 should I add again EPS I removed it a few days ago?
Will tackle this one.

**Comment by dpryan79** [comment]
I honestly wouldn't worry about EPS, though since it works we might as well leave it in. It was EMF or whatever that windows format is called that doesn't work.

**Comment by bgruening** [comment]
Should be fixed here: https://github.com/fidelram/deepTools/commit/9850f3e091ef48021fb1b501f270ea6c88a9c2c0
