### ISSUE TITLE
bamCorrelate: extension length

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#176]
--extendReads is buried under advanced options, but it is a _requirement_ for single-end reads.
Can we set a meaningful default, i.e 0 ?

**Comment by bgruening** [comment]
What should happen in case of single-end reads and no --extendReads is set?
ping @fidelram

**Comment by thomasmanke** [comment]
Then only the mapped length should be considered, in a splice-aware manner. I though deepTools is splice-aware

**Comment by bgruening** [comment]
I don't find were extendReads is a requirement: https://github.com/fidelram/deepTools/blob/release-1.6/deeptools/parserCommon.py#L32

**Comment by dpryan79** [comment]
This is fixed in the most recent push.
