### ISSUE TITLE
bamCorrelate: wrapper

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#177]
The wrapper is still outdated. There should be a new version from branch thomas_docu_changes

**Comment by vivekbhr** [comment]
@thomasmanke is this from your PR that was merged already?

**Comment by bgruening** [comment]
There is still an unmerged branch from @thomasmanke here: https://github.com/fidelram/deepTools/compare/thomas_docu_changes?expand=1

No PR was created until now.

**Comment by dpryan79** [comment]
I'll ask him

**Comment by dpryan79** [comment]
They're not completed yet

**Comment by dpryan79** [comment]
This was merged in, closing.
