### ISSUE TITLE
plotCoverage - no Galaxy wrapper yet

### ISSUE THREAD

**Issue by steffenheyne** [fidelram/deepTools#180]
plotCoverage is a new tool in deeptools2 and we should get a wrapper for it, or? @bgruening is this possible? What do you think?

**Comment by bgruening** [comment]
@steffenheyne is this ready for prime time? E.g --plotFileFormat is missing ...

**Comment by steffenheyne** [comment]
Is this a "requirement"? But yes, this option is missing...I will check how to add this...
Anything else needed/required?

**Comment by dpryan79** [comment]
I don't recall what the conclusion was of the last meeting. Realistically this will probably not be available before we have to submit, so no, it's not a requirement for that :=)

**Comment by bgruening** [comment]
It's not, I will include it. I somehow missed ... everything else from the image preferences that makes sense from the other tools ... zmin, zmax, xmin, xmax?
For my feeling the interface should match as much as possible between all tools.

**Comment by vivekbhr** [comment]
the wrapper is working in galaxy now..
[plotCoverage.pdf](https://github.com/fidelram/deepTools/files/69845/plotCoverage.pdf)
