### ISSUE TITLE
plotCoverage - cmdl interface needs to be adapted

### ISSUE THREAD

**Issue by steffenheyne** [fidelram/deepTools#185]
With all the latest changes on parameters like --extendReads the interface plotCoverage needs to updated. For the Galaxy wrapper an option "--plotFileFormat" would be nice.

also: is --skipZeros here a bit different than --skipNonCoveredRegions ?

This issue is just to not forget about this...

**Comment by vivekbhr** [comment]
--extendReads and other params are working now
--plotFileFormat is in galaxy..

**--skipZeros** is still there in plotCoverage, computeMatrix, plotCorrelation and bamFP.. It looks like it's a simple conversion from NaN to zero but don't know how different from --skipNonCoveredRegions. @fidelram

**Comment by fidelram** [comment]
--skipZeros is different than --skipNonCoveredRegions. skipZeros simply ignores rows or zeros in a matrix. --skipNonCoveredRegions acts on each sample either adding or treating as zero regions without reads or without any bigwig score.

**Comment by vivekbhr** [comment]
so they have different behavior..
