### ISSUE TITLE
plotHeatmap issues

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#187]
- default label ("genes") for profile y-axis is meaningless ==> my suggestion "coverage"
- what to show: the last three options  "heatmap only, heatmap and colorbar, colorbar only" do not work as selected and they will revert to "summary plot, heatmap and colorbar" instead. A sensible default, but the options are also useless. Perhaps it's worth having the heatmap without the summary.
- --onePlotPerGroup is unreckognized; it is called "--perGroup" now, but what does it do?
- --outFileNameData unreckognized (yields error if advanced output options are selected)
- number of kmeans clusters: default is 0, more sensible default would be 1

**Comment by vivekbhr** [comment]
Most of the issues are fixed in #188 now..
