### ISSUE TITLE
plotCoverage on galaxy

### ISSUE THREAD

**Issue by vivekbhr** [fidelram/deepTools#193]
plotCoverage is currently not working on galaxy.

```
plotCoverage: error: unrecognized arguments: --plotFileFormat png
```

This is related to the macro : `input_image_file_format` which can't pass the value to `--outFileFormat` (line 25).. but it's better if @bgruening or @dpryan79 fix it..

**Comment by bgruening** [comment]
Mh strange test are passing for me. I will look into this one.

**Comment by steffenheyne** [comment]
I think it is the --scaleFactor option that cause problems, it is now calles "--scaleFactors" and teh paramters format looks like "1:2", ie.  "--scaleFactors 1:2"

**Comment by bgruening** [comment]
@steffenheyne I don't see a scaleFactors option in plotCoverage. But I see a `  --plotFileFormat FILETYPE
                        Image format type. If given, this option overrides the
                        image format based on the plotFile ending. The
                        available options are: png, emf, eps, pdf and svg.
`
I don't understand this error.
@vivekbhr this is happening in Galaxy on your server?

**Comment by steffenheyne** [comment]
sorry the scaleFactor problem is for bigwigCompare!!!

**Comment by bgruening** [comment]
In the most recent wrappers we have `--scaleFactors number:numer`.

**Comment by dpryan79** [comment]
The actual plot coverage error is now resolved. The bigwigCompare thing is hopefully being followed in its own issue report :)
