### ISSUE TITLE
plotCorrelation: svg does not display

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#197]
Is SVG supposed to show in galaxy? PDF does, but SVG is shown as ascii (XML).

**Comment by bgruening** [comment]
This is a feature ;)
https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L627

We need to deactivate this feature to activate SVG rendering. I will include this in the Docker Image.

**Comment by bgruening** [comment]
fyi: https://github.com/bgruening/docker-recipes/commit/fd3dc4b106ee9be31c52587d296df282dc6184c0

**Comment by dpryan79** [comment]
This is now fixed, closing.
