### ISSUE TITLE
Remove dependency on UCSCtools/samtools

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#199]
Now that deepTools uses pyBigWig, there's no need for UCSCtools. While not yet completely documented, pyBigWig now supports bigWig file creation without intermediate files. Also, there's nothing that samtools does that we can't just do with pysam.

These two changes would considerably simplify the installation as well.

**Comment by vivekbhr** [comment]
Just adding here that some of the tools (eg. correctGCbias) also have checks for ucsctools and samtools, which can be removed after these dependencies are removed..
