### ISSUE TITLE
bigwigCompare on galaxy fails

### ISSUE THREAD

**Issue by steffenheyne** [fidelram/deepTools#200]
galaxy produces the following error while running bigwigCompare with 2 bigwig files:

Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 165, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 862, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "lib/galaxy/tools/evaluation.py", line 427, in build
    raise e
NotFound: cannot find 'scaleFactor1' while searching for 'advancedOpt.scaleFactor1'

Maybe related to the slightly changed parameter --scaleFactors 1:1

**Comment by bgruening** [comment]
And fixed! Thanks a lot Steffen!

**Comment by dpryan79** [comment]
@steffenheyne: I'll update the server tomorrow and this fix will then be live.
