### ISSUE TITLE
Reduce memory requirements in computeMatrix

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#202]
computeMatrix uses an absolutely absurd amount of memory for what it's actually doing. It doesn't help that it's getting values rather than intervals, which would be vastly faster and more memory efficient.

**Comment by bgruening** [comment]
You already tried the value approach and it doesn't work?

**Comment by dpryan79** [comment]
The value approach is what's currently implemented. It'd need to be redone a bit to take intervals and the results compared to ensure that things are being done correctly. This would, however, be preferable.

**Comment by dpryan79** [comment]
This was largely due to me using too many `Py_INCREF()`s in pyBigWig. That's fixed in version 0.1.10.
