### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by cjt5** [fidelram/deepTools#210]
I am currently attempting to install deeptools on a MAC OS X Yosemite (Version 10.10.15) and am getting the following error. 

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9l/k9fq7hc90vzchb0qjf6cxl5j6f95tw/T/pip-build-_mz9jhov/deeptools

I used both pip install (after anaconda installation) as well as python setup.py install...not sure what I am doing wrong.

Thanks for the help!

**Comment by dpryan79** [comment]
Can you post the exact command you used and the entire output before the error is encountered?

**Comment by cjt5** [comment]
terranova$ pip install deeptools
Collecting deeptools
  Using cached deepTools-1.5.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/9l/k9fq7hc90vzchb0qjf6cxl5j6f95tw/T/pip-build-_mz9jhov/deeptools/setup.py", line 22
        print "This does not appear to be a Git repository."
                                                           ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9l/k9fq7hc90vzchb0qjf6cxl5j6f95tw/T/pip-build-_mz9jhov/deeptools

Thanks very much for such a fast response! Really great!!

**Comment by bgruening** [comment]
@cjt5 this seems to be a Python3 issue. Can you run it please under python2?

**Comment by dpryan79** [comment]
One of these days we'll support python3 as well...

**Comment by bgruening** [comment]
Sure, we take sponsoring of :beers: and hack this out in a week :)

**Comment by cjt5** [comment]
Thanks a lot! Will try it out and let you know what happens.

**Comment by cjt5** [comment]
Everything worked fine using Python2...

Thanks again!

**Comment by bgruening** [comment]
Awesome!
