### ISSUE TITLE
binSize problem with bamCoverage

### ISSUE THREAD

**Issue by AlicePsyche** [fidelram/deepTools#211]
Hi, all

When I use bamCoverage, the bin size of generated bw file is not the same length, like following:

```bash
chr1    3000700 3000800 0.45
chr1    3000900 3001000 0.45
chr1    3001000 3001200 1.36
chr1    3001600 3001700 0.91
chr1    3001700 3001900 2.27
chr1    3001900 3002000 0.91
chr1    3002200 3002400 0.91
```

The command I run:

```bash
bamCoverage --bam name.bam \
--outFileName name.bw \
--outFileFormat bigwig \
--normalizeUsingRPKM \
--ignoreForNormalization "chrM" \
--missingDataAsZero no \
--binSize 100 \
--numberOfProcessors 2 \
--ignoreDuplicates
```

I am a newbie to bioinformatics, did I miss anything? I have read your 'all command line options' wiki page but found nothing. It would be grateful if you can help me.  Thanks for your valuable time :)

**Comment by dpryan79** [comment]
Can you write a bedGraph file and see if the same happens there. It might be that the conversion tool merges neighbouring entries with the same values.

**Comment by AlicePsyche** [comment]
Thanks for your quick reply ! But the problem still there 
```bash
chr1    3000100 3000200 0.45
chr1    3000200 3000600 0.91
chr1    3000600 3000700 1.36
chr1    3000700 3000800 0.45
chr1    3000900 3001000 0.45
chr1    3001000 3001200 1.36
chr1    3001600 3001700 0.91
chr1    3001700 3001900 2.27
```

command: 
```
--outFileName name.bedgraph \
--outFileFormat bedgraph \
--normalizeUsingRPKM \
--ignoreForNormalization "chrM" \
--missingDataAsZero no \
--region chr1 \
--binSize 100 \
--numberOfProcessors 2 \
--ignoreDuplicates
```

**Comment by dpryan79** [comment]
I tracked this down and it's due to this: https://github.com/fidelram/deepTools/blob/release-1.6/deeptools/writeBedGraph.py#L255-L256

That's not really a bug, it's a feature. This just saves space in the output files since there's no point in producing the extra lines.

**Comment by dpryan79** [comment]
If you really need this, then you can uncomment the stuff a few lines up (https://github.com/fidelram/deepTools/blob/release-1.6/deeptools/writeBedGraph.py#L241-L248).

**Comment by AlicePsyche** [comment]
Oh, I see ! Thanks very much ;)

**Comment by BigGiAnts** [comment]
i encountered the same problem as @AlicePsyche，and the above links are dead. 
can you tell me again how to fix the problem?
thanks a lot

**Comment by BigGiAnts** [comment]
i fix the problem:
find the file : writeBedGraph.py
uncomment line:  L250-L258  ## varies according to version of deeptools
save changes.
done
