### ISSUE TITLE
Potential for out of order entry addition when writing bigWig files

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#213]
In the bigWig creation stuff, I've assumed that the bedGraph would be in the same sort order as the BAM file header. This isn't actually the case and can cause issues. The solutions are (1) write a different sort utility or (2) sort the chromosome list that goes into pyBigWig to match the file. Option 2 is certainly simpler.

**Comment by steffenheyne** [comment]
I just want to stress that the sort order (of bedgraph/bigwig) is *important*. I had once a lot of trouble to sync outputs of different tools (deeptools and others) because the didn't care about the chr order. The additional difficulty was that I coudn't simply use linux sort as some other sort magic happend internally. So it would be nice to have either the sort order of the bam index or a sort-reproducible sort order of the bedgraph/bigwig.

**Comment by dpryan79** [comment]
At the moment the sort is reproducible with `LC_ALL=C sort -k1,1 -k2n,2 some_file`. I would generally prefer to keep the sort order of the BAM file, but that's rather more difficult to do (we'd need to write a file merger, though that wouldn't be too terrible to do).

**Comment by steffenheyne** [comment]
ah and what happens actually in the bigwig with chromosomes appearing in the bam index but they have no values at all in the bedgraph!? It would be nice if at least these chr (with the right size) appear in the bigwig index (does something like this exists?). I think I also had once problems with another tool that striped down these chr....

All this was important for me to get a proper (ie. have always the same number of chr in the same sort order) genome wide binning from bigwig files...

**Comment by dpryan79** [comment]
All chromosomes are in the index, regardless of whether they have an entry (the size is provided by the BAM file). Anything that produces lines with 0 in a bedGraph file will do so in a bigWig file as well.

**Comment by fidelram** [comment]
The sort order for bigwigFiles was imposed by the USCS `bedgraphToBigWig`. It has to be `LC_ALL=C sort -k1,1 -k2,2n `. Since now we are not using `bedgraphToBigWig` anymore we can probably use the same sort order as bam.
