### ISSUE TITLE
Read the docs updates

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#217]
The following pages still reference the wiki:

 * [x] example_usage
 * [x] help_faq
 * [x] help_galaxy_intro
 * [x] example_gallery
 * [x] example_step_by_step
 * [x] help_faq_galaxy

In addition, there are pages that have no links:
 * [x] help
 * [x] help_faq_galaxy
 * [x] example_gallery
 * [x] example_step_by_step

The following pages don't currently render properly:
 * [x] example_gallery
 * [x] example_step_by_step
 * [x] help_faq_galaxy

Page that needs an update with images:

* [x]  example_how_we_use

The following pages need to be updated, but can't be until the new galaxy wrappers are in the toolshed:
 * [x] example_step_by_step

**Comment by dpryan79** [comment]
See the `doc_fixes` branch for the updates.

**Comment by friedue** [comment]
I will dedicate most of tomorrow for working on this

**Comment by dpryan79** [comment]
Cool, feel encouraged to use the `doc_fixes` branch. Then we can get everything updated in a single merge and not duplicate efforts.

**Comment by friedue** [comment]
absolutely

**Comment by thomasmanke** [comment]
I must have broken list_of_tools.rst when I tried to remove a row from the table. Sorry. The simple goal was to introduce "data integration" as an analysis type for (multiBigwigSummary, multiBamCoverage and computeMatrix). multiBigwigSummary should only appear once in the table.

**Comment by dpryan79** [comment]
@thomasmanke: I fixed the table in the master branch.

**Comment by dpryan79** [comment]
The biggest thing that needs to be done with this now is to update the `example_step_by_step`, which will require the updated Galaxy wrappers being in the toolshed. I propose merging the current `doc_fixes` branch back into master and starting a new branch.

@friedue: Thoughts? BTW, we're down to 23 warnings with `make html`. 16 of those are due to tools not being in the TOC (not an issue) and 3 are due to images that don't exist yet. I'm still seeing if I can get rid of the last 3 doctest warning without breaking nosetests.

**Comment by friedue** [comment]
I agree on both, merging and starting a new branch.

Currently, I do not see any deepTools in deeptools2.ie-freiburg.mpg.de, so I guess their names will be updated soon?

**Comment by dpryan79** [comment]
@friedue: Sorry about the tools not currently appearing on deeptools2. I started updating them but hit an error with the installation of the actual deeptools package (as opposed to the wrappers). This isn't really an error in deepTools, it's just Galaxy being silly. They should appear and be functional by the morning your time.

**Comment by dpryan79** [comment]
I merged in and deleted doc_fixes. Feel free to make a new branch for additional changes, since I'm rather busy at the moment trying to determine WTF is up with the wrappers.

**Comment by dpryan79** [comment]
N.B., there's a new `doc_fixes` branch.
