### ISSUE TITLE
Recent reversions

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#219]
plotHeatmap/plotProfile have undergone the following reversions recently:

plotProfile:
 * [x] Relatedly, `--colors` no longer has any effect with `overlapped_lines`

plotHeatmap:
 * [x] `--colorNumber` has no effect
 * [x] `--yMax` somehow the profiler axis is then lost
 * [x] `--whatToShow` seems to be ignored

plotProfile and plotHeatmap:
 * [ ] `--yMin`/`--yMax` seem to zoom and shift the window, so things below the min are shown by the x-axis label and those above the max are near the title.

**Comment by dpryan79** [comment]
The `computeMatrix` thing was a bug in my script.

**Comment by dpryan79** [comment]
The overlapped_lines issue was due to switching to hexbin, which I'm not sure supports this.

**Comment by dpryan79** [comment]
Indeed, this is no longer possible for hexbin. I suppose this is how #124 got closed...

**Comment by fidelram** [comment]
Instead of adding a color per line, the new `plotProfile` version adds a block which gets properly labelled.

**Comment by dpryan79** [comment]
Indeed

**Comment by fidelram** [comment]
The `--colors` could be used for that. However, for the hexbin function colormaps are required (e.g. RdBuGr, or reds). But, I don't think those blocks should be colored differently by default. See:

![profile_hexbin](https://cloud.githubusercontent.com/assets/4964309/12329583/43be6d9e-bae1-11e5-893c-4cf6b72ec50b.png)

**Comment by dpryan79** [comment]
After playing around with things I'm just updating the documentation. I can make individual colormaps, but then individual colorbars are needed and that is incredibly cluttered. In the process, I also halved the size (in bytes) of produced svg and pdfs. These modifications are in the `fix219` branch.

**Comment by dpryan79** [comment]
That also removed a bug where the top image included all of the images superimposed

**Comment by dpryan79** [comment]
`--colorMap` doesn't seem to have any visible effect due to the range of values. That's no longer an issue.

**Comment by fidelram** [comment]
Can you paste a plot of the problem with --yMIn/--yMax to get an idea?

**Comment by dpryan79** [comment]
It seems that it only happens in SVGs, which can't be pasted into github. That means that this is a matplotlib bug and we can't do anything about it. I'll go ahead and close this.
