### ISSUE TITLE
Offer the option to export the data used to generate plots

### ISSUE THREAD

**Issue by friedue** [fidelram/deepTools#231]
Most tools have the option already, but the ones currently missing it are:

* [ ] plotPCA
* [x] plotProfiles

**Comment by fidelram** [comment]
plotProfiles can now save the data.

**Comment by dpryan79** [comment]
Have a look at PR #289 and let me know if the text output suffices (it's easiest to just look at the changed file, since I have an example output in a Galaxy wrapper test).

**Comment by dpryan79** [comment]
This is now fixed for the next release. Closing.
