### ISSUE TITLE
facelifts for readthedocs

### ISSUE THREAD

**Issue by friedue** [fidelram/deepTools#233]
Feel free to contribute ideas, code, images...! @fidelram @dpryan79 @vivekbhr @kilpert @thomasmanke @asrichter @steffenheyne @bgruening 

I am still a novice to reStructuredText, so any concrete input on how to make things actually look nice are much appreciated!

* [ ] the start site at readthedocs should also have a **slide gallery of images** instead of the current [static one](https://github.com/fidelram/deepTools/blob/master/docs/images/start_collage.png) --> according to Fidel, this will most likely have to be resolved using a GIF -- any other ideas? or anyone volunteering to make the GIF?
* [ ] I would also like to **feature the highlights of deepTools** (efficient BAM and bigWig handling, modularity, customizable publication-ready images) in a visually more stunning way than the current list at the bottom of [this page](http://deeptools.readthedocs.org/en/latest/) --> also as a GIF?
* [ ] the [workflow image](https://github.com/fidelram/deepTools/blob/master/docs/images/start_workflow.png) could also use a serious make-over (yes, in addition to renaming the tools) -- any volunteers? ideas?
* [ ] the gallery should have a grid-like structure of thumbnails similar to the [old gallery](https://github.com/fidelram/deepTools/wiki/Gallery) --> I will see if I can use [this advice](http://stackoverflow.com/questions/10219634/image-grid-in-restructuredtext-sphinx)

All of this should preferably be done in the ``doc_fixes`` branch.

**Comment by friedue** [comment]
to have links for bigger image versions, I will use this syntax:

```
.. raw:: html

    <a href=....><img src=....
```

**Comment by dpryan79** [comment]
We should be able to use the same javascript image gallery. The javascript and such can go in `_static/`and add them to `script_files` in the configuration. There's an equivalent css config line, if that's needed.

**Comment by fidelram** [comment]
Currently we have several entry points to deeptools and I don't think this does us any favor.
 * github.org
 * http://deeptools.github.io/
 * deeptools2.ie-freiburg.mpg.de
 * deeptools.readthedocs.org 

I would favor to keep the RTDs documentation as simple as possible as CSS and JS can not be ported in pdf or epub format. But, also seems advantageous to try to replace github.io by readthedocs. Any thoughts?

**Comment by friedue** [comment]
* I would scrape github.io
* We should delete most of the stuff in the README file here on github and simply point to RTDs
* I'd keep the wiki for now, but don't link it anywhere, this way, users that may have bookmarked it can still access the old pages and will hopefully eventually migrate to the RTDs given the big notices we've put on every wiki page
