### ISSUE TITLE
multiBigWigSummary 

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#235]
- is there a particular reason why multiBigWigSummary only works for two or more files?
Accepting single-files would be similar to UCSCtools:bigWigAverageOverBed

- we need to provide better description of the output files (-out / --outRawCounts) in particular we need to specify which summary of scores for given intervals is chosen (sum, average, median, ...)

"--BED bedfile Limits the correlation analysis to the ..." should be
"--BED bed file Limits the score summary to the ..."

**Comment by friedue** [comment]
bugger, I thought I had eliminated all mentioning of "correlation" from the multiBam* and multiBigwig* descriptions...will go through them again.

I tried to always give an example of the tabular output in the documentation, but I can be more specific in that case. It's the average, right?

**Comment by dpryan79** [comment]
The limit of 2+ files is artificial and trivial to remove. The question is how the produced npz file would be useful. We don't currently have any tools that would make use of this.

**Comment by dpryan79** [comment]
BTW, yes, it is indeed computing the average (https://github.com/fidelram/deepTools/blob/master/deeptools/getScorePerBigWigBin.py#L96), even though some of the code comments actually state otherwise (the stats() function in pyBigWig returns the mean, as did the equivalent in bx-python).

**Comment by thomasmanke** [comment]
as for the single bigwig file; the (optional) ascii output would basically be bed-graph, wouldn't it? That could be useful.

**Comment by dpryan79** [comment]
I suppose so. Once my PR passes in travis this will get fixed/closed.

**Comment by fidelram** [comment]
I wonder what would happen if someone tries to run plotCorrelate on the output from a single bigWig.

**Comment by dpryan79** [comment]
I never tried, that's why I mentioned in the usage that using a single file is only useful for creating a bedGraph file. I'll try plotCorrelation and plotPCA on a single one, though, just to see what happens. I assume plotPCA will throw an error at some point (after all, you can't do a PCA of 1 sample). plotCorrelation should actually work, and if it doesn't I'll fix that.

**Comment by dpryan79** [comment]
Hmm, scipy ends up throwing an error half the time. I'll just make them check for this and give an appropriate error message.

**Comment by dpryan79** [comment]
See https://github.com/fidelram/deepTools/commit/df289f1ef7db07ab582794debcef3ebb1205df75
