### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#237]
Python 2.7 is getting seriously long in the tooth. I think all of the requirements work with python3 already and if I can support both with the C API then this should be simple in pure python :)

Odds are that the 2to3 converter will make everything work.

Steps needed:
 - [x] Remove bx-python
 - [X] Add deeptoolsintervals
 - [x] Add twobitreader
 - [x] Run `2to3` and test

**Comment by fidelram** [comment]
I vote for this. We can start taking the steps listed here: https://docs.python.org/3/howto/pyporting.html

**Comment by dpryan79** [comment]
It looks like the only stumbling block for this is bx-python. It doesn't officially support python3 and given that that was tried and removed from the bioconda recipe, fixing it may be non-trivial.

**Comment by dpryan79** [comment]
Since we only use the 2bit and interval things, I can just write replacements if needed (I'd obviously prefer not to!).

**Comment by fidelram** [comment]
There is a bx-python3 https://bitbucket.org/mruffalo/bx-python3/overview

**Comment by dpryan79** [comment]
It might be easier to just not use bx-python. There's a `twobitreader` module that would at least take care of the 2bit stuff. That's written in pure python, so it might be a bit slow. There's also an intervaltree module that supports python 2 and 3. I might make a fork that uses those and see how the performance compares.

**Comment by dpryan79** [comment]
The `twobitreader` module needs a bit of work. I have a fork of it that removes a random `print()` that will break nose testing and confuse users. Aside from that, it generally seems to work.

**Comment by dpryan79** [comment]
I have one last PR on the `twobitreader` module, but otherwise that's working in Galaxy and the CLI. The author seems to be quick at accepting PRs, this issue should be closable soon.

**Comment by dpryan79** [comment]
I've started converting everything to python3. The biggest stumbling block at the moment is that any test that compares a text file whose header contains a python `dict()` (e.g., computeMatrix) will typically fail due to python3 having randomly ordered dictionaries.

**Comment by dpryan79** [comment]
This is essentially working now. The only thing failing are some of the image comparisons under python3 (these differ between OSX and Linux).

**Comment by dpryan79** [comment]
Shrug, sorting out the image comparison thing in python3 will be a large time sink. I'm just disabling testing of that component there, since the failing tests appear to produce identical images and the diffs mostly look like reordered lines or differences in floating point precision (e.g., an extra digit at the end of a coordinate).

Consequently, everything is passing. I'll keep this open, though until my most recent twobitreader PR is accepted, since that'll be needed to call things completely done. Nonetheless I'll go ahead and merge.

**Comment by fidelram** [comment]
Did you tried: http://matplotlib.org/devel/testing.html 

I tried to use it some months ago but failed because the required libraries were not in the matplotlib distribution.

**Comment by dpryan79** [comment]
I played with that a bit and it requires completely restructuring where everything is. That's not worth the effort.

**Comment by dpryan79** [comment]
Status update: My PR on twobitreader was accepted after an email to the author. I'm just waiting on the tarball to be made available on pypi (he may have forgotten that, I've sent an email). After that's there I'll make a conda package of it, put it in the Galaxy toolshed and then close this issue.

**Comment by dpryan79** [comment]
Twobitreader is now updated on pypi and available in bioconda and the Galaxy toolshed. There are likely a few obscure python3 bugs to squish still, but we'll only find that as we go.

**Comment by bgruening** [comment]
Awesome. Will be back soon to upload everything. Thanks a lot!
On Apr 22, 2016 1:26 PM, Devon Ryan <notifications@github.com> wrote:Twobitreader is now updated on pypi and available in bioconda and the Galaxy toolshed. There are likely a few obscure python3 bugs to squish still, but we'll only find that as we go.

**Comment by dpryan79** [comment]
I think yhoogstrate uploaded twobitreader to the toolshed already. Regarding the actual 2.3 release, that'll be a couple months. There were enough changes that this is going to need to simmer in testing for a while.
