### ISSUE TITLE
Compute matrix error when region are out of bound in the end of chromosome

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#250]
Hi,

I have just upgraded deeptool with "pip install deeptools" and I have some trouble with computeMatrix with the same data than before.

$ computeMatrix --version
computeMatrix 2.0.1

cmd : 
$ computeMatrix reference-point \
--regionsFileName Homo_sapiens.GRCh38.77.chromosomes.gene.bed \
--scoreFileName Sample_25.bw \
--outFileName Sample_25.genes.TSS.matrix.gz \
--outFileNameMatrix Sample_25.input_normalised.genes.TSS.tab \
--referencePoint TSS \
--upstream 2000 \
--downstream 2000 \
--binSize 10 \
--numberOfProcessors 20

log : 
*Warning* Duplicated region: ENSG00000279111 1:158578919-158579900.
[...]
24 (0.04) regions covering the exact same interval were foundFound:
        intervals: 60107
        no groups found
Warning:region too close to chromosome start for ENSG00000210049 MT:577:648.
Warning:region too close to chromosome start for ENSG00000211459 MT:648:1602.
Warning:region too close to chromosome start for ENSG00000210077 MT:1602:1671.
Warning:region too close to chromosome start for ENSG00000210082 MT:1671:3230.
Exception found. Message: Invalid interval bounds!
Problematic region: MT:16674-12674
Traceback (most recent call last):
  File "/mnt/data1/raoul.raffel/commun/tools/bin/computeMatrix", line 7, in <module>
    main()
  File "/mnt/data1/raoul.raffel/.local/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 366, in main
    hm.computeMatrix(scores_file_list, bed_file, parameters, verbose=args.verbose)
  File "/mnt/data1/raoul.raffel/.local/lib/python2.7/site-packages/deeptools/heatmapper.py", line 71, in computeMatrix
    mp_args).get(9999999)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
RuntimeError: Invalid interval bounds!

I think the region in bed is this : 
MT      14149   14674   ENSG00000198695 525     -

and the genome.fa.fai for MT is : 
MT      16569   2922919600      60      61

So with flanking region of 2kb from TSS this feature is out of bound and the process is killed. So we have to modify the bed annotations before using computeMatrix. 

Have you a solution to add NA or don't use this region ?

An other issue is that Mitochondrial chromosome is circular and so the features at boundaries can be keep and merged with the other part of chr.

**Comment by dpryan79** [comment]
This ends up being the same as #249 (I'll close this issue and reference it from there). In general, computeMatrix doesn't nicely handle invalid regions, which can happen both due to extending beyond the ends of a chromosome or due to using a chromosome not present in the bigWig files. My preferred solution would be to just screen out invalid regions, which would solve the problem (this is what many of the other tools do already).

It's unlikely that we'll get around to this until after the deepTools2 submission, which is next week.

**Comment by dpryan79** [comment]
We actually have a PR already in place that might solve this issue (and #249). Once it's merged in I'll test this specific case and reopen the issue if it's not fixed.

**Comment by dpryan79** [comment]
This seems to have been fixed a few minutes ago in #247. Go ahead and `pip install git+https://github.com/fidelram/deepTools.git --user --upgrade` and let me know if the problem persists.

**Comment by lelouar** [comment]
The problem seems to be fixed ;)

But an other issue that haven't seen before are appeared with the use of plotProfile : 

cmd: 
plotProfile \
--matrixFile Sample_25.mt.TSS.matrix.gz \
--outFileName Sample_25.mt.TSS.profile.png \
--plotHeight 5 \
--plotWidth 8 \
--refPointLabel TSS \
--plotTitle 'mt around TSS: H3K4me3_AN'

error:
Traceback (most recent call last):
  File "/mnt/data1/raoul.raffel/commun/tools/bin/plotProfile", line 4, in <module>
    from deeptools.plotProfile import main
  File "/mnt/data1/raoul.raffel/.local/lib/python2.7/site-packages/deeptools/plotProfile.py", line 9, in <module>
    from matplotlib import use
  File "/mnt/data1/raoul.raffel/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 124, in <module>
    from matplotlib.rcsetup import (defaultParams,
  File "/mnt/data1/raoul.raffel/.local/lib/python2.7/site-packages/matplotlib/rcsetup.py", line 34, in <module>
    from cycler import Cycler, cycler as ccycler
ImportError: No module named cycler


$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.get_distribution("matplotlib").version
'1.5.1'

**Comment by dpryan79** [comment]
@lelouar Thanks, that appears to be a matplotlib issue. It might be the case that you have a couple different copies of matplotlib getting used at once (don't ask me how that could happen...weird things happen sometimes). I would recommend removing matplotlib, checking `~/.local/lib/python2.7/site-packages` to ensure there are no remnant matplotlib files, and then reinstalling it. For some reason, it seems that `pip` occasionally misses things during an upgrade :(
