### ISSUE TITLE
change default width of profiler plots in Galaxy

### ISSUE THREAD

**Issue by friedue** [fidelram/deepTools#258]
I propose to change the default width of plotProfile plots (and heat maps, while we're at it) to **11 cm**. The current default width often leads to clashing labels. (Yes, I know, this depends on the regions that are chosen, however, it is consistently annoying me and I think the regions I am choosing are not completely unrepresentative.)
I can provide example plots if needed, but I find 11 cm for width a more reliably useful setting.

**Comment by fidelram** [comment]
The PR #260 changes the default values. We need to wait for @bgruening for green light.

**Comment by bgruening** [comment]
I like it!

**Comment by dpryan79** [comment]
I merged #260 in, so this should be done now.
