### ISSUE TITLE
allow the user to choose the linkage function

### ISSUE THREAD

**Issue by friedue** [fidelram/deepTools#264]
for hierarchical clustering, e.g. for ``plotCorrelation``

**Comment by vivekbhr** [comment]
@friedue I tested with all linkage methods and found insignificant differences between the clusters (1 out of thousands of regions here and there..). Do you think it's important?

**Comment by friedue** [comment]
depends on how difficult it is to implement. it's not a high priority fix.

**Comment by vivekbhr** [comment]
Not difficult. Just will create an additional input parameter (something like --hclust-linkage)

**Comment by friedue** [comment]
we can also put it on hold until someone needs it

**Comment by dpryan79** [comment]
I would recommend waiting until someone really really needs it. We have way too many options already.

**Comment by dpryan79** [comment]
Let's close and reopen if someone explicitly requests the feature and can make a compelling case.
