### ISSUE TITLE
plotCoverage in Galaxy currently _requires_ more than 1 BAM files as input

### ISSUE THREAD

**Issue by friedue** [fidelram/deepTools#269]
![screen shot 2016-02-02 at 12 12 04 pm](https://cloud.githubusercontent.com/assets/4973546/12757478/33a6a83a-c9a6-11e5-8988-f98791bb2ef3.png)
I don't think that's a meaningful requirement. Currently it simply fails when less than 2 BAM files are selected.

**Comment by dpryan79** [comment]
The input macro that this uses is shared with multiBamSummary and plotFingerprint. We explicitly don't want to allow single BAM input into multiBamSummary, so it would need to be modified accordingly.
