### ISSUE TITLE
computeMatrix --outFileNameData in version 2.0

### ISSUE THREAD

**Issue by dariober** [fidelram/deepTools#299]
Hello,

In deepTools version 1.5.x `computeMatrix` used to have the output option `--outFileNameData` which I found useful to make my own profile plots. Is there a replacement in version 2.0.x or later? Or the averages should be calculated offline from the matrix file?

This was the help related to `--outFileNameData`

```
--outFileNameData OUTFILENAMEDATA
                        Name to save the averages per matrix column into a
                        text file. This corresponds to the underlying data
                        used to plot a summary profile. Example: myProfile.tab
                        (default: None)
```

Thank you!
Dario

**Comment by dpryan79** [comment]
You have a couple options. While you could certainly calculate averages offline, it's probably more convenient to use the same option in `plotProfile`. Then the averages are already computed. Alternatively, in the next release this option will be available in `plotHeatmap`, though realistically speaking you could already use the `--outFileNameMatrix`option with `plotHeatmap`. Let me know if those don't suffice.

BTW, the reason that this was removed is that there's no perfect way to convey sample boundaries when more than one is used (I think this information is currently shoved into a comment line).

**Comment by dpryan79** [comment]
I'll close this for now. Feel free to reopen if what I mentioned above doesn't suffice.

**Comment by dariober** [comment]
Thank you Devon, sorry I forgot to reply earlier!
