### ISSUE TITLE
BamCoverage and RNA-seq generate bw with signs coming from split reads over introns

### ISSUE THREAD

**Issue by apastore** [fidelram/deepTools#307]
I am using deeptools on chip-sew data for some time and it is a great tool! 
Now I would like to generate a bw for RNA-seq data alligned with tophat2. I have notice that the coverage plot retain the intron region (and I guess this is due to split reads over the exon junction).

Could you suggest a way to get nicer bw files without coverage on intron form split reads?
Thanks!

**Comment by friedue** [comment]
Hi,
if you update to the latest deepTools version, split reads should be handled fine.

**Comment by dpryan79** [comment]
A word of advice, don't use the `--extendReads` option with spliced datasets, that'll also result in aberrant coverage of introns.

**Comment by apastore** [comment]
Thanks i will do! 
I am still on 1.5. Does update change the way how the coverage is computed (just wondering I I have to rerun all chip-seq sample or if I could use a mix of deeptools 1.5 and 2 for chip seq)
Any advice?
Best

**Comment by dpryan79** [comment]
The biggest difference is that read extension isn't done automatically in 2.0, but was in 1.5. It should be safe to just redo the RNAseq coverage (to be safe, you might rerun one ChIPseq file and double check that you get very very similar results, e.g., with `plotCorrelation`).

**Comment by apastore** [comment]
Thanks ! That was really helpful!
