### ISSUE TITLE
bioconda recipe version 2.2.0 still install computeMatrix 2.1.0

### ISSUE THREAD

**Issue by apastore** [fidelram/deepTools#310]
I have installed deeptools 2.2.0 with biconda but I still get computeMatrix 2.1.0

Thanks!

conda install deeptools=2.2.0 -f
/Users/alessandro/miniconda2/lib/python2.7/site-packages/clyent/__init__.py:10: UserWarning: Module _yaml was already imported from /Users/alessandro/miniconda2/lib/python2.7/site-packages/_yaml.so, but /usr/local/lib/python2.7/site-packages is being added to sys.path
  from pkg_resources import iter_entry_points
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: ..............................
Package plan for installation in environment /Users/alessandro/miniconda2:

The following packages will be UPDATED:

    deeptools: 2.2.0-py27_0  --> 2.2.0-py27_0

computeMatrix --version
computeMatrix 2.1.0

**Comment by dpryan79** [comment]
It's likely that the version number is just wrong (I really dislike how we have this implemented). If you run `computeMatrix --help` do you see an option like `--unscaled5prime`? If so, then you have version 2.2 and the version string is just wrong.

**Comment by apastore** [comment]
No, This was exactly where I realized there are something wrong with the recipe … I just download and install from github and it run with the unscaled parameter.

By the way which is the best way to set the unscaled5prime , unscaled3prime regionBodyLength to make a plot similar to the gene body option in neg.plot? I use a bed file generate from UCSC genePred

Thanks!

**Comment by dpryan79** [comment]
Hmm, that means that the file is wrong on pypi. I'll investigate that.

I've never used ngs.plot, so I can't comment on the remainder.

**Comment by apastore** [comment]
Thanks!

**Comment by dpryan79** [comment]
For some reason your shell is still getting the old version rather than the newer one you have installed. I just created a clean miniconda environment and ran `conda install -c bioconda deeptools` and this is what I get:

    ryan@pc331:~$ which computeMatrix 
    /home/ryan/miniconda2/bin/computeMatrix
    ryan@pc331:~$ computeMatrix --version
    computeMatrix 2.2.0
    ryan@pc331:~$ computeMatrix scale-regions --help 2>&1 | grep unscaled5prime
      --unscaled5prime UNSCALED5PRIME

My guess is that `which computeMatrix` will help clarify why the wrong version is getting called. The simplest resolution would be to remove deeptools, remove any remnant copies that anaconda missed, and then reinstall it.

**Comment by fidelram** [comment]
Check that you don't have PYTHONPATH set. Most of the issues reported in
the mailing list similar to this are due to incorrect PYTHONPATH.

-fidel

On Thu, Mar 3, 2016 at 10:27 PM, Devon Ryan <notifications@github.com>
wrote:

> For some reason your shell is still getting the old version rather than
> the newer one you have installed. I just created a clean miniconda
> environment and ran conda install -c bioconda deeptools and this is what
> I get:
>
> ryan@pc331:~$ which computeMatrix
> /home/ryan/miniconda2/bin/computeMatrix
> ryan@pc331:~$ computeMatrix --version
> computeMatrix 2.2.0
> ryan@pc331:~$ computeMatrix scale-regions --help 2>&1 | grep unscaled5prime
>   --unscaled5prime UNSCALED5PRIME
>
> My guess is that which computeMatrix will help clarify why the wrong
> version is getting called. The simplest resolution would be to remove
> deeptools, remove any remnant copies that anaconda missed, and then
> reinstall it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/310#issuecomment-191971767>.
>



-- 

Fidel Ramirez
