### ISSUE TITLE
computeMatrix using more than 100% CPU

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#317]
Hi, I am getting complaints from my sysadmin that when I run computeMatrix on a submitted job to the cluster, it uses more than 100% of 1 CPU.

Is there a way to restrict the CPU usage of computeMatrix?

I am using:
```
$HOME/.local/bin/computeMatrix --version
computeMatrix 1.5.12
```

**Comment by dpryan79** [comment]
You have two options. Firstly, you could use `-p 1` to tell it to only use a single core. Alternatively, if you want everything to be single-threaded then you can edit the config file. This file should be `$HOME/.local/lib/python2.7/site-packages/deeptools/config/deeptools.cfg`. If you change:

    default_proc_number: max/2

to 

    default_proc_number: 1

then everything should be single threaded.
