### ISSUE TITLE
fragmentLength equivalent in recent bamCoverage version?

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#318]
Hi,

I used to run bamCoverage like so:

```
bamCoverage -b my.bam --fragmentLength 1 -o my.bam.bw
```
what is the equivalent command for a recent version like 2.2.2-3?

**Comment by fidelram** [comment]
just remove --fragmentLength 1 and you will get the same output as before.
DeepTools2, by default does not do read extension.

-fidel

On Tue, Mar 15, 2016 at 12:04 PM, Albert Vilella <notifications@github.com>
wrote:

> Hi,
>
> I used to run bamCoverage like so:
>
> bamCoverage -b my.bam --fragmentLength 1 -o my.bam.bw
>
> what is the equivalent command for a recent version like 2.2.2-3?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/fidelram/deepTools/issues/318
>



-- 

Fidel Ramirez
