### ISSUE TITLE
plotHeatmap equivalent of this heatmapper command

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#319]
Any ideas how to upgrade to 2.2 for this command?

```
/usr/bin/plotHeatmap --colorMap hsv --heatmapWidth 7.5 --matrixFile my.bam.dtmat.tab.gz --sortUsing mean --outFileName my.bam.dtmat.heatmap.alignment_overview.pdf --plotTitle "foo -- t250 p50" --whatToShow "plot, heatmap and colorbar" --regionsLabel cpgsets --missingDataColor "#FFFFFF" --zMin 0 --zMax 100
```

**Comment by fidelram** [comment]
Is there anything that does not work for you using that command with
version 2.2 ?


On Tue, Mar 15, 2016 at 5:11 PM, Albert Vilella <notifications@github.com>
wrote:

> Any ideas how to upgrade to 2.2 for this command?
>
> /usr/bin/plotHeatmap --colorMap hsv --heatmapWidth 7.5 --matrixFile my.bam.dtmat.tab.gz --sortUsing mean --outFileName my.bam.dtmat.heatmap.alignment_overview.pdf --plotTitle "foo -- t250 p50" --whatToShow "plot, heatmap and colorbar" --regionsLabel cpgsets --missingDataColor "#FFFFFF" --zMin 0 --zMax 100
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/fidelram/deepTools/issues/319
>



-- 

Fidel Ramirez
