### ISSUE TITLE
bamCoverage:  assert(bw is not None) AssertionError

### ISSUE THREAD

**Issue by pkhoueiry** [fidelram/deepTools#324]
Dear all,

bamCoverage  (version 2.2.2-11-34e97d3) is throwing an error linked to bedGraphToBigWig conversion.
Here is the command that I am using:
python-2.7 $DEEPTOOLS/bamCoverage --bam bam/sample.1.raw.sorted.bam --binSize 50 --normalizeTo1x 2451960000 --extendReads 300 -o bw/sample1.bw -v -p 30 --outFileFormat bigwig

The file produced is in bedgraph with ".bg" as extension.
(bamCoverage 1.6 works fine though)

here is the traceback:

Traceback (most recent call last):
  File "bamCoverage", line 7, in <module>
    main()
  File "bamCoverage.py", line 251, in main
    format=args.outFileFormat, smoothLength=args.smoothLength)
  File "writeBedGraph.py", line 158, in run
    chrom_names_and_size, bedgraph_file, out_file_name, True)
  File "writeBedGraph.py", line 320, in bedGraphToBigWig
    assert(bw is not None)
AssertionError

**Comment by dpryan79** [comment]
Out of curiousity, what version of pyBigWig do you have installed (`pip freeze | grep pyBigWig`).

**Comment by dpryan79** [comment]
Also, what if you do the following from within python:

    import pyBigWig
    bw = pyBigWig.open("bw/sample1.bw", "w")
    assert(bw is not None)

Does the assertion step throw an error or do you get one beforehand?

**Comment by pkhoueiry** [comment]
1) pyBigWig version:  1.0.8 (obtained from PKG-INFO file since I do not have pip installed)
2) here is the output obtained regarding your request:
>>> import pyBigWig
>>> bw = pyBigWig.open("bw/sample1.bw", "w")
>>> assert(bw is not None)
TypeError: function takes exactly 1 argument (2 given)

Seems like the assertion is throwing an error.

**Comment by dpryan79** [comment]
Please upgrade pyBigWig to the most 0.2.7 (1.0.8 should have been labeled 0.1.8, that was a mistake on pypi).

**Comment by dpryan79** [comment]
BTW, the assertion is causing a problem due to the old version of pyBigWig. The one you're using didn't support writing files, only reading them. This was changed starting with 0.2.0, which is required by deepTools.

**Comment by pkhoueiry** [comment]
It worked,
Thanks Davon,

**Comment by dpryan79** [comment]
Glad that solved it!
