### ISSUE TITLE
Per-sample numeric summary output from plotFingerprint

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#328]
There's been some internal requests for a single metric attached to each sample from `plotFingerprint`. This could then be used in a more automated manner to flag samples by quality. The current contenders for a metric are: AUC, X-intersect, and elbow point (likely the point with the maximum second derivative).

I'll make a branch with that can output each of those and have them tested on known good/bad samples. Perhaps one of these will be very useful, perhaps not, we'll see.

**Comment by friedue** [comment]
but bad H3K4me3 samples look very similar to good H3K27me3 samples...how will you take that into account?

**Comment by dpryan79** [comment]
At some point the user would need to have an understanding of what he/she is doing. The idea is to give groups like DEEP a convenient way of screening samples.

**Comment by friedue** [comment]
so rather than a binary flag, this tool should generate a score and based on previous screenings/public data, one could come up with ranges that are expected for good samples of narrow and broad marks and visually show where the new samples fall.
this sounds like an additional tool, though, e.g. "compareFingerprints"

**Comment by friedue** [comment]
sounds like a neat Bachelor thesis project :)

**Comment by fidelram** [comment]
Having a number to summarize the results is the first step to allow comparisons which could be done later.

**Comment by friedue** [comment]
so what exactly do you mean with X intersect?

**Comment by asrichter** [comment]
Intersection of curve with x axis, i.e. fraction of genome not covered by reads.

________________________________
Von: Friederike Dündar <notifications@github.com>
Gesendet: Montag, 4. April 2016 16:05
An: fidelram/deepTools
Betreff: Re: [fidelram/deepTools] Per-sample numeric summary output from plotFingerprint (#328)


so what exactly do you mean with X intersect?

-

**Comment by dpryan79** [comment]
I suspect that the x intersect will end up being some small value > 0, but we'll try >0 first :)

**Comment by friedue** [comment]
the point where the curve stops intersecting the x used as a measure for the sequencing depth?

**Comment by dpryan79** [comment]
It's a measure both for the sufficiency of the sequencing depth but also how good/sharp the peaks will be. It's the fraction of the genome lacking signal, which even for sharp peaks is normally relatively low. I suspect that this or something like it can always get output, since it might always be useful (the perpetual, "How much more should we have sequenced?", question).

**Comment by asrichter** [comment]
@friedue: yes

@dpryan79: can also be a larger value if you have perfect enrichment or low sequencing depth

**Comment by friedue** [comment]
In any case, the last point of x axis intersect will likely also influence the AUC, for example.

Actually, Andreas has a an excellent point: in a perfect ChIP sample, there shouldn't be any background, hence, the portion of the genome covered should be rather small...the question "how many more reads??" is particularly difficult to answer for ChIP-seq

**Comment by dpryan79** [comment]
I'm not so sure that a perfect ChIP has ever been performed.

Anyway, feel free to play around with the "feature/implement328" branch. It adds a `--outQualityMetrics` option to `plotFingerprint`. The columns are: sample label, AUC, X intersect, and elbow point.

As an aside, I played around with using the maximum of the second derivative as the elbow. That ends up picking up what I suspect are regions that should be blacklisted instead (that's where the sharpest change in slope is). In hindsight, perhaps that shouldn't have been surprising.

**Comment by friedue** [comment]
I'm pretty sure that a perfect ChIP has never been performed, but if you want to use a score as a quality measure for ChIP, one should be aware of the ambiguous nature of the fingerprints.
What do you use for the elbow point now?

**Comment by dpryan79** [comment]
The furthest point from the diagonal.

**Comment by dpryan79** [comment]
The Galaxy wrapper has been updated to handle this. Once I hear back about whether the KL divergence or Jensen-Shannon distance are useful (I expect not) I'll merge and close this.

**Comment by dpryan79** [comment]
The Jensen-Shannon distance with a modified implementation turns out to be useful and is now implemented (if a reference sample is specified). This now seems to be working in Galaxy and I'll merge that into develop today and close this.
