### ISSUE TITLE
deeptools correctGCBias process sleeping??

### ISSUE THREAD

**Issue by amitgsir** [fidelram/deepTools#332]
Hi,

I am using deeptools for the GBcorrection of my genomic BAM files.

However, sometimes, computeGCBias or correctGCBias just hands, and it is not using any real CPU on top command in linux.

E.g. I used max/2 cpu (default option for processor) and my other process are using just 12core on my 48core server.

In this case, correctGCBias is using just around 4-6 core, and each core is also using just 0.3~0.5% of each core and vely low RAM too.

This is not very common, but we have encountered this issue quite a few times.

Any idea, what may be causing this and how to solve??

My server is still having free CPU (just using 22% CPU power, and free RAM).

Thanks,
Amit

**Comment by amitgsir** [comment]
I am using deeptools 1.5.11 version

**Comment by vivekbhr** [comment]
@amitgsir could you try using the newer release (2.2.2) and check if the problem persists?

**Comment by amitgsir** [comment]
Hi @vivekbhr,

I will check the new version.
Just curious if you have encountered the similar issue.

**Comment by dpryan79** [comment]
We've not run into this internally, though we use `correctGCBias` rarely enough that it's certainly possible that we've missed a bug.

**Comment by amitgsir** [comment]
Okay~~I will check the new build and will notify if encounter the similar issue.

**Comment by dpryan79** [comment]
Go ahead and either open a new issue or reopen this one if this continues to happen in the updated release.
