### ISSUE TITLE
computeMatrix mean, min, max, etc are NaN if any of the bigwig values is nan

### ISSUE THREAD

**Issue by fidelram** [fidelram/deepTools#333]
When computing the average over a bin, compute matrix becomes NaN if any of the values is a NaN.

This can be solved by setting --missingDataAsZero; however for some cases this is not desirable and instead NaNs should be simply ignored. For damID data and ChIP-chip data that only probe a fraction of the genome, most of the scores are NaN but is not wise to turn them into zeros for averaging.

A trivial solution is to always ignore NaNs in bins (unless the whole bin is empty) but before I implement this I would like to hear if there is any compelling reason to instead add yet a new parameter to control for this.

**Comment by fidelram** [comment]
Actually, I just noticed that this is the way is implemented already in the code. I am checking now if it is working properly because I am getting a lot of bins with NaNs

**Comment by foehnwind** [comment]
v3.1.2 still can generate a matrix with lots of nans, even through the bigwig input doesn't contain any NAs. Not sure how are NAs introduced during computeMatrix...

**Comment by dpryan79** [comment]
Please provide me with an example bigWig(s) if this is still occurring.
