### ISSUE TITLE
computeGCBias.py can't handle --blackListFileName

### ISSUE THREAD

**Issue by kashyapchhatbar** [fidelram/deepTools#334]
The rest of the tools are fine with it, however `computeGCBias` is not considering `--blackListFileName` properly

Here's the error

```bash
~ @
❯ computeGCBias -b bowtie_sorted/Input_WT_rep1.bam -bl mm9-blacklist.bed -freq freq.txt --effectiveGenomeSize 2150570000 -g mm9.2bit -l 120
Traceback (most recent call last):
  File "/usr/bin/computeGCBias", line 7, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/deeptools/computeGCBias.py", line 623, in main
    filter_out_file = args.BlackListFileName
AttributeError: 'Namespace' object has no attribute 'BlackListFileName'
```

It's showing the error [here](https://github.com/fidelram/deepTools/blob/master/deeptools/computeGCBias.py#L623-624). I think it's a typo for `blackListFileName` argument and also since the new implementation of blacklist file, `filterOut` argument is not required. 

Huge thanks for the awesome tool :+1:

**Comment by dpryan79** [comment]
I've merged the fix for this. I'll try to coordinate getting version 2.2.3 on pypi/bioconda/Galaxy today.

**Comment by dpryan79** [comment]
Ping @bgruening @fidelram

**Comment by bgruening** [comment]
Okidoki!

**Comment by kashyapchhatbar** [comment]
Confirming that the fix is working! Thanks :)

**Comment by dpryan79** [comment]
Great, thanks for letting us know!
