### ISSUE TITLE
galaxy filters gene names

### ISSUE THREAD

**Issue by fidelram** [fidelram/deepTools#335]
The following error occurs in galaxy when trying to filter the chromosome name from  E. coli strain UTI89: 'gi|91209055|ref|NC_007946.1'

NameError: Unknown chromosome: chrgiX91209055XrefXNC_007946.1X
Known chromosomes are: ['gi|91209055|ref|NC_007946.1|']

The chr is added by the code in an attempt to find a matching chromosome. But the pipes are replaced by 'X'.

**Comment by bgruening** [comment]
This is because we sanitize text inputs by default. I guess it is save to disable it, or explicitly allow pipes as input ...

**Comment by fidelram** [comment]
As long as the text is put into quotes and quotes are escaped it should be fine.

**Comment by dpryan79** [comment]
On the plus side, NCBI is apparently phasing out putting pipes in names like this :)

**Comment by bgruening** [comment]
@fidelram it's not that easy. A text input can also be `"; rm -rf; echo "` or something like that.

**Comment by dpryan79** [comment]
Pacifying user input is the single most annoying thing about webapp development :(

**Comment by fidelram** [comment]
Other option is to turn pipes into something else than 'X' that can be transformed back into a pipe in the python code. Something that normally does not appear on a gene name. 

But going back to your example: If a user adds something like `"; rm -rf; echo "` this should be sanitized as `'\"; rm -rf; echo \"'` which should be innocuous.

**Comment by bgruening** [comment]
@fidelram not if you turn off the sanitizer :).
But I can explicitly allow the pipe to not be sanitized, if not we can use you approach and deal with this on the python side. I think it is actually replaced by `__X__` isn't it?

**Comment by dpryan79** [comment]
According to the mailing list, it was just `X`. `__X__` would be MUCH easier to deal with.

**Comment by bgruening** [comment]
Mh, ok I'm was thinking it is using this here: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/util/__init__.py#L416

I will work on this today, and will explicitly allow pipes.

**Comment by bgruening** [comment]
No test yet. I need to think about this.
Hopefully this will work: https://github.com/fidelram/deepTools/compare/pipes?expand=1

**Comment by dpryan79** [comment]
@bgruening: Should this be closed now or should we run a couple quick tests on Monday?

**Comment by bgruening** [comment]
Yes. Hopefully it is fixed and both TS are updated to 2.2.3.
