### ISSUE TITLE
filter reads based on template size

### ISSUE THREAD

**Issue by samuelCollombet** [fidelram/deepTools#336]
It would be very nice to have an option do filter (paired-end) reads depending on their template/fragment size. specially for the program bamCoverage / bamCompare.

**Comment by dpryan79** [comment]
Normally this would be determined by the aligner marking things as properly paired or not, no?

**Comment by samuelCollombet** [comment]
dpryan79 not sure what you mean? indeed this make only sense for properly paired reads (otherwise the template length in the bam file ill be 0 I guess). 
I would liek to be able to selected only fragments (ie both paired reads) if the framgnet size that more than x and less than y bp.

**Comment by dpryan79** [comment]
Normally one gives the aligner information about the proper fragment size distributions and the properly paired bit in the flag is then set accordingly. That would then be what's used for filtering.  I'm not sure of any normal use case for needing to filter by fragment size otherwise.

**Comment by dpryan79** [comment]
Ah, we were just talking about this and thought about ATACseq. It makes sense, so we can add this.

**Comment by dpryan79** [comment]
This is a very easy thing to implement, we can include it in the 2.3 release.

**Comment by samuelCollombet** [comment]
Exactly! (could have mentioned ATACseq from the begining :D ). Thanks!

**Comment by dpryan79** [comment]
This is now included in the `develop` branch, so it'll be present in the 2.3 release. The options are called `--minFragmentLength` and `--maxFragmentLength`.

**Comment by samuelCollombet** [comment]
Great thanks! 
One question though: when filtering out some reads, what value is used to make the RPKM scaling? total number of sequenced reads or total number of filtered reads?

**Comment by dpryan79** [comment]
In 2.3 it's the estimated number of reads after filtering and blacklisting. In 2.2 it's the total number of reads (possibly sans reads in blacklisted regions).

**Comment by samuelCollombet** [comment]
and in develop version? ;)

**Comment by dpryan79** [comment]
`develop` is what will become 2.3, so the former.

**Comment by samuelCollombet** [comment]
Perfect Thanks a lot!

**Comment by dpryan79** [comment]
In fact you'll get something printed to the screen describing the estimated fraction of reads filtered given the criterion you specify (including fragment size min/max).
