### ISSUE TITLE
bamPEFragmentSize max fragment size shown on plot

### ISSUE THREAD

**Issue by samuelCollombet** [fidelram/deepTools#337]
Would be nice to have the option to change the max value on the x axis. 
I am using it to visualized the fragment distribution of ATACseq data, and 2 x mean of fragment size is not enough. I personally change the parameter in the .py file ([mean] x 2 changed for [max]), but it would be ncie to be able to change the parameter on the fly.

**Comment by dpryan79** [comment]
Indeed, this probably works poorly for ATACseq. Should be an easy enough change. Were you thinking of having some sort of `max length` parameter or instead one to just change the `2` to some user-specified value? Either would be possible and we can do whichever is preferred.

**Comment by samuelCollombet** [comment]
In my case I prefer to use the max, so I know what value it is, but it might depends on the user preference.
Also Just realized, havign the possibiltiy ot have the frequency in log scale would be nice :)

**Comment by dpryan79** [comment]
OK, user-specified max value and a log scale option. Those are quick and easy.

**Comment by samuelCollombet** [comment]
Cool! Thanks a lot!

**Comment by dpryan79** [comment]
I just added this to `develop` both via the CLI and Galaxy. There's now a `--maxFragmentLength` parameter to set the X axis maximum and a `--logScale` option that toggles plotting log frequencies. This are both great ideas, thanks for the suggestion!
