### ISSUE TITLE
commandLine: BED-output of clustered heatmap cannot be directly re-used with computeMatrix

### ISSUE THREAD

**Issue by friedue** [fidelram/deepTools#34]
The issue is caused by the lack of # lines in the output of heatmapper nowadays. To make heatmapper etc. work with Galaxy, Bjoern added the feature that the cluster ID is indicated in the 7th column of a bed-file, so that users can easily separate the file into separate data sets and supply them individually to computeMatrix. On the command line, computeMatrix expects just one BED file where the groups are separated by #. That means that currently the user needs to know that he has to turn the file with the format:
    
    chr1 10 12 Cluster1
    chr1 20  22 Cluster2

into a file like this:

    chr1 10 12
    # cluster1
    chr1 20  22
    # cluster2 

Perhaps we can come up with a more elegant solution in the future.

**Comment by vivekbhr** [comment]
As per this discussion, column 7 is in abuse now, and we can use *plotheatmap* output for *computematrix* in Deeptools-2.0.
