### ISSUE TITLE
bamPEFragsize for multiple bam-files

### ISSUE THREAD

**Issue by vivekbhr** [fidelram/deepTools#341]
I wanted to implement this at some point but couldn't follow up on that. bamPEFragsize can take only one bam-file at this moment but it will be good if it can take multiple, and make an overlapping histogram (with some transparency) with one color per sample.. Typically we have 6 samples for RNA-Seq (3 cont, 3 test) so it will be good to check the distribution of all of them in one plot (so max 6-8 different colors) ..

**Comment by dpryan79** [comment]
I would suggest that instead of using transparency to plot multiple samples on the same plot, that instead subplots be used (e.g., with plotProfile or plotEnrichment).

**Comment by vivekbhr** [comment]
Yah I think that would also be fine :+1: .. I thought overlaying will help to quickly compare samples, but with >8 samples it will get complicated due to multiple color contrasts..
