### ISSUE TITLE
computeMatrix - cannot open *.bw a second time if in read-only directory

### ISSUE THREAD

**Issue by MWSchmid** [fidelram/deepTools#349]
Hi

Thanks for the tools - nice work.

I encountered an error with "computeMatrix" (version 2.2.3-6-43d23f4). If I try to use the same set of *.bw files for several rounds of "computeMatrix", it fails to open the *.bw files after the first usage. It's important to mention that this only happens if the *.bw files are located in a read-only directory (in my case it was a cifs-mounted samba share, you can only write on it with sudo...).

Example:
```sh
for PEAKFILE in *.bed; do
computeMatrix reference-point -S /myData/*.bw -o ${PEAKFILE//.bed}.mat.gz -R $PEAKFILE --referencePoint center -a 5000 -b 5000 --skipZeros
done
```
This works with the first PEAKFILE (*.bed), but throws an error at the second round, if "/myData" is read-only (otherwise it works fine).

Best regards,

Marc

**Comment by dpryan79** [comment]
Hi Marc,

That's a new one. Do you get an error message of some sort?

Devon

--
Devon Ryan, Ph.D.
Email: dpryan@dpryan.com
Data Manager/Bioinformatician
Max Planck Institute of Immunobiology and Epigenetics
Stübeweg 51
79108 Freiburg
Germany
<devon.ryan@dzne.de>

**Comment by MWSchmid** [comment]
Yes - looks like this:

[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
[urlOpen] Couldn't open /myData/blaba.raw.bw for reading
Traceback (most recent call last):
  File "/usr/local/bin/computeMatrix", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/deeptools/computeMatrix.py", line 389, in main
    hm.computeMatrix(scores_file_list, bed_file, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose)
  File "/usr/local/lib/python2.7/dist-packages/deeptools/heatmapper.py", line 83, in computeMatrix
    mp_args).get(9999999)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
RuntimeError: Received an error during file opening!

**Comment by dpryan79** [comment]
That's rather unusual. This only happens if `fopen()` can't open a file. I suspect that your file system has things locked somehow. What happens if you open two terminals, start python in both, and type the following:

    import pyBigWig
    bw = pyBigWig.open("/myData/blaba.raw.bw")

Presumably that would give you the same error, but it's good to check.

**Comment by dpryan79** [comment]
Is it possible that you're running out of memory? That's the only explanation I can come up with.

**Comment by dpryan79** [comment]
If you could install the `fopen_debug` branch of pyBigWig with something like `pip install --upgrade git+https://github.com/dpryan79/pyBigWig.git@fopen_debug` and then try this again, you'll get a hopefully more informative error message. That should give us more to go on.

**Comment by MWSchmid** [comment]
Hm - it's quite obscure... 
- Opening two python consoles and doing pyBigWig.open(...) worked.
- Then I tried the exact same command on the same machine again - works today - failed yesterday.
- RAM is unlikely - the machines have 64 and 128 GB - most of it was free at the time I tried it.

I have the feeling that it is linked to the samba share (I'm running a samba server with a large volume which is mounted on several machines - all on a cloud infrastructure). Given that the setting is slightly special, I think that you can close the Issue - it won't happen too often and is likely not worth your effort.

**Comment by dpryan79** [comment]
Fair enough. You might still install the pyBigWig branch that I mentioned, it'll at least help point to the root cause. Thanks for the update!
