### ISSUE TITLE
bedGrapthToBigWig error when running bamCoverage

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#351]
I am running bamCoverage from deeptools version 2.2.3 in a computer cluster and I am getting this error below. I presume this is because the deeptools installation clashes with other versions of libraries I have in my $PATH or $PYTHONPATH.

Any ideas where this `bedGraphToBigWig` error comes from? Which clashing libraries should I check?

Thx,

A.

```
bamCoverage --version
bamCoverage 2.2.3
```

```
verbose: False
out_file_for_raw_data: None
numberOfSamples: None
bedFile: None
bamFilesList: ['/bi/group/cegx/CEGX_Run181/CEGX_Run181-12345678/CEG40_71_3-35428554/Data/Intensities/BaseCalls/bismark/CEG40-71-3_S1_L001_R1_001.cutB.sorted.mrgd.standard.karyotype.bam']
ignoreDuplicates: False
numberOfProcessors: 1
samFlag_exclude: None
save_data: False
blackList: None
stepSize: 50
smoothLength: None
center_read: False
defaultFragmentLength: read length
chrsToSkip: []
region: None
maxPairedFragmentLength: 1000
samFlag_include: None
binLength: 50
blackListFileName: None
minMappingQuality: None
zerosToNans: False
Traceback (most recent call last):
  File "/bi/apps/python/2.7.3/bin/bamCoverage", line 7, in <module>
    main()
  File "/bi/apps/python/2.7.3/lib/python2.7/site-packages/deeptools/bamCoverage.py", line 251, in main
    format=args.outFileFormat, smoothLength=args.smoothLength)
  File "/bi/apps/python/2.7.3/lib/python2.7/site-packages/deeptools/writeBedGraph.py", line 158, in run
    chrom_names_and_size, bedgraph_file, out_file_name, True)
  File "/bi/apps/python/2.7.3/lib/python2.7/site-packages/deeptools/writeBedGraph.py", line 320, in bedGraphToBigWig
    assert(bw is not None)
AssertionError
```

**Comment by vivekbhr** [comment]
It seems simply that the output file name wasn't given or the path was not writable. Can you paste the command?

**Comment by avilella** [comment]
I tried it with a small test.bam file and still the same issue. I can
create files in that directory without a problem:

```
touch ./file.txt
bamCoverage -b test.bam -o test.bam.bw
verbose: False
out_file_for_raw_data: None
numberOfSamples: None
bedFile: None
bamFilesList: ['test.bam']
ignoreDuplicates: False
numberOfProcessors: 4
samFlag_exclude: None
save_data: False
blackList: None
stepSize: 50
smoothLength: None
center_read: False
defaultFragmentLength: read length
chrsToSkip: []
region: None
maxPairedFragmentLength: 1000
samFlag_include: None
binLength: 50
blackListFileName: None
minMappingQuality: None
zerosToNans: False
Traceback (most recent call last):
  File "/bi/apps/python/2.7.3/bin/bamCoverage", line 7, in <module>
    main()
  File
"/bi/apps/python/2.7.3/lib/python2.7/site-packages/deeptools/bamCoverage.py",
line 251, in main
    format=args.outFileFormat, smoothLength=args.smoothLength)
  File
"/bi/apps/python/2.7.3/lib/python2.7/site-packages/deeptools/writeBedGraph.py",
line 158, in run
    chrom_names_and_size, bedgraph_file, out_file_name, True)
  File
"/bi/apps/python/2.7.3/lib/python2.7/site-packages/deeptools/writeBedGraph.py",
line 320, in bedGraphToBigWig
    assert(bw is not None)
AssertionError
```

**Comment by dpryan79** [comment]
What version of pyBigWig do you have installed? My only guess is that python is using a version from before bigWig files could be written.

**Comment by avilella** [comment]
This is on a cluster administered by the sysadmins, so I searched for
bigwig in the $PATH and found this:

```
echo $PATH | perl -lne 's/\:/\n/g; print' | xargs -n1 -P8 -I % find %
-iname "*BigWig*" 2>/dev/null
/bi/apps/python/2.7.3/bin/multiBigwigSummary
/bi/apps/python/2.7.3/bin/bigwigCompare
/bi/apps/python/2.7.3/bin/bed_bigwig_profile.py
echo $PYTHONPATH | perl -lne 's/\:/\n/g; print' | xargs -n1 -P8 -I % find %
-iname "*BigWig*" 2>/dev/null
```

**Comment by dpryan79** [comment]
`pip list | grep pyBigWig`

**Comment by avilella** [comment]
I tried it in the cluster, and I get 0.1.9 as the version of pyBigWig.

I then tried it in the local computer that I administer myself, where the
same test.bam works fine, and I get:

```
pip list | grep pyBigWig
pyBigWig (0.2.5)
 ```

Is this the possible culprit? I need to ask the sysadmin to update or find
a way to point deeptools to the copy of a newer version after doing `pip
install --user pyBigWiw`

**Comment by dpryan79** [comment]
Yes, that's the problem. Please ask the sysadmins to install the version of pyBigWig (and everything else) required by deepTools-2.2.3. You could install deepTools yourself on the cluster (e.g., in a virtualenv), but if the sysadmins are making the software available already then having them upgrade things appropriately is preferable.

**Comment by avilella** [comment]
I think the problem that I have an old pyBigWig library version in `$HOME/.local`.

How do I cleanly get rid of it so it does not affect deeptools?

**Comment by dpryan79** [comment]
You should be able to:

    cd $HOME/.local/python2.7/site-packages
    ls pyBigWig*
    rm -rf pyBigWig*

Double check that the `ls` command only shows `pyBigWig.so` and the `pyBigWig-0.2.7.egg-info/` and `pyBigWigTest/` directories before deleting them.
