### ISSUE TITLE
Ribosomal profiling with bamCoverage

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#352]
It would be nice to be able to use bamCoverage meaningfully to look at ribosomal profiling. The new metagene options are largely doing that, but we need to add a modified version of the `--MNase` option. The difference to `--MNase` will be that single-end reads will be needed and the resulting signal will be the 1 base at the center of each read.

This would also demonstrate a nice usage of both the metagene summarization but also using a GTF file with an alternate `--exonID` (CDS, rather than exon). We'll have to play around with a public dataset to see how even length reads should be treated, since their center is between two bases.

**Comment by dpryan79** [comment]
I might also write a little post-processing script to take the output of computeMatrix and split each line into 3 entries (one for each reading frame). That'd allow things like figure 1A below (from [here](http://www.nature.com/cr/journal/v24/n7/full/cr201474a.html))

![figure 1A](http://www.nature.com/cr/journal/v24/n7/images/cr201474f1.jpg)

**Comment by dpryan79** [comment]
The bamCoverage changes might also require using strand information to exclude random antisense alignments (it'd be good to support this anyway).

**Comment by dpryan79** [comment]
A bit of reading indicates that instead of centering, one uses a fixed offset from the start of the read (normally either 12 or 15 bases, for the P or A site). The correct offset yields a nice peak at the `AUG` (and/or stop codon). Apparently in an ideal world each read length (they need to be adapter but not quality trimmed) would have its own offset, but this seems to be largely overkill.

**Comment by dpryan79** [comment]
I just added a branch where `bamCoverage` has a `--RiboSeq` option. This needs testing, of course, and I still need a script to post process the output of computeMatrix to merge files and split by frame.

**Comment by steffenheyne** [comment]
Is ribosome profiling mainly/only performed via single-end sequencing? We would exclude the combination of a paired-end bam and --RiboSeq?

**Comment by dpryan79** [comment]
Correct, one only does SE sequencing. I'm currently excluding PE alignments for that reason.

**Comment by friedue** [comment]
maybe we should think about implementing certain default settings? i.e., `bamCoverage rifseq`, `bamCoverage strandedRNA-seq`, `bamCoverage genomicDNA` as short-cuts for certain combinations of useful parameter settings.

**Comment by dpryan79** [comment]
If we allow negative values as the offset, then we can use the same method to support GRO-seq and PRO-seq. I assume that people only pay attention to the last base of each read in such cases, but I'll check into that since we're now working on those a bit internally.

**Comment by dpryan79** [comment]
This has now been merged into `develop`.
