### ISSUE TITLE
matplotlib colormaps link has a wrong redirect

### ISSUE THREAD

**Issue by martenson** [fidelram/deepTools#355]
present here: https://github.com/fidelram/deepTools/blob/master/galaxy/wrapper/deepTools_macros.xml#L500

reported here: https://biostar.usegalaxy.org/p/17428/

**Comment by fidelram** [comment]
Thanks for reporting. The right reference is http://matplotlib.org/1.4.3/users/colormaps.html

**Comment by vivekbhr** [comment]
@fidelram is it fixed in the wrapper? else I can include in #354 ..

**Comment by dpryan79** [comment]
I merged a fix from @bgruening. He can push out a wrapper update to the toolshed whenever he wants then.
