### ISSUE TITLE
README.txt for deeptools/develop

### ISSUE THREAD

**Issue by vivekbhr** [fidelram/deepTools#358]
I believe README.txt can be safely deleted from deeptools/develop (i deleted it in my PR but still see it there).. pip should be able to work with README.rst, which is the updated one converted from README.md..

**Comment by dpryan79** [comment]
You mean pypi rather than pip, yes?

**Comment by vivekbhr** [comment]
@dpryan79 yah..

**Comment by dpryan79** [comment]
Can you make a PR for this or should I do it?

**Comment by vivekbhr** [comment]
yah I can do it.. :+1:
