### ISSUE TITLE
bamCoverage in predefined regions?

### ISSUE THREAD

**Issue by endrebak** [fidelram/deepTools#367]
Thanks for `deeptools`, seems great.

One thing I'd like to do is to make a TSS occupancy graph based on bins that are relative to the TSS (as opposed to bins with an absolute genomic position). 

A simple example of what I mean:

If you have a tss region of 100 bps and a bin size of 50 I'd like the first bin to be the 50 bps in front of the TSS and bin two the 50 bp behind the TSS. So that if the TSS is in position 975, the bins around the TSS are 925-975, 975-1025.

What I think you are doing now is to bin the genome into bins of 50 and then use bin 950-1000 and 1000-1050 when you run `createMatrix`. Am I right?

If you want to implement this, it seems to me you would come a long way just by letting bamCoverage take an argument of predefined regions that it should bin.

**Comment by dpryan79** [comment]
computeMatrix doesn't actually use the bins, rather it uses that values assigned to each position. If you use a binSize of 1 with bamCoverage and appropriate settings for computeMatrix then you can do what you want exactly (I'm doing something like that currently for a project here).
