### ISSUE TITLE
bamCompare --scaleFactorsMethod SES throws exception when using Hsap Ensembl toplevel reference (hg19 & hg38)

### ISSUE THREAD

**Issue by skurscheid** [fidelram/deepTools#368]
Hi,

I am not sure if this is the best point of contact as most issues seem to be raised the development team but I have come across a bug that seems to be related to the reference genome used for the initial alignments.

I am trying to run bamCompare using --scaleFactorsMethod SES with following command:
`bamCompare  --bamfile1 H2AZ-rep3-index1_S1.Q20.sorted.DeDup.bam\
                                                            --bamfile2 Input-rep2-index8_S8.Q20.sorted.DeDup.bam \
                                                            --outFileName Test.SES.bw\
                                                            --outFileFormat bigwig\
                                                            --scaleFactorsMethod SES\
                                                            --ratio log2\
                                                            --skipNonCoveredRegions
`

and encounter following error:

`
*ERROR*: The median coverage computed is zero for sample(s) #[1, 2]
Try selecting a larger sample size or a region with coverage
`

I initially encountered this problem when using reads aligned against the Ensembl toplevel assembly of hg38 (V84) (i.e. non-chromosomal & haplotype-specific sequences included).

Since then I have re-run the alignment against toplevel assembly of hg19 (V75) and the same error occurs.

In contrast, when using only "canonical" chromosomes, bamCompare runs without a problem.

I have attached the stdout.log of one of the failed runs which contains the --verbose output. I have a sneaking suspicion that his might be caused by the number of reference sequences contained in the BAM file, as this is the only difference between the working and error-causing data. I am happy to provide you with some (sub-sampled) BAM files as they trip the same exception.

Cheers,

Sebastian

[stdout.log https://cloudstor.aarnet.edu.au/plus/index.php/s/2t9NJZ5dvkTrseX]

**Comment by skurscheid** [comment]
I can also confirm that bamCompare works with this data when using the Ensembl "primary" assembly of hg38.

**Comment by fidelram** [comment]
In principle the problem occurs because more than 50% of the sampled regions used to estimate the coverage have 0 overlapping reads. Do you know if this may be true for the regions that you want to analyze?

Increasing the number of regions sampled could help (`--numberOfSamples`).

**Comment by skurscheid** [comment]
It works when supplying specific regions.

I only tested increasing --numberOfSamples by a factor of 10 and this resulted in the same error. I get the impression that the inclusion of the different haplotypes in the toplevel reference leads to the sampling routine arriving at the mean = 0 solution. I am now using the "canonical" chromosomes as the regions of interest and this seems to work so far.

Thanks for replying!

**Comment by fidelram** [comment]
Can you run multiBamSummary bins and save the raw counts output? My expectation is that half of the bins will have zero reads.

**Comment by skurscheid** [comment]
Sorry for the delay in getting back.

Yes, you are right, way more than half the bins had zero reads. But this is definitely compounded by the fact that the toplevel reference is 10X the size of the primary reference... Anyway, it is not a bug in deepTools but rather a flaw in my work flow, and it can be fixed by using the primary reference.

Cheers!
