### ISSUE TITLE
Read shifting for ATAC-seq

### ISSUE THREAD

**Issue by rspreafico** [fidelram/deepTools#370]
Hello dev team,

encouraged by Devon Ryan following a post on Google Groups, I am posting this feature request. 

I wonder whether bamCoverage may handle read shifting before computing the pileup signal. This would be handy for ATAC-seq. Typically shifting is performed by converting BAM files to BED files with bedtools (the following example assumes regular BED format, not BEDPE), then invoking awk:

awk 'BEGIN {OFS = "\t"} ; {if ($6 == "+") print $1, $2 + 5, $3 + 5, $4, $5, $6; else print $1, $2 - 4, $3 - 4, $4, $5, $6}' original.bed > shifted.bed

and then converting back from BED to BAM again with bedtools. The shifting is usually 4 or 5 bp: the total for the + and - strands must be 9bp. The total being an odd number, the number of nucleotides to shift should therefore be selectable separately for reads on the + vs - strands. The direction of shifting would come from the sign of the number of nucleotides to shift. 

I find that the literature is not very clear about whether PE reads should be extended for ATAC-seq. IMHO, they should not. 

Another possible feature, related to this, is to allow for on-the-fly read trimming. This is conceptually the opposite of the extendReads parameter. However, if a read is already shorter than the extendReads parameter, it does not get extended. It would be handy to allow for actually trimming mapped reads down to a certain length. One would probably want to map the longest read possible for maximal mapping accuracy, but then he might be interested in only a certain number of nucleotides (e.g. those accessible by the Tn5 enzyme in ATAC-seq) when computing the pileup signal. Unlike shifting as described above, trimming is non-standard for ATAC-seq. However, I guess that on-the-fly trimming might be of interest for a number of different applications.

To conclude, congrats on deepTools! It's a great piece of software that I regularly use in my everyday work. Thanks for all your hard work!

Best,

Roberto

**Comment by dpryan79** [comment]
I've largely implemented this for the next release (2.4). In `bamCoverage` you can use the `--Offset` option to specify a range within each alignment to use. As an example, `--Offset 5 -1` will trim off the first four bases of an alignment (leaving the 5th base through the end). This isn't exactly what was requested, but it's as close as we're likely to ever implement.
