### ISSUE TITLE
Precompiled dependencies cause issues with openldap version on CentOS 6

### ISSUE THREAD

**Issue by lparsons** [fidelram/deepTools#373]
After installing the lastest deeptools, it seems that pyBigWig and/or the installed python was compiled against openldap 2.3, which is old, the current version (for CentOS 6) is 2.4. Thus I get the following error:

        import pyBigWig
    ImportError: libldap-2.3.so.0: cannot open shared object file: No such file or directory

Not sure where the best place to report this is, so I'm making two tickets (feel free to close the one that is less relevant). See https://github.com/galaxyproject/tools-iuc/issues/786.

**Comment by dpryan79** [comment]
I have no idea how pyBigWig got linked to libldap, perhaps python is somehow getting linked against it. I'll close this and follow up on the IUC issue.
