### ISSUE TITLE
bamCoverage: --samFlagInclude does not work

### ISSUE THREAD

**Issue by your-highness** [fidelram/deepTools#378]
I am working with paired end alignment data generated by bowtie2 with minimum insert size 750 and maximum insert size of 3000. I filtered out duplicates.

bamCoverage (version  2.2.3) should generate bigWigs for first reads in proper pairs (SAMFLAG 66):
```
bamCoverage -b noDups.bam -o noDups_raw_f66.bw --samFlagInclude 66
``` 
When checking the bigWigs in IGV I found many suspicious regions, showing alignment artefacts. I checked the bigWig for one of these regions, I get:
```
bigWigSummary noDups_raw_f66.bw chr13 55828597 55828705 1
214.037
```

This value is not even close to what I expect for first read in proper pairs coverage (SAMFLAG 66):
```
samtools view -c -f 66  noDups.bam chr13:55,828,597-55,828,705
2
```

However, the bamCoverage reported value seems to be close to SAMFLAG 64:
```
samtools view -c -f noDups.bam chr13:55,828,597-55,828,705
233
```

Is there a problem with the samflag filter?

**Comment by your-highness** [comment]
A quick follow up:

I rerun bamCoverage with filtering for proper pairs (2) and then excluding seconds in pairs (128):

```
bamCoverage -b noDups.bam -o noDups_raw_f2F128.bw  --samFlagInclude 2 --samFlagExclude 128
```

The results look much better:
```
bigWigSummary noDups_raw_f2F128.bw chr13 55828597 55828705 1
0.981481
```
```
samtools view -c -f 2 -F 128 noDups.bam chr13:55,828,597-55,828,705
2
```

Something seems to be going wrong with the handling of `--samFlagInclude` if it is `66`. For now, the combination of `--samFlagInclude 2` and `--samFlagExclude 128` is a good work around.

**Comment by dpryan79** [comment]
That does seem odd. Could you provide us with the BAM file so we can debug this more efficiently?

**Comment by dpryan79** [comment]
Ah, I see that the test for this is that the alignment must have at least one of the flags specified in `--samFlagInclude` present. So having bit 2 set suffices. We'll have to discuss internally whether it's really a good idea to change that (I'm sure there are unforeseen consequences that aren't currently coming to mind).

**Comment by your-highness** [comment]
Thanks for the fast response, @dpryan79 . You select reads based on "at least one" of the bits being set. This is not clear from the documentation!

IMO, ``--samFlagInclude`` should be handled as a "hard filter" where a read has to suffice all the bits being set. If not, it simply mimics the reverse of ``--samFlagExclude``. I think ``--samFlagExclude`` could work as "soft filter".

**Comment by dpryan79** [comment]
I agree completely. I have a branch that currently implements this. I'll double check with the group and as long as no one objects we'll get this included (and change the documentation to mention this) for the next release, which I'm hoping to release in about 2 weeks.

**Comment by dpryan79** [comment]
I just got around to merging this, so it'll be resolved for the next release.
