### ISSUE TITLE
repository_dependencies for Galaxy wrappers

### ISSUE THREAD

**Issue by martenson** [fidelram/deepTools#380]
There is a data_manager defined as a repo dependency here:
https://github.com/fidelram/deepTools/blob/master/galaxy/wrapper/repository_dependencies.xml

This will cause the installations of all tools to show as `missing repo dependencies' in the admin panel unless the Galaxy has this DM installed. 

E.g. Main has (and will have) no DMs installed. Is this repo dependency necessary?

**Comment by dpryan79** [comment]
We can get rid of that, at least we've never actually used the data manager for our internal or public Galaxy servers.

@bgruening Any objections?

**Comment by bgruening** [comment]
We do have some sort of loc files support and the recommended way currently is to use data-managers.
https://github.com/fidelram/deepTools/blob/eabe7d81b458049a35f27d6467ff09d10472541f/galaxy/wrapper/deepTools_macros.xml#L374

Not sure we should remove this just because main is not using it. If it's broken we should fix it. 
Granted, this feature is not frequently used and we can discuss removing it entirely.

**Comment by dpryan79** [comment]
OK, we can chat on Saturday or something then.

**Comment by bgruening** [comment]
:smiley:

**Comment by martenson** [comment]
afaik only admins can use DMs so the configuration of loc files and whatnot happens asynchronous to the tool usage and is part of the administration of the instance.

This is not a huge hurdle, I was just curios why this is set up in this way.

**Comment by bgruening** [comment]
@martenson this just makes it very easy for an admin to know which data-managers he needs to use if he wants to populate the loc files. I think, this and datatypes are the only reason repository_dependencies exists, isn't it?
But good point let's discuss this at the IUC meeting.

**Comment by dpryan79** [comment]
Was there any consensus regarding this at the IUC meeting?

**Comment by bgruening** [comment]
Unfortunately, we have not discussed it.

**Comment by dpryan79** [comment]
I'll go ahead and close this. Once there's some sort of best-practice consensus we can do whatever that is.
