### ISSUE TITLE
installation question 

### ISSUE THREAD

**Issue by flay** [fidelram/deepTools#382]
Hi,

I installed the latest version of deepTools using pip install deeptools --user
The installation was fine and I didn't have any issue. But when I tried to call for the commands, I am getting an error:

[flay@login4 deepTools]$ bamCoverage
-bash: bamCoverage: command not found

I am using python v.2.7.3 and already have my PATH and PYTHONPATH sourced in bash_profile, so I am not sure why it's not finding the command. I would really appreciate your help with this.
Thank you!

**Comment by dpryan79** [comment]
That's unusual. Is `~/.local/bin` in your PATH?

**Comment by flay** [comment]
Yes it is

**Comment by dpryan79** [comment]
Is `bamCoverage` there and is it executable? My only guess is that somehow the executable bit didn't get set. If it isn't executable, the `chmod a+x` it.

**Comment by flay** [comment]
I uninstalled and reinstalled deepTools using pip and this time I was able to find the executable command. However, when I am trying to run the command, it seems that it's not finding certain modules even though  ~/.local/bin and /.local/lib/python2.7/site-packages are set in my PATH and PYTHONPATH respectively: 

bamCoverage --bam ES.bam --binSize 5 --normalizeTo1x 2150570000 --fragmentLength 200 -o ES.bw --ignoreForNormalization chrX
Traceback (most recent call last):
  File "/u/home/f/flay/.local/bin/bamCoverage", line 4, in <module>
    from deeptools.bamCoverage import main
  File "/u/home/f/flay/.local/lib/python2.7/site-packages/deeptools/bamCoverage.py", line 6, in <module>
    from deeptools import writeBedGraph  # This should be made directly into a bigWig
  File "/u/home/f/flay/.local/lib/python2.7/site-packages/deeptools/writeBedGraph.py", line 4, in <module>
    import numpy as np
  File "/u/home/f/flay/.local/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/u/home/f/flay/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/u/home/f/flay/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 22, in <module>
    from .npyio import *
  File "/u/home/f/flay/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 12, in <module>
    from . import format
  File "/u/home/f/flay/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 154, in <module>
    import io
  File "/u/home/f/flay/.local/lib/python2.7/site-packages/io/__init__.py", line 1, in <module>
    from .fastio_ import loadtxt, savetxt
  File "__init__.pxd", line 155, in init iced.io.fastio_ (iced/io/fastio_.c:4789)
AttributeError: 'module' object has no attribute 'dtype'

**Comment by dpryan79** [comment]
Can you try to `pip uninstall -y numpy && pip install --user numpy`? This seems to be some sort of issue with the numpy package, which will get reinstalled with the command I posted.

**Comment by flay** [comment]
When I tried that command, I got this error: 

pip uninstall -y numpy && pip install --user numpy
Traceback (most recent call last):
  File "/u/local/apps/python/2.7.3/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 22, in <module>
    from sets import ImmutableSet as frozenset
  File "/u/local/apps/python/2.7.3/lib/python2.7/zipfile.py", line 464, in <module>
    class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'

This is very strange because I didn't have any issue with numpy prior to installing deeptools since I used numpy for other tools as well -- it seems like pip install deeptools --user somehow screwed up my previous numpy version and I now cannot seem to uninstall or reinstall this numpy. 

Really appreciate your help with this!

**Comment by fidelram** [comment]
Hi,

Can you try installing deeptools using anaconda? (see
https://github.com/fidelram/deepTools)

This is the best way to solve your issues regarding numpy.

-fidel


On Tue, Jun 28, 2016 at 6:47 AM, flay <notifications@github.com> wrote:

> When I tried that command, I got this error:
>
> pip uninstall -y numpy && pip install --user numpy
> Traceback (most recent call last):
> File "/u/local/apps/python/2.7.3/bin/pip", line 5, in
> from pkg_resources import load_entry_point
> File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 22, in
> from sets import ImmutableSet as frozenset
> File "/u/local/apps/python/2.7.3/lib/python2.7/zipfile.py", line 464, in
> class ZipExtFile(io.BufferedIOBase):
> AttributeError: 'module' object has no attribute 'BufferedIOBase'
>
> This is very strange because I didn't have any issue with numpy prior to
> installing deeptools since I used numpy for other tools as well -- it seems
> like pip install deeptools --user somehow screwed up my previous numpy
> version and I now cannot seem to uninstall or reinstall this numpy.
>
> Really appreciate your help with this!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fidelram/deepTools/issues/382#issuecomment-228947304>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEu_1YuIkbS7EizwQSBKj9OqjOvmABptks5qQKd-gaJpZM4I-bTd>
> .
>



-- 

Fidel Ramirez

**Comment by dpryan79** [comment]
@flay: Go ahead and reopen this if you're still having issues.
