### ISSUE TITLE
multiBigwigSummary runs slowly due to unevenly distributing work among processes

### ISSUE THREAD

**Issue by kernco** [fidelram/deepTools#385]
I'm running multiBigwigSummary with data from chicken. The chicken genome has ~20,000 small unplaced scaffolds in addition to the main chromosomes (most of the non-model organism genomes are like this). When running multiBigwigSummary with multiple cores, I noticed in "top" that I would see many multiBigwigSummary processes listed for a few minutes, but then it would go down to only a single process and continue to run for a long time before finishing.

I edited getScorePerBigWigBin.py and added "print chrom, start, end" at line 59 to see if there was a specific genomic region that was slow for some reason. It looks like what is happening is that the TASKS list in mapReduce.py, which is divided among the processes, is treating the small unplaced scaffolds as an equal unit of work compared to a chunk of one of the large chromosomes, and because of the ordering of TASKS, most of the processes are getting a bunch of the small unplaced scaffolds to work on, which they finish very quickly, while one of the processes is given the main chromosome chunks which are the vast majority of the work.

I "fixed" this in a pretty silly way, which is to add random.shuffle(TASKS) as line 150 in mapReduce.py. I haven't tested how it affects any other deepTools functions, and there's probably a better way to solve this, but it does seem to spread the large chromosome chunks around to the various processes so it divides the work more evenly and completes much faster.

**Comment by dpryan79** [comment]
This sounds like a decent solution , can you make a pull request?

**Comment by kernco** [comment]
Which branch should I fork? Develop?

**Comment by fidelram** [comment]
yes, use develop.

On Tue, Jun 28, 2016 at 6:11 PM, Colin kern <notifications@github.com>
wrote:

> Which branch should I fork? Develop?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fidelram/deepTools/issues/385#issuecomment-229098984>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEu_1aFa4ndX0aiLCFmDdlS5yCWitUIYks5qQUeWgaJpZM4I_lo0>
> .
>



-- 

Fidel Ramirez

**Comment by dpryan79** [comment]
@kernco: I merged your PR, thanks!
