### ISSUE TITLE
Support remote files in deepBlue

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#387]
It'd be quite useful to support remote files in [deepBlue](http://deepblue.mpi-inf.mpg.de/).

Tools that should support this are:

 * [x] bigwigCompare
 * [x] computeMatrix
 * [x] multiBigwigSummary

These should optionally accept some sort of API key.

The following additionally need to be done:

 * [x] Figure out how to deal with partially overlapping intervals
 * [x] Ensure correctness of results
   * [x] bigwigCompare
   * [x] computeMatrix
   * [x] multiBigwigSummary
 * [x] Write a short example in the documentation
 * [x] Request a userKey that's needed for one sample and test that with everything, since I expect `--userKey` isn't being handled everywhere.

**Comment by bgruening** [comment]
+1

**Comment by fidelram** [comment]
Agree 

Fidel Ramírez

**Comment by dpryan79** [comment]
As an initial step, I've made [a jupyter notebook](https://github.com/dpryan79/jupyter_notebooks/blob/master/deepBlue%20connection%20and%20query%20demonstration.ipynb) with a class that demonstrates how to connect to and query values from deepBlue.

**Comment by dpryan79** [comment]
`bigwigCompare` now handles files on deepBlue. One issue is that I haven't yet figured out how to get deepBlue to play nicely with region requests. Currently, the server returns only all intervals contained completely within the requested region, so anything only partially overlapping is lost. That's a problem for how multithreading is handled (I would argue that it's generally problematic). I've contacted the deepBlue folks to ask about how to deal with this.

**Comment by steffenheyne** [comment]
so you mean for example intervals that are not concordant with the bin size of wiggle file are lost?

**Comment by dpryan79** [comment]
No, if you have the following:

    chr1 0  10 1.0
    chr1 10 12 1.1
    chr1 12 22 0.0

and ask for everything in the region chr1:5-15 then you'll only get the middle interval. This is problematic since intervals aren't fixed width, so expanding the size by some amount isn't guaranteed to work.

**Comment by dpryan79** [comment]
With a little help form the deepBlue folks, the partially overlapping intervals issue is now taken care of.

**Comment by dpryan79** [comment]
One note with `multiBigwigSummary` is that the bin size should be adjusted up to 100000 or 1 million for the sake of speed. The server has too much overhead to efficiently handle so many smaller queries. This goes for `computeMatrix` too, though there it's more a matter of the transcript sizes.

**Comment by dpryan79** [comment]
This is now all working in `develop`.
