### ISSUE TITLE
extract reads assigned to specific features using plotEnrichment

### ISSUE THREAD

**Issue by giusem** [fidelram/deepTools#389]
In my opinion, a neat addition to plotEnrichment would be the possibility to save the reads that are assigned to each feature in plotEnrichment

**Comment by dpryan79** [comment]
That's what `bedtools` is for :)

**Comment by fidelram** [comment]
I suppose that you can do the filtering using bedtools intersect but in the case of several features would not be more convenient to let plotEnrichment save multiple sam files?

**Comment by dpryan79** [comment]
Sure, but I'm trying to not reinvent the wheel unless absolutely required. If someone else wants to code that up that's fine, but I won't.

**Comment by dpryan79** [comment]
Because it's how I roll, here's code that will probably do what you want. You'd want to add in argparse or something.

    #!/usr/bin/env python
    import pysam
    from deeptoolsintervals import Enrichment

    bam = pysam.AlignmentFile("something.bam")
    gtf = Enrichment(["blah.gtf"])

    # Make a dict() of output files
    fps = dict()
    for t in gtf.features:
        fps[t] = pysam.AlignmentFile("{}.bam".format(t), "wb", template=bam)

    for read in bam.fetch():
        features = gtf.findOverlaps(read.get_reference_name(), read.get_blocks())
        if features is not None:
            for feature in features:
                fps[feature].write(read)

    bam.close()
    for k, v in fps.items():
        v.close()

You'll need deepTools installed for this to work, since `deeptoolsintervals` is part of the API.
