### ISSUE TITLE
Minor typo inn the docs

### ISSUE THREAD

**Issue by adomingues** [fidelram/deepTools#399]
[Here](http://deeptools.readthedocs.io/en/latest/content/tools/plotHeatmap.html), first example:

```
plotHeatap -m matrix.mat.gz \
      -out ExampleHeatmap1.png \
```

should be:

```
plotHeatmap -m matrix.mat.gz \
      -out ExampleHeatmap1.png \
```

Not the misspelling of "heatmap" in the command call.

Yes, I know it is a very minor issue :) Sorry for being pedantic. Is there a better way to report these things, or here is perfectly fine?

**Comment by dpryan79** [comment]
Thanks for pointing that out, that should be fixed shortly. BTW, this is a perfectly fine place to report stuff like that :)
