### ISSUE TITLE
bamCoverage: Controlling maxPairedFragmentLength:

### ISSUE THREAD

**Issue by your-highness** [fidelram/deepTools#410]
Hello,

I would like to use bamCoverage (version  2.3.3-1-c9c30ee) on STARR-seq data. Therein, Paired End fragment have a length distribution from 0.5 to 3kb. I tried
`bamCoverage -b in.bam -o out.bw --minMappingQuality 30 --samFlagInclude 2 -bs 10 --normalizeUsingRPKM --minFragmentLength 500 --maxFragmentLength 3000`
stdout:
```bash
Due to filtering, 0.62514864268% of the aforementioned alignments will be used 742.43903102
normalization: RPKM
minFragmentLength: 750
verbose: False
out_file_for_raw_data: None
numberOfSamples: None
bedFile: None
bamFilesList: ['in.bam']
ignoreDuplicates: False
numberOfProcessors: 24
samFlag_exclude: None
save_data: False
stepSize: 10
smoothLength: None
center_read: False
defaultFragmentLength: read length
chrsToSkip: []
region: None
maxPairedFragmentLength: 1000
samFlag_include: 2
binLength: 10
blackListFileName: None
maxFragmentLength: 3000
minMappingQuality: 30
zerosToNans: False
```
The result is not what I want. it seems `maxPairedFragmentLength: 1000` is the problem. I can not control parameter specifically. 

After checking the code, I found that I can influence this parameter by `-e`.
`bamCoverage -b in.bam -o out.bw --minMappingQuality 30 --samFlagInclude 2 -bs 10 --normalizeUsingRPKM --minFragmentLength 500 --maxFragmentLength 3000 -e 750` gives the correct result.

How can I control maxPairedFragmentLength? Only via `-e`?

**Comment by dpryan79** [comment]
The `maxPairedFragmentLength` setting should be ignored if reads aren't being extended. I presume you really wanted reads extended anyway, in which case you might also try `-e` by itself (though if the median fragment size is below 750 then you'll lose the larger fragments).

**Comment by dpryan79** [comment]
@fidelram: What are your thoughts on getting rid of the `maxPairedFragmentLength` check in "proper-pairs" check function? I'm of two minds regarding even checking for proper pairs in a hard-coded way, though I fear changing that might catch some people by surprise. Thoughts?

**Comment by your-highness** [comment]
I don't know if my use case is a very specific case but it would be nice that when "--maxFragmentLength" is set, the initial "maxPairedFragmentLength" is set to this value.

**Comment by fidelram** [comment]
`maxPairedFragmentLength` is handy when working with extended pairs. If not set, non concordant pairs get wrongly extended. An extreme example would be a pair whose first mate maps to the start of the chromosome and the other mate to the end. Without the check, the whole genome would be covered.

What we need to do is to offer a print out only of the parameters used. The current list that is printed was supposed to be a debug line but I have noticed that is quite handy to check default parameters for the users.

**Comment by dpryan79** [comment]
Fair enough. Anyway, I'm setting `--maxFragmentLength` to set `maxPairedFragmentLength` if specified for the 2.4 release.
