### ISSUE TITLE
bamCompare with options 

### ISSUE THREAD

**Issue by ale07alvarez** [fidelram/deepTools#412]
am trying to use bamCompare following one of the example usage given: 
https://github.com/fidelram/deepTools/wiki/Normalizations
and have not succeeded in making it work when using the options  --binSize 25 --scaleFactorsMethod SES --sampleLength 1000 --numberOfSamples 100000.

NOTE: Then analysis works without the options

usage (on single end data):
~/anaconda2/bin/bamCompare -b1 combined-RORAB3-N1_sorted.bam -b2 combined-C-INPUTB-N1_sorted.bam --binSize 25 --scaleFactorsMethod SES --sampleLength 1000 --numberOfSamples 100000 -o log2ratio_ChIPb3_vs_Inputb.bw
Error: 
Traceback (most recent call last):
  File "/home/alerodri/anaconda2/bin/bamCompare", line 7, in <module>
    main()
  File "/home/alerodri/anaconda2/lib/python2.7/site-packages/deeptools/bamCompare.py", line 309, in main
    scale_factors = get_scale_factors(args)
  File "/home/alerodri/anaconda2/lib/python2.7/site-packages/deeptools/bamCompare.py", line 199, in get_scale_factors
    mapped_reads = [bam1.mapped, bam2.mapped]
UnboundLocalError: local variable 'bam1' referenced before assignment

**Comment by dpryan79** [comment]
What version are you using? This should have been fixed in version 2.3.4.

**Comment by ale07alvarez** [comment]
bamCompare 2.3.3, I thought I had the latest version of deep tools,
how can I update individual modules?

**Comment by ale07alvarez** [comment]
I installed deeptools using:
conda install -c bioconda deeptools

**Comment by dpryan79** [comment]
You can `conda update deeptools`.

**Comment by ale07alvarez** [comment]
not sure why is not updating : packages already installed
$ conda update deeptools
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......
# All requested packages already installed.
# packages in environment at /home/aa/anaconda2:
#
deeptools                 2.3.3                    py27_0    bioconda
[alerodri@juno bin]$ pwd
/home/aa/anaconda2/bin

**Comment by dpryan79** [comment]
Try instead `conda update -c bioconda deeptools`.

**Comment by ale07alvarez** [comment]
update worked thanks!!!
