### ISSUE TITLE
Update docs to mention python3 support.

### ISSUE THREAD

**Issue by j-andrews7** [fidelram/deepTools#419]
Hi all,

Minor thing, but the [Read the Docs installation](http://deeptools.readthedocs.io/en/latest/content/installation.html) page doesn't mention python3 support, though the PyPI page does. Adding that info to the docs might save those of us who utilize python3 from setting up a python2 environment just to run this (as it is a great suite!).

Thanks.

**Comment by j-andrews7** [comment]
Went ahead and submitted a pull request for this - #420. Not sure what version of python3 are actually supported, so I just threw in 3.x.

**Comment by dpryan79** [comment]
Good catch! I'll have a look at this and get it merged on Monday. Regarding the supported versions, we test 3.5 on Travis and 3.4 on our internal servers, though I presume 3.3 at least works too (no clue about 3.2, I assume no one's using it any more).

**Comment by dpryan79** [comment]
I merged your PR, thanks for the help!
