### ISSUE TITLE
Problem installing deeptools in virtual environment: ImportError: No module named sysconfig

### ISSUE THREAD

**Issue by chriad** [fidelram/deepTools#421]
I use` pip install deeptools` in a virtual environment and get the following error:
```

Downloading/unpacking pysam>=0.8.2 (from deeptools)
  Downloading pysam-0.9.1.4.tar.gz (2.2MB): 2.2MB downloaded
  Running setup.py egg_info for package pysam
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/work2/ggasser/muelchri/master_thesis/source/pyvenv/venv/build/pysam/setup.py", 
line 32, in <module>
        import sysconfig
    ImportError: No module named sysconfig
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/work2/ggasser/muelchri/master_thesis/source/pyvenv/venv/build/pysam/setup.py", line
 32, in <module>

    import sysconfig

ImportError: No module named sysconfig
```
python --version : Python 2.6.6

The issue that I encountered is with `bamCompare`:

H3K4me2_8002_ChIP_Rep2.bw.bg is not case-sensitive sorted at line 1902983.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.

I tried just to update according to the advice given here https://groups.google.com/forum/#!topic/deeptools/2yxgUrlziN8 , but than ran into the above isssue.

**Comment by dpryan79** [comment]
We don't support versions of python that old, you'll need to use at least version 2.7.

**Comment by chriad** [comment]
Thanks!
