### ISSUE TITLE
github version 2.3.4 different from to PyPi version 2.3.4?

### ISSUE THREAD

**Issue by Carambakaracho** [fidelram/deepTools#424]
Hi there,

This is a really minor but quite confusing error:

I installed this morning release 2.3.4 from the github tarball and `deeptools --version` and `bamCoverage --version` reported 2.3.2

Then I realized you provide a pip pakage and installed it via pip directly, now  `deeptools --version` prints the whole help screen, but   `bamCoverage --version` reports 2.3.4

Did the 2.3.2 version end up in the tarball by accident or does the 2.3.4 version report the wrong version number?

Cheers,
Steffen

**Comment by dpryan79** [comment]
I don't know why the version from github reports 2.3.2, it's likely that the tag was misplaced and then fixed without github updating the source tarball. Anyway, it should be correct on pypi. I should note that I'm in the process of pushing out 2.3.5 (I hope to have it available within the next hour).

**Comment by Carambakaracho** [comment]
Awesome, I'm currently testing the my usecase anyway, so I'll just upgrade after you published 2.3.5.
Thanks

**Comment by dpryan79** [comment]
2.3.5 should now be available on pypi (and soon via conda and Galaxy).

**Comment by dpryan79** [comment]
I double checked that the --version option in the tarball that I put on pypi is correct :)
