### ISSUE TITLE
computeMatrix default sorting parameter (==no) changes order of output file

### ISSUE THREAD

**Issue by karl616** [fidelram/deepTools#425]
Hi, 

running computeMatrix (reference-point) without the sortRegions flag should default to no sorting of the file. Still, the order of the regions in the output file are disturbed. A small example attached at the end. The names in the input file was numerically sorted from G1_1 to G1_1211. This is not the behaviour I expected. Did I misunderstand?

Best,
Karl

computeMatrix reference-point \
    --regionsFileName G1.bed \
    --scoreFileName input.bw \
    --outFileName G1.out.gz \
    --outFileNameMatrix G1.matrix.csv \
    --referencePoint TSS \
    --beforeRegionStartLength 1000 \
    --afterRegionStartLength 1000 \
    --numberOfProcessors 8

zcat G1.out.gz | cut -f 1-6 | head
@{"verbose":true,"scale":1,"skip zeros":false,"nan after end":false,"sort using":"mean","unscaled 5 prime":0,"body":0,"sample_labels":["input"],"downstream":1000,"unscaled 3 prime":0,"group_labels":["genes"],"bin size":10,"upstream":1000,"group_boundaries":[0,1210],"sample_boundaries":[0,200],"missing data as zero":false,"ref point":"TSS","min threshold":null,"sort regions":"no","proc number":8,"bin avg type":"mean","max threshold":null}
20      48782639        48782899        G1_492  3.0     +
1       33546597        33546705        G1_173  2.0     +
16      81069364        81069452        G1_390  3.0     +
16      74330660        74330673        G1_691  4.0     +
5       7373187 7373230 G1_563  3.0     +
1       43824329        43824626        G1_1116 9.0     +
1       43855479        43855553        G1_1022 8.0     +
11      66234209        66234216        G1_186  2.0     +
12      56211540        56211703        G1_878  6.0     +

**Comment by vivekbhr** [comment]
That's right, from version 2.3 onward the order you see is the order stored in the interval tree, so it's not sorted, but still ordered in some way.

If you want the order to be the same as you entered, you can use version 2.2.x .. We have to sort this thing out or clarify in the documentation.

**Comment by karl616** [comment]
Thank you,

I work around it for now, but it would be nice to have it sorted out.

**Comment by vivekbhr** [comment]
Great.. I opened #426 to see what we can do about it..
