### ISSUE TITLE
sorting/ordering regions for computeMatrix 

### ISSUE THREAD

**Issue by vivekbhr** [fidelram/deepTools#426]
From version 2.3 onward the regions are always returned as per the interval tree, so `sorting=NO` returns a confusing output.

@dpryan79 mentioned earlier that fixing the sort order is difficult in the interval tree. Shall we find a workaround? If not we should clarify in the documentation that people need to use earlier version to avoid ordering of the output.

**Comment by dpryan79** [comment]
2.4 has a [computeMatrixOperations](http://deeptools.readthedocs.io/en/develop/content/tools/computeMatrixOperations.html) command on the CLI and in Galaxy that can do this for those that really want the orders to match. For 2.3, `scripts/subsetMatrix` is a stripped-down form of that with less testing.

**Comment by dpryan79** [comment]
I've added a bit to the computeMatrix documentation for the 2.4 release.
