### ISSUE TITLE
computeMatrix/plotHeatmap --outFileNameMatrix output

### ISSUE THREAD

**Issue by vivekbhr** [fidelram/deepTools#427]
The `--outFileNameMatrix` output in computeMatrix and plotHeatmap outputs the bins across all samples separated by space, which is inconvenient for parsing the output. We should output a file with samples separated by TAB and bins separated by SPACE.

**Comment by dpryan79** [comment]
Could we just separate everything by tabs? That'd be simpler to implement. I'm also personally open to changing the structure of the header to make it easier to determine sample bounds.

**Comment by vivekbhr** [comment]
But then there will be the same problem as with space. we won't know which bins belong to which sample.

**Comment by vivekbhr** [comment]
or I think we can separate everything by tab and then add a header line with sample:bin.. So this will say `sample_X:bin1 <tab> sample_X:bin2 <tab>  sample_Y:bin1` and so on

**Comment by dpryan79** [comment]
I'd be in favor of the latter one, purely because its a really quick change :) At the moment, it's `sample_X:widthX <tab> sample_Y:widthY <tab>`, so it'd just be a matter of not converting from sample bounds to width.

**Comment by dpryan79** [comment]
@vivekbhr: Let me know if my changes worked :)

**Comment by dpryan79** [comment]
I've finished changing this. The final implementation adds a 3rd header columns (that doesn't start with a `#`) with sample names as column headers. Further, everything is now tab separated. I've tested this to ensure it now works.
