### ISSUE TITLE
Order of BAM/bigWig files in Galaxy wrappers

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#428]
See [here](https://biostar.usegalaxy.org/p/19839/) for context. In short, it might be nice to let the folks using Galaxy to choose the order of BAM/bigWig files in multi*Summary and computeMatrix, instead of the order being determined by how things are arranged in the history. For computeMatrix, this will end up being possible *post-hoc* with `computeMatrixOperations` once 2.4 is released, but it still might be nice to implement this directly. The implementation would mimic the region selection in computeMatrix.

@bgruening: Thoughts? The implementation should be easy enough, but I don't know if there's something that I'm missing (e.g., can a minimum of 2 input files still be used for things like multiBamSummary?).

**Comment by bgruening** [comment]
The only problem I'm seeing is that a repeat element in the user-interface is tedious for large files. It was a repeat in the 1.x time afaik and we changed it to a multi-select to not select 20 files step by step. So this option should be optional and non-default?

**Comment by dpryan79** [comment]
Good point. Maybe we need a conditional "Do you REALLY care about the order of the files?" conditional.

**Comment by bgruening** [comment]
Something like this, yes ;)

**Comment by dpryan79** [comment]
:) Cool, I'll put this together after the holiday then.

**Comment by bgruening** [comment]
Enjoy your vacation!

**Comment by dpryan79** [comment]
You too!

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch.
