### ISSUE TITLE
Deep Tools correctGCBias unrecognized arg --filterOut produces an error

### ISSUE THREAD

**Issue by jennaj** [fidelram/deepTools#434]
**Version** 

toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_compute_gc_bias/deeptools_compute_gc_bias/2.2.3.0

**Error**

> job stderr:
> Fatal error: Exit code 2 ()
> usage:
>  computeGCBias -b file.bam --effectiveGenomeSize 2150570000 -g mm9.2bit -l 200 --GCbiasFrequenciesFile freq.txt [options]
> computeGCBias: error: unrecognized arguments: --filterOut /galaxy-repl/main/files/XXX/XXX/dataset_XX.dat

**Tool form display of option**

<img width="722" alt="screen shot 2016-06-22 at 12 56 39 pm" src="https://cloud.githubusercontent.com/assets/8999735/16281502/944fbe32-3879-11e6-8537-574c8566e843.png">

Moved from https://github.com/galaxyproject/tools-iuc/issues/835. Retested 2016-09-07

**Comment by dpryan79** [comment]
I guess the wrapper was never updated. `--filterOut` should be `--blacklistFileName`.

**Comment by dpryan79** [comment]
I see that Björn fixed this is June but didn't push out a wrapper update. You can just swap `--filterOut` with `--blacklistFileName` in the wrapper and it should work. This is correct in the most recent version, though that tool is painfully slow in it (that's been fixed for the next release, due Nov. 1).

**Comment by bgruening** [comment]
@dpryan79 I thought I updated deeptools in September :(
https://toolshed.g2.bx.psu.edu/view/bgruening/suite_deeptools/7f5562625ae2

@jennaj can you check if you have the latest version?

**Comment by dpryan79** [comment]
@bgruening You did, but this is an old version, since the two GCBias tools are really really slow in 2.3 (we didn't realize that until well after the release), so we've been suggesting 2.2 to people. I wrote a new 2bit access module that's python3 compliant and much much much faster (being mostly C and all).

**Comment by jennaj** [comment]
@bgruening @dpryan79 Deep Tools on http://usegalaxy.org is at v Galaxy Version 2.3.5.0. Guess we'll need that update once ready in the Tool Shed.

@nate Is there an "@" ping for the Main bug squad? Be convenient to ping them all at once - unless you have a better idea. They can sort out who will take which task (like this one - tracking fix then updating Test, testing, then updatng Main, autotest). Once I see that noted here, I can also test as backup using more complex tests (larger, real data) than the automated tests and we can close out for the Main server.

**Comment by jennaj** [comment]
Version 2.3.6 is in the MTS as of the 25th. Guess we can update http://usegalaxy.org now?

ping @galaxyproject/guac
