### ISSUE TITLE
multiBamSummary doesn't always produce output

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#436]
This has got to be the weirdest bug I have ever seen. For some reason, `multiBamSummary` sometimes doesn't produce output, but this appears (at the moment) to be dependent on the length of the full path to the output file name. That is, if you use `--outFileName foo.npz` you'll get output, but `--outFileName /some/really/long/path/foo.dat` you won't. This seems to be happening on both Galaxy main and our deepTools Galaxy instance with version 2.3.5. At the moment I have absolutely no idea why this is happening.

ping @jennaj

**Comment by bgruening** [comment]
@dpryan79 are you using an NFS share in your long path?

**Comment by dpryan79** [comment]
Found it, apparently the version of numpy being used by version 2.3.5 in Galaxy has the odd behavior that the `savez_compressed()` function will often append ".npz" to the file name.

**Comment by dpryan79** [comment]
Correction, it will always append that, which makes me wonder how the Travis Galaxy tests have been passing!

**Comment by dpryan79** [comment]
Ah, the fix is easy, you just pass in a file pointer (of whatever the heck python calls its equivalent), as is done in multiBigwigSummary.

**Comment by jennaj** [comment]
Version 2.3.6 is in the MTS as of the 25th. Guess we can update http://usegalaxy.org now?

ping @galaxyproject/guac
