### ISSUE TITLE
The file xyz does not have BAM format

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#437]
Hi,

I am running the latest release of deeptools (installed from pip) and this command gives me the following warning/error:

```
# multiBamSummary bins --numberOfProcessors 2 --bamfiles  /home/dnanexus/CEG45-135-5_S5_L00.sorted.standard.bam /home/dnanexus/CEG45-135-6_S6_L00.sorted.standard.bam /home/dnanexus/CEG50-5-4_S1_L00.sorted.standard.bam /home/dnanexus/CEG50-5-5_S2_L00.sorted.standard.bam /home/dnanexus/CEG50-5-6_S3_L00.sorted.standard.bam /home/dnanexus/CEG50-5-7_S4_L00.sorted.standard.bam --binSize 1000 -o /home/dnanexus//bamCorrelate.multibamsummary.npz
The file /home/dnanexus/CEG45-135-5_S5_L00.sorted.standard.bam does not have BAM format 
The file /home/dnanexus/CEG45-135-5_S5_L00.sorted.standard.bam does not have BAM format 
```
Any ideas what is the software looking for in the bam file to call it BAM format or not?
How should I assess what's going on with my bam files?

**Comment by dpryan79** [comment]
Do you have read permissions? The code (in python is just):

    pysam.Samfile(bamFile, 'rb')

The error message you're seeing is what happens if there's an error other than "file doesn't exist".

**Comment by avilella** [comment]
I can't imagine there are any permissions issues, this is in an instance of
Dnanexus where the same user acc downloads the data and then runs
deeptools...

Looking at it, it doesn't seem to stop with an error, just prints the 'not
a BAM format' prompt, but continues using compute:

```
CPU: 24% (2 cores) * Memory: 702/3764MB * Storage: 25GB free * Net:
0↓/0↑MBps
Oct 20, 2016 1:08 PM
```

Is this 24% CPU usage meaning it is still doing something useful?

Would any extra flags help here? `--verbose` or any other flags?


On Thu, Oct 20, 2016 at 1:10 PM, Devon Ryan <notifications@github.com>
wrote:
>
> Do you have read permissions? The code (in python is just):
>
> pysam.Samfile(bamFile, 'rb')
>
> The error message you're seeing is what happens if there's an error other
than "file doesn't exist".

**Comment by dpryan79** [comment]
I would presume that it's doing something then. Each core is doing this (meaning that you should have gotten it at least once per core), so perhaps there was a transient file system error?

**Comment by avilella** [comment]
It seems to be something specific in the Dnanexus environment since I am having no problems running the same code locally. I'll do some more chasing...

Closing ticket ATM

**Comment by dpryan79** [comment]
OK, let me know if you track it down and there's something we can do to prevent this.
