### ISSUE TITLE
bamCoverage bedGraph files should be sorted

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#439]
See #438 for the original report. Apparently the bedGraph file is only getting sorted when we make bigWig files (I don't think I've ever checked this).

**Comment by dpryan79** [comment]
This is now fixed for the next release.

**Comment by malcook** [comment]
can you comment on the nature of the sort?  Specifically, is chr10 less than chr2?  In my hands it seems it is not, and arguable it should be.  Thoughts?
