### ISSUE TITLE
bamCoverage outputs empty bedgraph file

### ISSUE THREAD

**Issue by daquang** [fidelram/deepTools#440]
My BAM file is 17GB. When I run bamCoverage on it with the following options, bamCoverage only outputs an empty bedgraph file:

--normalizeTo1x 2478297382 --numberOfProcessors 12 --ignoreForNormalization chrX chrM --Offset 1 --binSize 1 --blackListFileName blacklist.bed.gz --skipNonCoveredRegions

It seems to work fine for smaller BAMs.

**Comment by dpryan79** [comment]
My guess is that this is related to #438, since --Offset 1 with 1x normalization could yield a lot of values <0.1. Can you either try the develop branch or post the problematic BAM file somewhere?

**Comment by daquang** [comment]
Thanks for looking into it. You can find the bam and blacklist bed file here:

https://hpc.oit.uci.edu/~dxquang/

As you can probably tell from what I'm trying to do, I'm trying to get a normalized DNase I 5' cut coverage at single base resolution.

**Comment by dpryan79** [comment]
Thanks, I'm downloading that now and will have a look.

**Comment by dpryan79** [comment]
I've tried this on what will become the 2.4.0 release and at least there it produces reasonably sized output. I can reproduce this with version 2.3.6, so I guess we've fixed it in the interim :)

**Comment by dpryan79** [comment]
BTW, the 2.4.0 release should be out on Wednesday, though you can get it via the "develop" branch now if you need it right away.

**Comment by daquang** [comment]
Thank you so much for the fast response! Seems to be working well so far :)
