### ISSUE TITLE
1x Coverage Normalisation

### ISSUE THREAD

**Issue by annaquaglieri16** [fidelram/deepTools#442]
Hi Devon, 

I would like to better understand how the 1x Normalisation works. As I understood, if I have a PE library deepTools computes the average depth as: (Number of Reads (or fragments??) * fragment length)/ (effective Gen size). By default it takes the mean fragment size. Is this correct?

if I have a SE library it computes the average depth as: (Number of Reads  * read length (or it estimates a fragment length??))/ (effective Gen size). Is this correct?

Then the scaling factor will be 1/depth and it uses this factor to scale the coverage in each bin. Is this right? Is there a way to output the scaling factor used since I did not see it in the log output.

Thanks for your help and your time, 

Best wishes,
Anna

**Comment by dpryan79** [comment]
PE and SE datasets are essentially handled the same, the only difference being how the `-e` option is used. If `-e` is not specified, then the fragment length is set to the median read length for both SE and PE experiments. The rest is exactly what you outlined (i.e., the expected coverage is estimated as `#reads` * `fragment length` / `effective genome size`. If the `-e` option is used, then median PE fragment size is used or whatever value you give to `-e` for SE experiments.

You can have deepTools output the scaling factor with the `-v` option.

**Comment by annaquaglieri16** [comment]
Dear Dacon, 
thanks a lot, 
In your previous email you wrote: "the fragment length is set to the median READ LENGTH for both SE and PE."
The read length is always the same, did you mean fragment length? 

Thanks again!

Anna

**Comment by dpryan79** [comment]
Nope, I meant the read length, which is only the same if you didn't trim your reads.

**Comment by annaquaglieri16** [comment]
Got it!
Thanks a lot
