### ISSUE TITLE
Customising plots with matplotlibrc configuration file

### ISSUE THREAD

**Issue by mxenoph** [fidelram/deepTools#444]
Hello,

I would like to control the font type and size used in plotHeatmap (deeptools 1.6.0-640-gbe54288). Is it possible to control `rc` parameters with a `matplotlibrc` configuration file? 

I am not a confident python programmer but if I understand the code correctly `FontProperties()` gathers the font specifications (https://github.com/fidelram/deepTools/blob/master/deeptools/plotHeatmap.py#L210) and those are used for plotting. Is there a reason 'font.size' is hard-coded in the script with `matplotlib.rcParams` and overwriting `~/.config/matplotlib/matplotlibrc`? I'm thinking of editing the source code and recompiling to allow using the parameters defined in matplotlibrc.

**Comment by fidelram** [comment]
I recommend you to modify the code and remove the hard coded font size for your purpose. We need to think of a way to set a nice font size. The same applies for plotCorrelation.
