### ISSUE TITLE
bamCoverage with filtering sets unneeded scaling factor

### ISSUE THREAD

**Issue by fidelram** [fidelram/deepTools#445]
bamCoverage without normalization should return integer values. However, when filtering is applied (e.g. ignore duplicates) a scaling factor is computed and applied.

Instead, if no normalization is required, the adjustment of the scaling factors due to filtering should be skipped.

**Comment by dpryan79** [comment]
The scaling factor should just be 1 in those cases, so are you actually seeing a difference? Is this having a considerable performance impact?

**Comment by fidelram** [comment]
PR #446 solves the problem
