### ISSUE TITLE
bamCoverage and multireads

### ISSUE THREAD

**Issue by brianpenghe** [fidelram/deepTools#448]
Can I ask how bamCoverage deals with multireads? Does it divide the read counts by the NH tag number or just looks at the unique reads? Could you add some features to enable different ways of multireads handling?

Thanks

**Comment by dpryan79** [comment]
bamCoverage counts all alignments as 1 or not at all. In most cases it's best to simply exclude secondary alignments, which has approximately the same effect in the end. Without a very compelling use-case, I'd prefer to avoid adding any extra options to the existing tools.

**Comment by brianpenghe** [comment]
OK I see. 

Thank you!
