### ISSUE TITLE
py2bit dependency

### ISSUE THREAD

**Issue by eranroz** [fidelram/deepTools#449]
When installing deepTools with python 3.5 I see the following error:

> 
> Searching for py2bit>=0.2.0
> Reading https://pypi.python.org/simple/py2bit/
> Downloading https://pypi.python.org/packages/f4/98/5fc4799e9b6717a80aa31efd09bb6ce8fbca87fae8985ca202129639ff24/py2bit-0.2.0.tar.gz#md5=c441eea85270dda8f502b389b6235518
> Best match: py2bit 0.2.0
> Processing py2bit-0.2.0.tar.gz
> Writing /tmp/easy_install-0_f14xfi/py2bit-0.2.0/setup.cfg
> Running py2bit-0.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0_f14xfi/py2bit-0.2.0/egg-dist-tmp-hkoejrrm
> /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'classifier'
>   warnings.warn(msg)
> zip_safe flag not set; analyzing archive contents...
> py2bitTest.__pycache__.test.cpython-35: module references __file__
> __pycache__.py2bit.cpython-35: module references __file__
> No eggs found in /tmp/easy_install-0_f14xfi/py2bit-0.2.0/egg-dist-tmp-hkoejrrm (setup script problem?)
> error: The 'py2bit>=0.2.0' distribution was not found and is required by deepTools

I work around it by installing it directly from source.

See upstream issue:
https://github.com/dpryan79/py2bit/issues/3

**Comment by dpryan79** [comment]
I assume that this has been solved by your pip upgrade, yes?

**Comment by eranroz** [comment]
Thanks @dpryan79 . Solved (seems that the issue due to old pip [version 8.1.2] with some broken pip configurations).
