### ISSUE TITLE
issue with bamCoverage --maxFragmentLength 

### ISSUE THREAD

**Issue by naiarabediaga** [fidelram/deepTools#453]
Hi, 

I am analysing ATAC-seq data, and I am trying to use bamCoverage to filter the nucleosomal free reads (paired-read distance <100 pb) by defining --maxFragmentLength 100 and I get the error "unrecognized arguments: --minFragmentLength". 

$ bamCoverage -b  a.bam --maxFragmentLength 100  -o output.bw

It works fine without the --maxFragmentLength argument. 

I have installed what I think is the lates release (deepTools 2.4.0). 

Any help is much appreciated

Naiara

**Comment by dpryan79** [comment]
I'm trying to reproduce this issue with that exact command and can't. Can you confirm that `bamCoverage --version` is showing 2.4.0? I suspect that for some reason python is using an older version.

**Comment by naiarabediaga** [comment]
Hi Devon, 

Thanks for your front reply. You were right, phyton is using bamCoverage 2.2.4. Is there anyway I can force phyton use the latest version? I am working within the institute server, and I suspect that I cannot ask IT to remove the older versions. I am sorry if the questions is too naive.

Thanks a lot

**Comment by dpryan79** [comment]
You can create a virtualenv and install the updated version there:

    virtualenv deeptoolsenv
    source deeptoolsenv/bin/activate
    pip install deeptools

You can change `deeptoolsenv` to whatever you want and put it where ever you like.

**Comment by naiarabediaga** [comment]
All is good now. Thanks a lot!

**Comment by crazyhottommy** [comment]
from the help

```
  --minFragmentLength INT
                        The minimum fragment length needed for read/pair
                        inclusion. This option is primarily useful in ATACseq
                        experiments, for filtering mono- or di-nucleosome
                        fragments. (default: 0)
  --maxFragmentLength INT
                        The maximum fragment length needed for read/pair
                        inclusion. (default: 0)

```

which one should be used? I think --maxFragmentLength should be used but it says otherwise.

Thanks!

**Comment by friedue** [comment]
Are you asking for use with ATAC-seq data?

In principle, you can apply whatever filter you deem reasonable for your data; or ATAC-seq you often want to focus on a specific range of fragment lengths, so you would probably set both, `--minFragmentLength` as well as `--maxFragmentLength`

**Comment by crazyhottommy** [comment]
Thanks for replying! yes, I am asking for ATACseq.

I know I can use something like:
`--minFragmentLength 10 --maxFragmentLength 100`.

It is just the way the help page says confuses me.

for filtering mono- or di-nucleosome fragments, one needs to restrict that the fragment length is shorter than say 147 bp thus --maxFragmentLength. but this info was given in the --minFragmentLength entry.

**Comment by friedue** [comment]
I see; you're taking issue with the omission of the "This option is primarily useful..." in the description of `--maxFragmentLength`.  To filter mono- and dinucleosomes most cleanly, one would have to set indeed both parameters.

**Comment by crazyhottommy** [comment]
yes. thanks for the confirmation though.
