### ISSUE TITLE
Scaling counts on regions with different sizes

### ISSUE THREAD

**Issue by annaquaglieri16** [fidelram/deepTools#458]
Hi there, 

when plotting the profile on regions with different widths (scale-regions command), larger or shorter regions are rescaled to fit the chosen --regionBodyLength. 

How is the rescaling performed? Say a region of 100bp has to be rescaled to 50bp. Do you only re-bin the counts in 50 bins (collapsing bins two by two - using sum? mean?) or you perform other adjustments on the y-axis to avoid that larger regions will be very enriched just because they have been compressed into a smaller regions?

Thanks for your time, 

Anna

**Comment by dpryan79** [comment]
We use linear interpolation and then apply the desired function (mean, median, max, etc.) to the points in the resulting bin.
