### ISSUE TITLE
plotheatmap --regionslabel

### ISSUE THREAD

**Issue by MoHeydarian** [fidelram/deepTools#461]
I'm using deepTools version 2.4.1.0 on a Cloudman instance of Galaxy. When I try to label multiple regions and include spaces in the region names using plotheatmap I get the following error:

Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/mnt/galaxy/tools/deeptools/2.4.1/iuc/package_python_2_7_deeptools_2_4_1/e9855a43ac53/bin/plotHeatmap", line 11, in <module>
    main(args)
  File "/mnt/galaxy/tools/deeptools/2.4.1/iuc/package_python_2_7_deeptools_2_4_1/e9855a43ac53/lib/python/deeptools/plotHeatmap.py", line 585, in main
    hm.matrix.set_group_labels(args.regionsLabel)
  File "/mnt/galaxy/tools/deeptools/2.4.1/iuc/package_python_2_7_deeptools_2_4_1/e9855a43ac53/lib/python/deeptools/heatmapper.py", line 1070, in set_group_labels
    raise ValueError("length new labels != length original labels")
ValueError: length new labels != length original labels

If I replace the spaces with underscores the tool behaves like it should, but I would like to avoid underscores. 

Using the syntax in the documentation (label_1, “label 2”) return the error above. 

Thanks for any help.

**Comment by dpryan79** [comment]
The syntax is `label_1 "label 2"`, with a space rather than a comma. I'll fix this in the Galaxy wrapper for the next bugfix release (the command line documentation is correct).

**Comment by dpryan79** [comment]
This is now fixed in the `develop` branch.

**Comment by rsdmse** [comment]
We're using versions 3.5.1, 3.5.5 and noticed that the comma is still there in the command-line documentation:
```
  --regionsLabel REGIONSLABEL [REGIONSLABEL ...], -z REGIONSLABEL [REGIONSLABEL ...]
                        Labels for the regions plotted in the heatmap. If more than one region is being plotted, a list of labels
                        separated by spaces is required. If a label itself contains a space, then quotes are needed. For example,
                        --regionsLabel label_1, "label 2". (default: None)
```
