### ISSUE TITLE
bamCompare 

### ISSUE THREAD

**Issue by tamarsegal** [fidelram/deepTools#463]
Hi
I have ChIP-seq of H3K9me3 of two conditions, each of them has its own input.
I would like to compare the two conditions, after normalizing/subtracting the input signal.
Is its possible to run bamCompare of each condition against its input, and then compare the two generated bigwig files using bigwigCompare?
Looking forward to your reply.
Thanks,
Tamar

**Comment by dpryan79** [comment]
Hi Tamar,

Yes, this is one of the uses of bigwigCompare.

**Comment by tamarsegal** [comment]
Hi,

Continuation of question #463,

Thanks for your reply, I tried to run it but I got this error:

RuntimeError: The requested sample(M27_CI.bw) has no associated experiment!
If you did not intend to use samples on deepBlue, then it appears either
you misspelled a file name or one of your BAM files is lacking a valid
index.

It seems like I should upload BAM file instead of bigwig, but I would like
to compare two bigwig files.

Below is the command I used:

 bigwigCompare -b1 M27_CI.bw -b2 C27_CI.bw --outFileName C27_M27.bw
--outFileFormat bigwig

 Any idea what cause the error?

In addition, I also tried to run plotFingerprint with 6 samples, two
modifications within two conditions, each of them has its own input. I run
it three times, the first with all 6 samples together, and then separately
for each modifications. By looking at the figures (attached) it seems that
when all samples are plotted together ("fingerprint"), the lines don't
reach 1 on the Y axis. In addition the locations of the lines have changes.
For example when I plotted the two modifications separately
("K9/K27_fingerprint"), the control lines ("C") are separated from the
other lines, but this is not the case when plotted them all together. Is
this OK? I would expect the bin calculation to be the same in all cases,
hence would not expect any difference. What do I miss?

Thanks,

Tamar

2017-01-02 16:41 GMT+02:00 Devon Ryan <notifications@github.com>:

**Comment by dpryan79** [comment]
It looks like you just have a typo with the first issue.

Regarding plotFingerprint, you'll need to attach the plots so I can see them.

**Comment by dpryan79** [comment]
Thanks emailing those to me. What your observing are regions that you should blacklist occupying a very small part of the genome but receiving a disproportionate number of reads. Differences between using a subset or the full set of samples are presumably due to differences in chromosomes present.
