### ISSUE TITLE
Galaxy specific - sortRegions and sortUsing 

### ISSUE THREAD

**Issue by MoHeydarian** [fidelram/deepTools#464]
I'm using deepTools 2.4 in Galaxy. I would like to plot my data with computeMatrix -> plotHeatmap in  the order that the regions are provided to deepTools. There are options to not sort the data (--sortRegions 'no'), though when the advanced options are revealed in the tool form the --sortUsing parameter is invoked and the initial order of the regions is lost. When the advanced options are not revealed the initial order of regions is preserved.

Can the sortUsing parameter be excluded/ignored when invoking --sortRegions 'no', or is there a better way (or am I missing something)? 

Thanks in advance!

**Comment by dpryan79** [comment]
At least in the 2.4.1 wrapper the default is 'keep', which is labeled "maintain the same ordering as the input files". If you specify "no" ("no ordering") or "keep" ("maintain the same ordering as the input files") then --sortUsing is ignored regardless of what is specified.

**Comment by MoHeydarian** [comment]
Yes I see that specifying "no ordering" or "maintain the same ordering as the input files" for computeMatrix and using plotHeatmap without revealing the advanced options preserves the order. 

When revealing the advanced options of plotHeatmap the order is lost, even when specifying "no ordering" for the sortRegions option. I can share the data I'm working with, if that helps.

**Comment by bgruening** [comment]
Mo, maybe this can fix it: https://github.com/fidelram/deepTools/issues/464

**Comment by MoHeydarian** [comment]
Would that revision hide the sortUsing selection box in the tool form if sortRegions is set to "no ordering" (in plotHeatmap)? If the user selects "no order" for sortRegions it could be confusing to still show the selection menu for sortUsing.

**Comment by dpryan79** [comment]
Yes, can you share an appropriate history or dataset with me (I'm ryan@ie-freiburg.mpg.de on the main usegalaxy.org site). If correct, this is a bug in more than just the Galaxy wrapper, since --sortUsing should always be ignored if --sortRegions is either not given or "no" or "keep".

**Comment by MoHeydarian** [comment]
Usegalaxy.org is still on version 2.3.6 (which also doesn't maintain the order of the regions), I'll share a history with you on my Cloudman instance by email shortly.

**Comment by dpryan79** [comment]
Thanks for the cloudman instance, I can see the issue and will try to get it fixed when I'm back in the office on Monday (I'll push out version 2.4.2 then).

**Comment by dpryan79** [comment]
For the sake of posterity, the issue here is that plotHeatmap on the command line defaults to `--sortRegions descend` if `--sortRegions` isn't otherwise specified, whereas by selecting the "show advanced options" in the wrapper you end up with `--sortRegions no` then being passed by default. The defaults passed under "show advanced options" should really match what would be used if those weren't shown, so I'll update that to have "descend" selected by default.

**Comment by dpryan79** [comment]
The change will be present in the 2.4.2 release, which will go out this week.
