### ISSUE TITLE
Question - way to retrieve region names from a heatmap?

### ISSUE THREAD

**Issue by MoHeydarian** [fidelram/deepTools#466]
I'm using deepTools 2.4 in Galaxy. 

Is there a way to retrieve region names from plotHeatmap? For example, after I cluster the output of computeMatrix using plotHeatmap, I would like to retrieve the region IDs from a particularly interesting cluster for further analysis (or spot checking on a genome browser). 

I know the --saveMatrix option will write out the underlying values used to generate the heatmap, but I do not see region IDs associated with these underlying values. 

A great feature for interrogating ones data with deepTools would be an interactive product from plotHeatmap that would allow the user to identify which row corresponds to which region by hovering over the row with the mouse pointer. I may have missed my chance to ask Santa for this ;)

**Comment by dpryan79** [comment]
There's an --outFileSortedRegions option that should do this for you.

**Comment by MoHeydarian** [comment]
Oh I see, "Save the regions after skipping zeros or min/max threshold values" nicely provides a table with the regions IDs. Thanks, Devon!
