### ISSUE TITLE
bamCoverage and ribosome profiling data

### ISSUE THREAD

**Issue by bontus** [fidelram/deepTools#468]
The --Offset parameter is indeed a good start, however, offsets are dependent on read length and hence this option should be expanded.
Suggestion: a parameter such as --OffsetList that takes both the read lengths and associated offset values.
Example: --OffsetList 25,26,27,28,29,30:12,12,13,13,14,14 where

read length <-> offset
25 / 26 <-> 12 nt
27 / 28 <-> 13 nt
29 /30 <-> 14 nt

Best

**Comment by dpryan79** [comment]
I'll file this under "not going to implement". While it's true that the exact location of the base to use can vary by one base depending on the read length, in my experience there's no tangible benefit to caring about this. Pausing and similar profiling is most reasonably processed at the codon level, so a slight increase in the base-level variance will have minimal effect on down-stream processing.
