### ISSUE TITLE
Segmentation fault in 'plotHeatmap'

### ISSUE THREAD

**Issue by mbk0asis** [fidelram/deepTools#474]
Hi. 
I'm getting 'Segmentation fault (core dumped)' message every time I ran the 'plotHeatmap'.
I used the following code to draw a plot,

`plotHeatmap -m HD.bigWig.matrix.mat.gz -out HD.heatmap.png`

I'm using deeptools version 2.4.2, and updated pyBigWig to 0.2.8 version.

What did I do wrong?

Thank you!

**Comment by dpryan79** [comment]
That's odd, can you either email the `HD.bigWig.matrix.mat.gz` to me or post it somewhere? That'd be needed to debug this. My email address is ryan@ie-freiburg.mpg.de

**Comment by dpryan79** [comment]
I'll close this for now, since I haven't received further information.

**Comment by mbk0asis** [comment]
Sorry!
I should've told you earlier.
Somehow, I haven't seen the error message again.
I might used a wrong file for the input.

Please, close this.

Sorry again.





----
*Byungkuk Min*
Ph.D Candidate
University of Science & Technology, <http://ust.ac.kr>
Korea Research Institute of Bioscience and Biotechnology
<http://www.kribb.re.kr>
125 Gwahangno, Yuseong-Gu, Daejeon, 34141, Korea
Laboratory : 042-860-4423
FAX : 042-860-4608
Cell phone : 010-5209-7377

**Comment by dpryan79** [comment]
Great, thanks!
