### ISSUE TITLE
plotFingerprint - Error while reading all BAM files at once

### ISSUE THREAD

**Issue by venuthatikonda** [fidelram/deepTools#475]
Hi,
When I use all BAM files at once as input to plotFingerprint function, it is raising an error `[bwHdrRead] There was an error while reading in the header!`. However, if I provide individual path to each BAM, it is working fine. Am I missing anything here.

Here is how am I using.

```
/b06x-isilon/b06x-a/adshh/scripts/tools/deepTools/bin/plotFingerprint -b /b06x-isilon/b06x-a/adshh/results/chip-hs37d5-alignments/MB12/MB12*/*.bam --minMappingQuality 30 --skipZeros -T "Fingerprints plot" --plotFile fingerprints.png

[bwHdrRead] There was an error while reading in the header!
Traceback (most recent call last):
  File "/b06x-isilon/b06x-a/adshh/scripts/tools/deepTools/bin/plotFingerprint", line 11, in <module>
    main(args)
  File "/usr/lib64/python2.7/site-packages/deeptools/plotFingerprint.py", line 363, in main
    num_reads_per_bin = cr.run()
  File "/usr/lib64/python2.7/site-packages/deeptools/countReadsPerBin.py", line 244, in run
    y = pyBigWig.open(x)
RuntimeError: Received an error during file opening!
```

But when I modify as following, it works fine.

```
/b06x-isilon/b06x-a/adshh/scripts/tools/deepTools/bin/plotFingerprint -b /b06x-isilon/b06x-a/adshh/results/chip-hs37d5-alignments/MB12/MB12_H3K27ac_CAGATC/MB12_H3K27ac_CAGATC-combined.bam /b06x-isilon/b06x-a/adshh/results/chip-hs37d5-alignments/MB12/MB12_Input/MB12_Input-combined.bam --minMappingQuality 30 --skipZeros -T "Fingerprints plot" --plotFile fingerprints.png
```
All BAM files are indexed and available at the same location as BAMs with the same name.

Thank you.

**Comment by dpryan79** [comment]
Your file globbing is picking up more than the two BAM files you think it is. At least one of the additional BAM files isn't indexed.

**Comment by venuthatikonda** [comment]
Yes, there are more than 2 BAM files (12 histone marks and input). Everything was indexed. I even re-indexed the BAMs and tried but no use. Is there any other reason for function to rise this error?

**Comment by dpryan79** [comment]
This will only happen if (1) the BAM file can't be opened, (2) the BAM file isn't indexed or (3) the index can't be opened/is invalid. You can restrict your file globbing to a subset of the files to see which sample is problematic.

BTW, programs don't actually see things like, `/some/path/*.bam`. Your shell expands them to something like `/some/path/sample1.bam /some/path/sample2.bam /some/path/sample3.bam`. That's why file globbing is never the root cause of the problem.

**Comment by venuthatikonda** [comment]
Solved. So I ran `samtools idxstats` on every BAM and checked the line numbers in all of the resulting files. There are 2 BAMs with some errors. Without these 2 BAMs everything is working fine.

Thanks !

**Comment by dpryan79** [comment]
Great!
