### ISSUE TITLE
correlation of bam/bigwig coverage with bed files?

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#479]
Hi,

I've got a bam file that I can transform into a bw (bigwig) file of read coverage, and I would like to correlate the coverage to a list of bed files, each of which has bed regions labelled as a group of 6 different states (Constitutive_Het, Promoter, Transcribed, etc.).

What's the best way to do such 1 bam vs multiple bed files correlation using deeptools?

Thx

**Comment by dpryan79** [comment]
I guess I'm not sure what's being correlated in this context. Perhaps you want something like `plotEnrichment` instead?

**Comment by avilella** [comment]
I have used the multiBamSummary/plotCorrelation/plotPCA tools before to
correlate a set of bams.

Here I would like a correlation of coverage in 1 bam with where that
coverage is present, against a collection of bed files.

**Comment by dpryan79** [comment]
OK, so `plotEnrichment`, likely after splitting your BED files according to column 4.
