### ISSUE TITLE
FAQ: Error with UCSCtool bedGraph to bigWig

### ISSUE THREAD

**Issue by friedue** [fidelram/deepTools#48]
Now that we have deepTools being tolerant towards chromosome naming, I totally forgot that other tools are not that forgiving. I just put the error here so I eventually make an FAQ entry out of it:

>  BedGraph to bigWig on data 76
An error occurred with this dataset: 2L is not found in chromosome sizes file

**Comment by vivekbhr** [comment]
With recent changes this won't be required anymore..
