### ISSUE TITLE
--Offset in plotEnrichment

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#481]
It would be great to have --Offset also working in plotEnrichment (as for bamCoverage)
Use case: calculate overlaps of reads with BED files based on start coordinates only (--Offset 1)

My current and cumbersome workaround is to create a modified bam-file of start sites.

**Comment by dpryan79** [comment]
Please try the `feature/implement481` branch.

**Comment by dpryan79** [comment]
@thomasmanke This is now in the develop branch.
