### ISSUE TITLE
Problem with scaleFactor setting in bamCoverage

### ISSUE THREAD

**Issue by ycl6** [fidelram/deepTools#482]
Hi,

I am using bamCoverage to generate signal file for viewing on UCSC. So I choose to output as bedGraph format because I need to edit the chrom prefix before I convert it to bigwig. I set the scaleFactor as follow 

`bamCoverage --numberOfProcessors 10 --scaleFactor 0.9022 --binSize 1 --outFileFormat bedgraph --filterRNAstrand forward --bam file.bam -o forward.bedGraph`

But when I view the output file, it seems the values are not scaled. Why is it so?

```
1       1640711 1640713 6
1       1640713 1640725 8
1       1640725 1640726 12
1       1640726 1640778 16
1       1640778 1640780 14
1       1640780 1640844 12
1       1640844 1640853 10
1       1640853 1640854 4
1       1640854 1640857 2
1       1640857 1640879 0
```

**Comment by dpryan79** [comment]
Please note the help for the `--scaleFactor` option:

> Indicate a number that you would like to use. When used in combination with --normalizeTo1x or --normalizeUsingRPKM, the computed scaling factor will be multiplied by the given scale factor.

Since you didn't use `--normalizeUsingRPKM` or `--normalizeTo1X` then `--scaleFactor` was ignored.

Having said that, I can make this possible in the next release.

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch and will be present in the 2.5.0 release.
