### ISSUE TITLE
tempfile handling

### ISSUE THREAD

**Issue by bgruening** [fidelram/deepTools#485]
As per IRC discussion the tempfile handling of deeptools might not be ideal.
This function is producing a lot of tempfile that are not cleanup automatically: https://github.com/fidelram/deepTools/blob/fd4e8dc896c2ac6f838e35e8160046d6ac862692/deeptools/utilities.py#L183

This can be a problem for long running systems and NFS file systems.

**Comment by dpryan79** [comment]
Is there a way in Galaxy to set $TMP to the working directory? That'd fix this.

**Comment by dpryan79** [comment]
Alternatively, we could directly do that in the wrapper.

**Comment by bgruening** [comment]
Yes, on Galaxy we can fix it. The question was more general, is this something we should worry about for other users that don't cleanup there temp. Or this is a non-issue?

**Comment by dpryan79** [comment]
This is a non-issue. If people want the temp directory somewhere else then they can set it there. In Galaxy there's no convenient way to do this, so we can change it to `.`. I imagine that this only becomes an issue because `/tmp` starts to run out of names eventually (otherwise the files will get deleted once deepTools completes).

**Comment by bgruening** [comment]
Thats the point, deepTools is not removing these files and they will stay.

**Comment by dpryan79** [comment]
That should only happen on error. If that's actually happening then it's a bug.

**Comment by bgruening** [comment]
Good to know. Because the tempfiles are created with "delete=False". I will keep an eye on it.

**Comment by fidelram** [comment]
As @dpryan79 says, the intermediate files that deepTools creates are deleted unless the program is stop or crashes.  Normally, this is not a problem but indeed those intermediate files tend to accumulate over time. The `delete=false` is required for the reduce part of deepTools, when all temp files are collected.

One potential solution is for deepTools to run a garbage collection once it is started to delete files older than  a month for example. In galaxy this should work fine, but for command line, only the user files will be taken care.

**Comment by dpryan79** [comment]
@bgruening I have a branch [with this](https://github.com/fidelram/deepTools/blob/feature/tempLocationGalaxy/galaxy/wrapper/deepTools_macros.xml#L3-L9) added to each wrapper. If that's the desired behavior for Galaxy then I'll include it for the next release (E.T.A. one month).

**Comment by bgruening** [comment]
@dpryan79 thanks, but on Galaxy we can simply work around this by setting these ENV vars in the job_conf.xml. usegalaxy.org just found many of those files. So either deeptools was crashing a lot or deeptools does not clean correctly after them self. As soon as our Galaxy is back again I will watch this more closely. Feel free to close this issue.

**Comment by dpryan79** [comment]
OK, I'll revert those changes. If you/they find a real culprit then let me know, it's easy enough to fix once I know where to look.
