### ISSUE TITLE
--outRawCounts is normalized? 

### ISSUE THREAD

**Issue by rojasp** [fidelram/deepTools#486]
Hi, I have a question about the output generated by multiBamSummary.
I'm using this approach to get the coverage over a specific region. For that, I've used a normalized bigwig file (normalization by scale factor), as follow
MultiBigwigSummary BED-file -b FileNorm -out coverage.zip --BED region.BED --outRawCounts coverage

I would like to know if the coverage that --outRawCounts reports, takes in account the normalized data, and also, I would like to know if it uses RPKM for reads.

Thank you!

**Comment by dpryan79** [comment]
It'll output whatever is in the bigwig file. So if the bigwigs are normalized then multiBigWigSummary will honor that.

Realistically, all multiBigWigSummary is doing is going over the BED regions, getting the average score/signal/whatever-you-want-to-call-it from each sample, and then writing that directly to a file.

**Comment by rojasp** [comment]
Thank you @dpryan79! 
Just another quick question, I get that previous normalized bigwig file from bamCoverage --scaleFactor to a specific number of reads, Is this a proper file to use as an input in MultiBigwigSummary ?

Thanks again

**Comment by dpryan79** [comment]
Presuming you purposely set the scale factor to make the bigWigs comparable then that would be a fine input. If you just randomly set the scale factor to 10 for some samples for no reason then that'd be a meaningless input. I presume the former was the case :)

**Comment by rojasp** [comment]
Yes, I set a scale factor to a specific number of reads to compare more than one sample :) Thank you very much @dpryan79 for all the information and patient!
