### ISSUE TITLE
--yMax an --yMin as vector

### ISSUE THREAD

**Issue by apastore** [fidelram/deepTools#487]
Is possible to set --yMax and --yMin as vectors as for the --zMax and --zMin?

Thanks!

**Comment by vivekbhr** [comment]
@apastore No --yMin and --yMax only take one argument.

**Comment by apastore** [comment]
yes .. would not be useful when comparing tracks with different signal intensities ?

**Comment by vivekbhr** [comment]
Usually comparing different intensities are solved by changing the --zMin and --zMax , for visualization on heatmap. Do you want to to modify the profile plot?

**Comment by dpryan79** [comment]
This is presumably for the profiles on top of the heatmaps (or directly in plotProfile). If we're going to allow different Z coloring scales, we might as well do it for the profile plots too. I could see this being useful when DNA methylation is incorporated into plots.

**Comment by apastore** [comment]
Yes exactly! This is for the profile plot on the top of heatmap.

I work with many different kind of tracks, including chip, atac, and rna. And every marker has it own dynamic range. (Maybe also the possibility to log some of the plot would also help sometimes)

Thanks!

**Comment by dpryan79** [comment]
The `feature/implement487` now implements this in plotProfile and plotHeatmap. The former generally looks nicer IMO. This is all a bit hacky, since matplotlib doesn't want to space things out nicely by default and forcing it to do so can result in the heatmaps not perfectly aligning with the profiles.

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch, which will become the 2.5.0 release at the end of the month.
