### ISSUE TITLE
--outFileCorMatrix row/column labeling error

### ISSUE THREAD

**Issue by jsonbl** [fidelram/deepTools#493]
Hi, I'm using multiBigWigSummary and plotCorrelation to generate heatmaps. When I cross-checked the pearson correlation table generated by --outFileCorMatrix, I noticed that the labels for both the row and columns are incorrect. 

When I replot the matrix in R, I get more-or-less the same heatmap but the labels are all scrambled. If I rename the row and column headers of the table generated by the --outFileCorMatrix based on the filename order going into multiBigWigSummary, then I can re-create the matrix in R in a way that makes sense. 

I'm using the following command:

multiBigWigSummary bins -b *.bw --chromosomesToSkip chrU chrUExtra chrYHet chrM -bs 25000 -out results.25kb.npz; plotCorrelation -in results.25kb.npz -c pearson -p heatmap --removeOutliers --colorMap RdBu_r -o heatmap.25.pearson.png

**Comment by dpryan79** [comment]
I squeezed the fix for this into the next bugfix release, which I hope to push out today.

**Comment by dpryan79** [comment]
This is now fixed in version 2.4.3, which is available in pypi (and soon conda).

**Comment by jsonbl** [comment]
Great and thanks! Verified fix in v2.4.3
