### ISSUE TITLE
computeMatrix scale-regions: Scaling counts on regions and flanking regions

### ISSUE THREAD

**Issue by AlicePsyche** [fidelram/deepTools#495]
Hi, all

I just want to know how does `computeMatrix scale-regions` normalize flanking regions with different length regions in the bed file? Sorry I didn't find related documentary. 

For example, I have two regions 100bp and 1000bp. When I run `-b 3000 -a 3000 --regionBodyLength 5000 `, the flanking region length is indeed upstream/downstream 3000bp no matter the regionbodylength is actually 100bp/1000bp, or the upstream/downstream is some kind of rescaled length: for 100bp region, it's 100/5000 * 3000 = 60bp; for 1000bp region, it's 1000/5000 * 3000 = 600bp ? 

Thanks for your help.

**Comment by dpryan79** [comment]
In your example, the flanking region size is 3kb regardless of the region size. We don't provide a method to have the flanking size vary according to the region size. 

Devon
