### ISSUE TITLE
Readme cleanup

### ISSUE THREAD

**Issue by bgruening** [fidelram/deepTools#498]
@dpryan79 I fixed the readme real quick in https://github.com/fidelram/deepTools/commit/6bad80c203eca77fbf364521bc23c39a3edebf7c

But there are two readme files, one rst, one md. Is this a result of a bad merge?

**Comment by dpryan79** [comment]
I think the rst is generated when `python setup.py sdist` is run (so things render better on pypi).

**Comment by dpryan79** [comment]
Hmm, at least that's what I assumed it came from. @vivekbhr what was the purpose of this?

**Comment by fidelram** [comment]
Thanks Bjoern. I think the Readme.rst is required for pypi. We should pick one of those.

**Comment by vivekbhr** [comment]
.md file is the one which we have been updating. But rst was required for pypi.. are we sure pypi can't use .md

**Comment by dpryan79** [comment]
I'm pretty sure there's a way to get pypi to use the markdown. I'll take care of that for the Friday release.

**Comment by bgruening** [comment]
Mh ... http://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work

**Comment by dpryan79** [comment]
Ah, right, it only vaguely works. Perhaps we can just use a stub and link to RTD.

**Comment by bgruening** [comment]
If you don't include any you still see the metadata I think, which can include a link to RTD and is not that bad. Otherwise you can also stick to rst here.

**Comment by dpryan79** [comment]
I've just made it a bit of a stub with a link to RTD in the `develop` branch, so it can just be ignored in the future.
