### ISSUE TITLE
Error message when normalizing to RPKM - bamCoverage

### ISSUE THREAD

**Issue by SaraJeanne08** [fidelram/deepTools#501]
I am running bamCoverage both with and without normalization - and with separate tracks generated per strand. I am getting a error message about filtering ( using only ~50% of the reads) when I pass the command with normalization but I do not get this message when I run it in the exact same way without normalization. Except for binSize = 1, I am running otherwise all the default settings. Can you please explain this error message? 

I am assuming my bw file is fine (just a output bug) because I am generating a track for each strand (so half the reads are not being used) but I want to be certain. Thank you in advance.

Output Below:

normalization: RPKM
minFragmentLength: 0
verbose: False
out_file_for_raw_data: None
numberOfSamples: None
bedFile: None
bamFilesList: ['Aligned.sorted.out.trimmed.bam.dupesmarked.bam']
ignoreDuplicates: False
numberOfProcessors: 16
samFlag_exclude: None
save_data: False
stepSize: 1
smoothLength: None
center_read: False
filter_strand: forward
defaultFragmentLength: read length
chrsToSkip: []
region: None
maxPairedFragmentLength: 1000
samFlag_include: None
binLength: 1
blackListFileName: None
maxFragmentLength: 0
minMappingQuality: None
zerosToNans: False
Due to filtering, 48.8099498809% of the aforementioned alignments will be used 16256222.6299

**Comment by dpryan79** [comment]
That's not an error, just an informational message.

**Comment by SaraJeanne08** [comment]
Thank you! I appreciate your help with this.
