### ISSUE TITLE
multiBigwigSummary Bed-file and region size normalization

### ISSUE THREAD

**Issue by zsun89** [fidelram/deepTools#505]
Hi. I have maybe a naive question for multiBigwigSummary in the Bed-file mode. When I activate the -outRawCounts flag and get a tab file as a output, are these "AVERAGE scores" of each region normalized to the SIZE of each corresponding region? Since the regions in the bed file may not be of same size, I want to be sure the scores for each region are comparable or they need further normalization to the size of each regions (like in the situation of RPKM)? Thank you!!

**Comment by vivekbhr** [comment]
Using multiBigWigSummary you want to compare samples, not regions with each other. the regions stay common between samples, therefore you don't have to worry about different regions with different sizes.

**Comment by zsun89** [comment]
Thank you for your comment @vivekbhr. In my case, I actually do want to compare regions with each other. I only have one bigwig file as input and do not intend to generate a matrix for correlation or compare between samples. I want to use multiBigwigSummary in a nontypical way to just sum up signal in each region and generate a bed file. However, I don't know if the signals in each region are normalized to region size (under Bed-file mode each region is a bin) or not.

**Comment by dpryan79** [comment]
There's no region size-based normalization done by default. You'll need to post-process your output.

**Comment by zsun89** [comment]
Thank you for the answer! @dpryan79

**Comment by vivekbhr** [comment]
@zsun89 you might want to do computeMatrix `scale-regions` in case you are comparing several groups of regions with each other using one bigwig..
