### ISSUE TITLE
how to process spike-in with bamCoverage and plotHeatmap

### ISSUE THREAD

**Issue by apastore** [fidelram/deepTools#509]
Hi I have a question, I have Drosophila genome spike-in in a chip-seq experiment. Does anybody have experience on the best way to normalised and process those samples to generate bw and countmatrix?

I am following the instruction of the vendor: 

map reads to the sample genome (human, mouse, etc.)
map reads to the DM genome
count unique DM sequence tags. Identify sample with least amount of tags
Count DM tags from other samples. Create a normalization factor = lowest_sample/sample_of_interest

then I use the normalisation factor ${SPIKE} in deeptools as follow:

bamCoverage -b ${SAMPLE}/${SAMPLE}.nodup.norm.bam -o /scratch/${PBS_JOBID}/${SAMPLE}/${SAMPLE}.bw \
			-p 1 --normalizeTo1x ${genomesize} \
			--scaleFactor ${SPIKE} \
			--ignoreForNormalization chrX chrY \
			-bl ${ENCODEBED} \
			--smoothLength 40 \
			--binSize 10 \
			--centerReads --extendReads 150

Since I am getting a modest increase, and the vendor results are a modest decrease of signal I am wondering if I am doing something wrong with bamCoverage --scaleFactor argument or if the discrepancy is due to the different processing of the bw between my pipeline (deeptools based) and the vendor one (custom made).

Thanks a lot for your support  and advice!

**Comment by dpryan79** [comment]
The general process would be to run something like multiBamSummary on the fly BAM files and use the text files from that in DESeq2 to get size factors. Those size factors then become scale factors in bamCoverage. Just note that `--scaleFactor` is multipled against each value, whereas I think DESeq2 divides it (so invert things).

**Comment by apastore** [comment]
Thanks ! I will test this!

**Comment by dpryan79** [comment]
@apastore Let me know how it goes. I don't know of anyone internally who is doing this (off-species spike-ins are a great idea though), so I can't foresee exactly how it'll turn out.

**Comment by apastore** [comment]
Sure, I will do.

**Comment by millerh1** [comment]
Just curious... how did this go?
