### ISSUE TITLE
tmp files still writing to default tmp folder during sort step and killing run

### ISSUE THREAD

**Issue by SaraJeanne08** [fidelram/deepTools#512]
Dear Developers,

We have been having issues with deepTools - bamCoverage writing temp files and filling up our folder and thus killing / erroring out our runs. We have updated the config file as advised to others on your google forum but the program is still sorting on our linux system on the default tmp folder and still filling up that folder. We tried updating the config file again by editing the sort command - 
Originally the config file pointed to this:
[external_tools]
sort: sort

And we changed it to this:
[external_tools]
sort: sort -T /newfilserv/tmp

this did not work - tmp files still moved over to the default tmp folder for this step and killed the run.

Thank you!

Sara

**Comment by dpryan79** [comment]
Try setting `tmp_dir: /some/path` in the config file. That's probably the simplest solution.

**Comment by dpryan79** [comment]
If it helps, I mean the line [here](https://github.com/fidelram/deepTools/blob/master/deeptools/config/deeptools.cfg#L23)

**Comment by dpryan79** [comment]
Feel free to reopen this if what I suggested doesn't solve the problem.
