### ISSUE TITLE
Error with correctGCbias.py

### ISSUE THREAD

**Issue by gunjangala** [fidelram/deepTools#517]
Hello,
I am trying to use "correctGCbias" command from deeptools package version 2.4.2 and get the following error for "GCbiasFrequenciesFile" option. 

```
$ correctGCBias -b sample_23.sorted.bam --effectiveGenomeSize 12100000 -g sacCer3.2bit --GCbiasFrequenciesFile freq1.txt -o tmp.bam
/share/apps/python/2.7.12/intel/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/lib/npyio.py:893: UserWarning: loadtxt: Empty input file: "freq1.txt"
  warnings.warn('loadtxt: Empty input file: "%s"' % fname)
Traceback (most recent call last):
  File "/share/apps/deeptools/2.4.2/intel/bin/correctGCBias", line 11, in <module>
    main(args)
  File "/share/apps/deeptools/2.4.2/intel/lib/python2.7/site-packages/deeptools/correctGCBias.py", line 553, in main
    F_gc = data[:, 0]
IndexError: too many indices for array
```

freq1.txt is an empty text file, so the error raised for an empty file mist be valid. But the documentation says that option is for output file/path and the default for it is "None". Also, I referred this [link](http://deeptools.readthedocs.io/en/latest/content/tools/computeGCBias.html) to use correctGCbias command. Can you please help me fix this?

**Comment by dpryan79** [comment]
Can you attach the `freq1.txt` file to your post? It should be a text file with at least 3 columns, but I suspect that yours is empty for some reason.

**Comment by dpryan79** [comment]
The problem is that `freq1.txt` is empty. How did you create that file? It should be the output of `computeGCBias`.

**Comment by gunjangala** [comment]
I just execute `touch freq1.txt` and mention it in the option for `--GCbiasFrequenciesFile`. The following is what happens if I do not use `--GCbiasFrequenciesFile` and/or not mention the filename.
```
$ module purge
$ module load deeptools/intel/2.4.2 
$ correctGCBias -b sample_23.sorted.bam --effectiveGenomeSize 12100000 -g sacCer3.2bit --GCbiasFrequenciesFile -o tmp.bam
usage: An example usage is:
 correctGCBias -b file.bam --effectiveGenomeSize 2150570000 -g mm9.2bit --GCbiasFrequenciesFile freq.txt -o gc_corrected.bam [options]
correctGCBias: error: argument --GCbiasFrequenciesFile/-freq: expected one argument
$ correctGCBias -b sample_23.sorted.bam --effectiveGenomeSize 12100000 -g sacCer3.2bit -o tmp.bam
usage: An example usage is:
 correctGCBias -b file.bam --effectiveGenomeSize 2150570000 -g mm9.2bit --GCbiasFrequenciesFile freq.txt -o gc_corrected.bam [options]
correctGCBias: error: argument --GCbiasFrequenciesFile/-freq is required
```

I followed along the example documentation mentioned [here](http://deeptools.readthedocs.io/en/latest/content/tools/computeGCBias.html). How exactly is `correctGCbias` is to be executed?

**Comment by dpryan79** [comment]
You *must* use `computeGCBias` first. That will create the `freq1.txt` file.

**Comment by gunjangala** [comment]
Ok.I see. I missed out on that information. Thanks, Devon Ryan.
