### ISSUE TITLE
Input-subtracted bigWig normalised to RPM not RPGC

### ISSUE THREAD

**Issue by jma1991** [fidelram/deepTools#521]
I want to create input-subtracted bigWig files normalised to reads per million (RPM). I do not want to use the RPGC method implemented. To do this I am calculating the number of mapped reads in my BAM files and dividing this number by 1 million (scaling factor). I then divide 1 by my calculated scaling factor and pass this to the scaleFactors argument. To create an input subtracted bigwig which is normalised using these factors I'm using the following command:

bamCompare -b1 ChIP.bam -b2 Input.bam -o Subtract.bw --ratio subtract --scaleFactors 0.4:0.8

I'm unsure whether the scaleFactors argument is used given I've not set the --normalizeTo1x argument. Could you confirm this is the correct approach?

I am using deepTools version 2.4.3

**Comment by dpryan79** [comment]
You don't need (or want) `--normalizeTo1x`, the scaling factors should be getting appropriately applied already.
