### ISSUE TITLE
Feature Request: Adding "label" option to ComputeMatrix function 

### ISSUE THREAD

**Issue by venuthatikonda** [fidelram/deepTools#523]
Hi,

I've been using `computeMatrix` function, it's great. I was wondering whether it would be possible to add `label` option to this function to label the samples provided instead of original filenames. Sometimes long filenames are messing up the plot. Though, `samplesLabel` exists with `plotProfile`, it is sometimes difficult to use `computeMatrix` result at a later point and also with other programs.

example

```
~/myTools/deepTools/bin/computeMatrix reference-point --referencePoint center -b 4000 -a 4000 -R promoters.bed -S my_file_name_1.bw my_file_name_2.bw --label mf1 mf2 --skipZeros -o matrix_result.gz --outFileSortedRegions regions_sorted.txt
```

Thank you.

**Comment by dpryan79** [comment]
Thanks for the reminder, I'd already forgotten about this!

Can you try the `feature/implement523` branch? I just added this in but it'd be nice to have someone other than me test it :)

**Comment by dpryan79** [comment]
I've merged this into the `develop` branch, since I'd like to get 2.5.1 out on the 12th.
