### ISSUE TITLE
plotFingerprint -b $chip --JSDsample $input

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#527]
The subject line will not calculate JSD, Chance etc.  Instead one needs to specify

plotFingerprint -b $chip $input --JSDsample $input 

This is somewhat counter-intuitive. Would it make sense to add the JSDsample automatically to the list of bam files?

**Comment by dpryan79** [comment]
I can have it added in if it's not already there I suppose. The reason for the current implementation is simply that plotFingerprint pre-existed the JSD code, so that was the simplest implementation.

**Comment by dpryan79** [comment]
This is implemented in `develop`. Please give it a test with `module load deeptools/develop`.
