### ISSUE TITLE
Correlation coefficients in heatmap don't match the value in the text file

### ISSUE THREAD

**Issue by bapoorva** [fidelram/deepTools#529]
Hi,

I ran multibigwig summary on some wiggle tracks and then used plotcorrelation. However, the correlation coefficients in the heatmap do not match the values in the text file. I am not sure what is wrong. Can somebody help me out with this ? 

So, here is my plot,
[bwtracks2.pdf](https://github.com/fidelram/deepTools/files/1001700/bwtracks2.pdf)

and the text file

[bwtracks.txt](https://github.com/fidelram/deepTools/files/1001705/bwtracks.txt)

**Comment by dpryan79** [comment]
What version are you using, I think I fixed this in version 2.4.3.

**Comment by bapoorva** [comment]
I am using version 2.4.2. I will update it. Thank you
