### ISSUE TITLE
Chromosome names did not match between the bigwig files

### ISSUE THREAD

**Issue by TracyBallinger** [fidelram/deepTools#532]
I am trying to use multiBigwigSummary to merge multiple bigwig files and I'm getting this error: 
The following chromosome names did not match between the the bigwig files
chromosome      length
chrUn_KI270581v1              7046
chrUn_KI270364v1              2855
chrUn_KI270393v1              1308
....

The command is 
multiBigwigSummary BED-file -b bigwigfiles -out outfile.npz -BED bedfile -p 2
I've tried running it on just chr1 running by adding the -r chr1 option, and I get the same error.  
I've also tried running it with the --chromosomesToSkip option, listing the chromosomes that are listed in the error message, and I still get the error.  
Is there any way around this?  Can multiBigwigSummary work on bigwig files that don't have exactly matching chromosomes?  

Thanks!

**Comment by dpryan79** [comment]
That's just a warning, you'll get correct results for the chromosomes that exist (or have names that can be munged to exist) in all of the files.

**Comment by 1391794753** [comment]
I have a similar problem like this:when i'm trying the following command:
 computeMatrix scale-regions -S GSM2190583.bigwig GSM2190586.bigwig -R GSM2190583.bed GSM2190586.bed --beforeRegionStartLength 3000 --regionBodyLength 5000 --afterRegionStartLength 3000 --skipZeros -o matrix.mat.gz
and i get the error:
The following chromosome names did not match between the bigwig files
chromosome	length
chr9_gl000201_random	     36148
chr8_gl000197_random	     37175
 chrUn_gl000244	     39929
 chrUn_gl000249	     38502
已杀死
By the way, there is not a correct result exist.
