### ISSUE TITLE
multiBigwigSummary: misleading help

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#533]
-out OUTFILENAME
                        File name to save the gzipped matrix file needed by
                        the "plotHeatmap" and "plotProfile" tools. (default:
                        None)

is misleading and should instead refer to plotPCA and plotCorrelation.
Apparently this was copied over from computeMatrix (where it is correct)

**Comment by dpryan79** [comment]
This is fixed in the up-coming 2.5.2 release.
