### ISSUE TITLE
bamCoverage stdout

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#535]
Can bamCoverage print to STDOUT when producing bedGraph output?

**Comment by dpryan79** [comment]
Not really, no. Internally it writes a bunch of temp files and then merges them together to get the final output. This is already written to disk, so we never needed it to be printed out. Doing so wouldn't end up saving on temp space or I/O, if that's what you're hoping for (though at some point the step of merging and sorting the temp files should be removed to allow just a single output file to be directly written).
