### ISSUE TITLE
plotCorrelation scatterplot needs option to alter scales

### ISSUE THREAD

**Issue by connorrogerson** [fidelram/deepTools#536]
PlotCorrelation scatterplots are useful for checking correlation between replicates but the tool needs an option to define the maximum of an axis. I've had many plots where all the data are squished into the bottom left corner because the scales are way off. I'm also already using --skipZeros and --removeOutliers options.

![image](https://user-images.githubusercontent.com/16903004/26871803-505a98c6-4b6c-11e7-98a9-1f2a3959c8cb.png)

**Comment by dpryan79** [comment]
I've implemented this in the `develop` branch for the 2.6.0 branch.
