### ISSUE TITLE
Rotating labels in profilePlot

### ISSUE THREAD

**Issue by blaiseli** [fidelram/deepTools#537]
This is a feature request (unless the possibility already exists): It would be nice to have a way to chose a rotation angle for the labels corresponding to the `--startLabel` and `--endLabel` options, and more generally, to have more customization options (size, colours) for these labels and others.

**Comment by dpryan79** [comment]
Label rotation is now implemented in the branch slated to become version 2.6.0. This will work with both plotProfile and plotHeatmap. Some of the other stuff can be done with a .matplotlibrc. We're not going to provide options for literally everything, it's already getting unwieldy to test everything.
