### ISSUE TITLE
Font size and type in plotHeatmap

### ISSUE THREAD

**Issue by rbronste** [fidelram/deepTools#540]
Hi,

I am trying to customize the font size and type (12-14, Helvetica), wondering how I can go about doing that? Seems as though I can change at least the size in plotHeatmap.py and recompile but can't locate font type. Thanks.

Rob.

**Comment by dpryan79** [comment]
I don't think we hard code the font type anywhere, so presumably you can make a `matplotlibrc` file and hopefully that will be honored.

**Comment by ernstki** [comment]
For reference:

<https://matplotlib.org/stable/tutorials/introductory/customizing.html#the-matplotlibrc-file>
