### ISSUE TITLE
docrequest: is sorting in heatmaps based on gene body or whole row?

### ISSUE THREAD

**Issue by endrebak** [fidelram/deepTools#543]
You store meta-info about upstream/downstream in your matrix so it is theoretically possible that the sorting is only based on the contents of the gene bodies. Is it?

Thanks for deeptools btw, it is brilliant.

**Comment by dpryan79** [comment]
It's based on the whole row, the sorting function doesn't know where sample or gene body bounds are.

**Comment by steffenheyne** [comment]
just a little thing to add: plotHeatmap has an option "–sortUsingSamples" with that you can select the samples used for sorting in case you have a multi-sample heatmap (eg. "–sortUsingSamples 1 3"). Per sample we always use the full row
