### ISSUE TITLE
plotProfile could also accept region files?

### ISSUE THREAD

**Issue by endrebak** [fidelram/deepTools#544]
I want to compare different groups of genes in the profileplot. If I have created the matrix for all the genes, it would be nice to be able to create different plots comparing different subsets of genes just with profilePlot. Is that possible (possibly with some hack)?

The approriate way seems to be to use computeMatrix with different combinations of -R flags, but that is very time-consuming.

**Comment by steffenheyne** [comment]
You can have different groups of regions in a bed file by putting "deepTools_group" in a header line at a specific column. This can be used to indicate a column with group labels. Note that these should be sorted such that all group entries are together. So to see how this should look like, use your usual region file, do kmeans clustering and use "–outFileSortedRegions" with plotHeatmap.

**Comment by dpryan79** [comment]
You can also use `computeMatrixOperations` on the large output to create different subsets. While you can recombine that, I never added a function to rename groups, which is what would be needed in this case. I'll leave this open as a reminder to add that.

**Comment by endrebak** [comment]
This would be brilliant.

My use case: we have RNA-Seq data and ChIP-Seq data for the same experiment. I want to sanity check that the genes with the highest expression are depleted for H3K27me3 for example, while enriched for phosphorylated PolII.

**Comment by endrebak** [comment]
Thanks for your answers.

1) Is there a way to modify my matrix file to include groups?

This is what it looks like:

```

zcat  data/compute_matrix/exon/tes/AAG_KO.mat.gz | cut -c -75 | head
@{"max threshold":null,"sort regions":"keep","nan after end":false,"sample_
chr1	6457265	6457274	exon:ENST00000416731.5:7	.	+	-4.049490	-4.049490	-2.96
chr11	67433443	67433447	exon:ENST00000531765.2:1	.	+	0.000000	0.000000	0.00
chr20	36229331	36229340	exon:ENST00000373941.5:21	.	+	0.000000	0.000000	0.0
chr17	49811565	49811574	exon:ENST00000509124.5:4	.	+	-0.484326	-0.484326	-0
chr11	65221160	65221164	exon:ENST00000534471.1:1	.	+	-0.846284	-0.846284	-0
chr12	9997159	9997163	exon:ENST00000398937.6:1	.	-	0.000000	0.000000	0.0000
chr11	65537023	65537029	exon:ENST00000279270.10:8	.	+	0.000000	0.000000	0.0
chr17	35510035	35510039	exon:ENST00000592908.1:2	.	-	-0.484326	-0.484326	-0
chr11	66423500	66423504	exon:ENST00000639555.1:5	.	+	-0.484326	-0.484326	-0
```

2) So if my bed file looks like this:

```
 head -3 data/annotation/gene/annotation.bed
chr1	11868	14409	ENSG00000223972.5	.	+
chr1	14403	29570	ENSG00000227232.5	.	-
chr1	17368	17436	ENSG00000278267.1	.	-
```

I'd change it to this:

```
 head -4 data/annotation/gene/annotation.bed
Chromosome Start End Name Score Strand deepTools_group
chr1	11868	14409	ENSG00000223972.5	.	+   0
chr1	14403	29570	ENSG00000227232.5	.	-   0
chr1	17368	17436	ENSG00000278267.1	.	-  75
```

The deepTools_group would then include the expression quintile of the gene.

3. If I create a matrix using different region files, would it then be possible to have a collective plot without groups afterwards?

Example: I create a matrix with five groups, the expression quintiles 0, 0-25, 25-50, 50-75, 75-100. I want to create two plots with this matrix: a profile plot with the five quintile groups and a profile plot with all the genes, without regards to group. Do I need two matrixes for this or just one?

4) Are the groups (regions) used in the heatmaps in any way?

**Comment by endrebak** [comment]
This is what following steffenheynes recipe produced. I am posting it here so others know what the bed should look like.

```
#chrom  start   end     name    score   strand  thickStart      thickEnd        itemRGB blockCount      blockSizes      blockStart      deepTools_group
chr1    1598011 1600096 ENSG00000228594.3       .       -       1598011 1600096 0       1       2085    1598010 cluster_1
chr1    1324755 1328897 ENSG00000224051.6       .       +       1324755 1328897 0       1       4142    1324754 cluster_1
chr1    1785284 1891117 ENSG00000078369.17      .       -       1785284 1891117 0       1       105833  1785283 cluster_2
chr1    2425979 2505530 ENSG00000149527.17      .       +       2425979 2505530 0       1       79551   2425977 cluster_2
chr1    1541672 1574869 ENSG00000160075.11      .       -       1541672 1574869 0       1       33197   1541671 cluster_2
chr1    214870733       214871716       ENSG00000185221.6       .       +       214870733       214871716       0       1       983     214870731       cluster_2
chr1    42570969        42571390        ENSG00000236180.2       .       +       42570969        42571390        0       1       421     42570965        cluster_2
```

@steffenheyne: Are the following columns needed?

    thickStart     thickEnd        itemRGB blockCount      blockSizes      blockStart

**Comment by steffenheyne** [comment]
no, these are not required. You can have `deepTools_group` eg. as 7th column. 
However, `computeMatrix` can make use of these columns with the option `--metagene`, see
http://deeptools.readthedocs.io/en/latest/content/tools/computeMatrix.html

**Comment by endrebak** [comment]
Wonderful, thanks.
