### ISSUE TITLE
plotly output for deepTools?

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#548]
This is just an idea I'm playing around with, but it might be cool if some of the tools could have a plotly output instead of static things like png or pdf. This might allow things like mouse-over for displaying label names in plotPCA or perhaps redoing kmeans clustering or other similar things for plotHeatmap.

 - [x] plotCorrelation
 - [x] plotCoverage
 - [x] plotEnrichment
 - [x] plotFingerprint
 - [x] plotHeatmap
 - [x] plotPCA
 - [x] plotProfile
 - [x] bamFragmentSize
 - [x] computeGCBias

And of course the requisite:

 - [x] Added to Galaxy
 - [x] Galaxy bamPEFragmentSize wrapper has no image format option
 - [x] Read the docs
 - [x] Mention file size and that some options are ignored in Galaxy

**Comment by endrebak** [comment]
Yes! Would be great for showing results to biologists.

**Comment by bgruening** [comment]
Cool idea!

**Comment by dpryan79** [comment]
Everything except plotHeatmap now has support for plotly output. I'm not sure if a plotly output for plotHeatmap will end up being feasible. plotly ends up producing web pages with the raw data in the plots integrated it, so the files quickly become large. As an example, for computeGCBias, I don't actually plot the raw data in the box plots, because that results in html files that are big enough to freeze a browser. Instead I calculate where everything should be in the box plot and make a vector with 9 values that will produce the same boxplot. That ends up cutting file sizes down to something reasonable.

Also, plotly seems to be causing problems on TravisCI. It looks like maybe there's a problem with the conda package related to [this](https://community.plot.ly/t/failure-at-the-first-hurdle-python-error-on-import-plotly/3331/5).

**Comment by dpryan79** [comment]
For what it's worth, a few of the plots are much more useful with plotly. An example is `plotCorrelation` with a scatterplot. I can't use an actual scatterplot (you end up with HUGE webpages), so I switched to a heatmap, which proved much more useful than what we're currently doing with the normal matplotlib output.

**Comment by dpryan79** [comment]
This is now in the `develop` branch and will appear in the 2.6 release. Note that plotly output for plotHeatmap is pretty big and seems to work better with chrome than firefox.
