### ISSUE TITLE
bigwigcompare best --ratio for shallow depth

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#553]
I have datasets from a ChIP-seq style nature where the pulldowns have nice peaks of coverage (top of the image) and for which some level of Input sequencing was done.

When using bigwigCompare with default `--ratio`, I get rather noisy "blocky" patterns that I presume may be due to the Input not having enough depth (see bottom part of the image). Negative values are shown in grey.

For an example like this, which of the `--ratio` types would be most adequate? If it's a matter of flagging out false peaks where there are artificial peaks of Input coverage, what would be the best type?

Thanks in advance

![screen shot 2017-07-04 at 13 50 21](https://user-images.githubusercontent.com/158007/27830754-c22d497c-60bf-11e7-9147-b91ffb40b0a5.png)

**Comment by dpryan79** [comment]
If you used `bamCompare` instead, you might try the `--smoothLength` option to just try to smooth over the noise a bit.

**Comment by avilella** [comment]
Brill, I will try that and report.

**Comment by dpryan79** [comment]
Sorry for the late reply to your question, no, at least I don't have any rules of thumb for the smoothing.
