### ISSUE TITLE
multiQC integration

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#554]
This is a long-standing internal request. It'd be nice to have multiQC modules that can take the text output from some of the tools and process them for plotting. Obvious choices would be bamPEFragmentSize and plotFingerprint. 

 - [x] bamPEFragmentSize (`--table`)
 - [x] estimateReadFiltering
 - [x] plotCoverage
 - [x] plotEnrichment
 - [x] plotFingerprint

I may whittle down the above list a bit still.

**Comment by vivekbhr** [comment]
This would need opening a PR for multiQC with some example outputs from deeptools modules

**Comment by dpryan79** [comment]
Yes, that's the idea. I'd just write the multiQC modules.

**Comment by dpryan79** [comment]
The support is now there for everything. I would like to play around with making grouped bargraphs rather than line plots for somethings (not sure that's possible).

**Comment by dpryan79** [comment]
- [ ] Try grouped bar graphs
- [ ] Ensure the plots are correct (mainly for plotFingerprint, which I'm not sure is correct yet).

**Comment by asalhab** [comment]
Hi @dpryan79 
is there any plan to add plotCorrelation, GCbias, plotPCA outputs to deeptools module? I already implemented deeptools modules for MultiQC sometime ago and I was waiting a little bit till I have it in the final shape I wanted and then submit a PR, but it seems you are faster :)
it has the following modules: 

- plotCorrelation
- plotPCA (scatter plot, eigenvalues, PCs contributions)
- plotFingerprint
- computeGCBias
- plotCoverage (coverage, cumulative)

an example of the output is here: https://drive.google.com/open?id=0B4L4_miTcGYlX3VhRUhrQXd0c0E
maybe my code  github https://github.com/asalhab/MultiQC/blob/master/multiqc/modules/deepTools/ can save time for you.
this was build based on deeptools 2.5.0.1 and MultiQC v1.dev0

**Comment by dpryan79** [comment]
@asalhab No, I don't have any plans to add those (well, plotFingerprint is already in my PR and plotCoverage is at least partly covered too). In version 2.6 I've added plotly output for all of the tools, so you can directly get interactive plots with that. Consequently, I only found it useful to add support for tools that are often run on subsets of data as part of pipelines (so one can combine multiple result sets).
