### ISSUE TITLE
Feature request: color assignment in plotPCA

### ISSUE THREAD

**Issue by romanhaa** [fidelram/deepTools#560]
The PCA plot can become a bit tedious to interpret when each sample has a different color, especially when they overlap (10+ samples). It would be helpful (and perhaps easy to implement) to make an option in the plotPCA function for color specification. I would imagine to submit a list which has the same length as the samples being plotted. This way I could color the samples based on the group they belong to.

Keep up the good work guys!

**Comment by dpryan79** [comment]
This is implemented in the `develop` branch and will be present in the 2.6 release. It'll be the `--colors` option.
