### ISSUE TITLE
multiBamSummary Error Reading in Header

### ISSUE THREAD

**Issue by AmyOlex** [fidelram/deepTools#561]
Hello,

I haven't used DeepTools in over a year and have just updated to the new version.  I'm trying to run the multiBamSummary on some TCGA BAM files, but I keep getting an error.  

Here is my command line:

>>multiBamSummary bins --bamfiles TCGA-E2-A155-01A-11D-A12B-09_IlluminaGA-DNASeq_exome_gdc_realn.bam -out ../gdc_bam_file_deeptool_results/test.npz --outRawCounts ../gdc_bam_file_deeptool_results/test.tab -p 20

Here is the Error:

[bwHdrRead] There was an error while reading in the header!
Traceback (most recent call last):
  File "/usr/bin/multiBamSummary", line 11, in <module>
    main(args)
  File "/usr/lib64/python2.7/site-packages/deeptools/multiBamSummary.py", line 224, in main
    num_reads_per_bin = c.run(allArgs=args)
  File "/usr/lib64/python2.7/site-packages/deeptools/countReadsPerBin.py", line 244, in run
    y = pyBigWig.open(x)

I have Python Version 2.7.5

I installed DeepTools using the following commands on my RHEL 7 Server:
>> sudo pip install --upgrade pip
>> sudo pip install deeptools

I tried to run on non-TCGA BAM files, but it gave the same error.  Please let me know what other information you need.

Thank you for your help.

**Comment by dpryan79** [comment]
Reindex the BAM files.

**Comment by dpryan79** [comment]
Feel free to reopen this if the issue still isn't resolved.
