### ISSUE TITLE
not a valid number of processors

### ISSUE THREAD

**Issue by MeHelmy** [fidelram/deepTools#562]
when I use this command 
`plotCoverage --bamfiles align_mem_sorted.bam -plotFileFormat pdf -o ./genome_covergae/figures/coverage  -T "my coverage" -v  -numberOfProcessors 10`

I have this error:

> argument --numberOfProcessors/-p: lotFileFormat is not a valid number of processors

why there is confusion between the format and number of process?!

**Update:**

my bad I used -numberOfProcessors  instead of --numberOfProcessors.  but the error message I think is misleading

**Comment by steffenheyne** [comment]
use double dash: --plotFileFormat pdf

**Comment by dpryan79** [comment]
The error message is produced by the python `argparse` module, there's nothing we can do about that.
