### ISSUE TITLE
interpretation of plotCoverage

### ISSUE THREAD

**Issue by MeHelmy** [fidelram/deepTools#563]
I have a question regarding the interpretation of the coverage graph from the ``` plotCoverage ```

according to the graph below 20% of the sampled bp have up to 15 overlapping reads. what about 100 or 90%  as shown in the figure should be up to 0 overlapping reads?!

or should it be 20% of the sampled bp have **at least** 15 overlapping reads

https://ibb.co/khMrh5

**Comment by dpryan79** [comment]
Yes, it should be "20% of the sampled bases have at least 15 overlapping alignments". Thanks for catching that error!

**Comment by dpryan79** [comment]
I've fixed the image in the `develop` branch.
