### ISSUE TITLE
omit graphical output for plot* tools 

### ISSUE THREAD

**Issue by steffenheyne** [fidelram/deepTools#571]
Thomas often asked for this and I have currently no exact overview about which tools already can omit the graphical output and only provide text table output (already in develop?). 

This is mainly for performance reasons if one runs a deepTools plot* tool with many (15...50..100..) samples. 
If performance is a no issue for a tool, we might keep it as it is.. 

Main candidate is plotCorrelation, but due to available line/point styles and readability etc also plotFingerprint, plotCoverage  and plotPCA could support text-only output. 

support in 2.6.0:

- [x] plotCorrelation
- [x] plotFingerprint
- [x] plotCoverage
- [x] plotPCA
- [x] plotProfile
- [x] plotHeatmap
- [x] plotEnrichment
- [x] bamPEFragmentSize

Any other tools need this?

**Comment by dpryan79** [comment]
I've updated your post with what's already covered. The only tool for which the image isn't yet optional in 2.6 is `plotCoverage`. I'll consider this the feature request for that.

**Comment by steffenheyne** [comment]
ah and bamPEFragmentSize ??? :-)

**Comment by dpryan79** [comment]
That one never required it, to my knowledge.

**Comment by steffenheyne** [comment]
yes ...I just thought of consistency reasons that it is also possible to just output the table and allow to omit the plot

**Comment by steffenheyne** [comment]
it partially fits here, but I can also open new issue:

Can we enhance "plotEnrichment --outRawCounts" text table output to print also the absolute total reads and feature read counts (in each output row), not just fraction/percentage

would help comparing results to eg. "samtools view -L my.bed my.bam " as it reports usually a bit less...

total read count in plotEnrichment is "accurate" or estimated? code looks like it is just all reads in bam...

**Comment by dpryan79** [comment]
It uses all reads, so it's exact.
