### ISSUE TITLE
bamPEFragmentSize could output the raw fragment metrics

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#572]
Or perhaps just what goes into the histogram, if we precompute that (I need to check). This was requested on the mailing list.

**Comment by steffenheyne** [comment]
is the number of histogram bins (not the genomic ones) fixed or is this like and auto-estimate? should we allow so imfluence on the histogram bins? could be useful  for the text output....also think of multiqc!?

**Comment by dpryan79** [comment]
There are already `--distanceBetweenBins` and `--binSize` options. Yeah, I'll need to give it a usable header if multiQC is going to be able to grok it.

**Comment by steffenheyne** [comment]
yes, this is to influence the sampling from the genome, what I meant is if there is any influence on the histogram bins in the profile for the output!

**Comment by dpryan79** [comment]
No, the bins are whatever they end up being.

**Comment by dpryan79** [comment]
I mean, you can plot the log and set a maximum, but that's it.

**Comment by dpryan79** [comment]
I'm adding `--table` and `--outRawCounts` options. The first will the metrics in tabular format to a file (rather than the more unstructured format to stdout). The second write a tsv (with a header line to make detection by multiQC easier) with columns, "fragment/read length", "occurences", "label". That can be easily loaded into R (`skip=1`).

**Comment by dpryan79** [comment]
This is now implemented (also in Galaxy) and documented in the `develop` branch.

**Comment by steffenheyne** [comment]
great! Could we have easily more stats in the text output like mean and  median fragment size? This would make picard a little bit less needed in our workflows...

We should check in detail which metrics from picard CollectInsertSizeMetrics we can easily reproduce...what do you think?

**Comment by dpryan79** [comment]
Sure, though I expect most of what Picard outputs that's useful is already being output.
