### ISSUE TITLE
multiBAMSummary does not support ordering

### ISSUE THREAD

**Issue by bgruening** [fidelram/deepTools#573]
The mask in Galaxy has a form to select multiple BAMs in a specific order, which makes sense in BuildMatrix but not in multiBAMSummary. Too much DRY here. This is a mental note for me to fix it.

https://github.com/fidelram/deepTools/blob/master/galaxy/wrapper/multiBamSummary.xml#L46

**Comment by dpryan79** [comment]
This was requested so people could have the proper order for downstream plotting.

**Comment by bgruening** [comment]
But it does not have any effect as I was told, at least not in multiBAMSummary.

**Comment by dpryan79** [comment]
I haven't heard any issues, so if there's an issue I'd rather just fix it.

**Comment by dpryan79** [comment]
I've just tested this and things like `plotCorrelation --whatToPlot scatterplot` obey the ordering.

**Comment by bgruening** [comment]
But this report was for multiBAMSummary. I need to get more information from the users.

**Comment by dpryan79** [comment]
Unless the user is either parsing the npz file (unlikely) or saving the raw counts (also unlikely) then the only way they could see the actual file order is with `plotCorrelation --whatToPlot scatterplot`, since the other plot methods would end up reordering the samples as appropriate.
