### ISSUE TITLE
Bug parsing output file name

### ISSUE THREAD

**Issue by hmontenegro** [fidelram/deepTools#576]
When using plotHeatmap I had a minor issue if the output filename had the pattern `.f`, e. g.:

`plotHeatmap -m ATAC.f.matrix.gz -out ATAC.f.pdf --colorMap=Blues`

Complained with:

```
fc-list: unrecognized option '--format=%{file}\n'
usage: fc-list [-vV?] [--verbose] [--version] [--help] [pattern] {element ...} 
List fonts matching [pattern]

  -v, --verbose        display status information while busy
  -V, --version        display font config version and exit
  -?, --help           display this help and exit
```
However, it did create the file. There were no complains when using as:

`plotHeatmap -m ATAC.f.matrix.gz -out ATAC.pdf --colorMap=Blues`

The pdf from both commnads is identical.

**Comment by dpryan79** [comment]
What version of matplotlib do you have installed? I just tried a random small matrix without issue:

    plotHeatmap -m computeMatrixOperations.mat.gz -out ~/ATAC.f.pdf --colorMap=Blues

That matrix is available [here](https://github.com/fidelram/deepTools/blob/master/deeptools/test/test_data/computeMatrixOperations.mat.gz). I'm using matplotlib version 2.0.2, so I wonder if this is a version dependent issue.

**Comment by hmontenegro** [comment]
Sorry, one of those inexplicable one-off problems. I am repeating the same commands (recovering them from history, so exactly same) and not getting the error / warning. 

Testing with your data or mine failed to repeat the problem, you may close the issue. Thanks for looking quickly at it, sorry again for the false alarm.

**Comment by dpryan79** [comment]
Weird, well I'm glad it's working for you now :)
