### ISSUE TITLE
something wrong with –-scaleFactor in bamCoverage  

### ISSUE THREAD

**Issue by Yuxuan0060** [fidelram/deepTools#580]
Hi, 

When I use bamCoverage without any normalization or scaleFactor ( bamCoverage -b input.bam -o output.bg -of bedgraph --ignoreDuplicates --minMappingQuality 30 --extendReads 200), I got the following output.
chr1	0	3000050	0
chr1	3000050	3000200	1
chr1	3000200	3000300	2
chr1	3000300	3000450	1
chr1	3000450	3000600	2
chr1	3000600	3000700	3
chr1	3000700	3000750	1
chr1	3000750	3000850	2
chr1	3000850	3000950	1
chr1	3000950	3001000	3

Then I tried normalize to 1X (bamCoverage -b input.bam -o output.bg -of bedgraph --ignoreDuplicates --minMappingQuality 30 --extendReads 200 --normalizeTo1x 215057000)
It worked well with the following output
chr1	0	3000050	0
chr1	3000050	3000200	0.393831
chr1	3000200	3000300	0.787662
chr1	3000300	3000450	0.393831
chr1	3000450	3000600	0.787662
chr1	3000600	3000700	1.18149
chr1	3000700	3000750	0.393831
chr1	3000750	3000850	0.787662
chr1	3000850	3000950	0.393831
chr1	3000950	3001000	1.18149

But when I use scaleFactor on top of that ( bamCoverage -b input.bam -o output.bg -of bedgraph --ignoreDuplicates --minMappingQuality 30 --extendReads 200 --normalizeTo1x 21505700 --scaleFactor 0.1. ), the values are not scaled and are the same as the values without any normalization. The output is as follows:
chr1	0	3000050	0
chr1	3000050	3000200	1
chr1	3000200	3000300	2
chr1	3000300	3000450	1
chr1	3000450	3000600	2
chr1	3000600	3000700	3
chr1	3000700	3000750	1
chr1	3000750	3000850	2
chr1	3000850	3000950	1
chr1	3000950	3001000	3

Why is it that?
Thank you.

**Comment by dpryan79** [comment]
--scaleFactor overrides --normalizeTo1x, so your third command should
result in values of 0, 0.1, 0.2, 0.1 and so on. In fact, that's exactly
what happens when I try this locally. What version are you using?

Devon

--
Devon Ryan, Ph.D.
Email: dpryan@dpryan.com
Data Manager/Bioinformatician
Max Planck Institute of Immunobiology and Epigenetics
Stübeweg 51
79108 Freiburg
Germany
<devon.ryan@dzne.de>

**Comment by Yuxuan0060** [comment]
Thank you for your reply. I am using version 2.4.3.  I tried it again without  --normalizeTo1x ( bamCoverage -b input.bam -o output.bg -of bedgraph --ignoreDuplicates --minMappingQuality 30 --extendReads 200 --scaleFactor 0.1) but the values are still not scaled. 
chr1	0	3000050	0
chr1	3000050	3000200	1
chr1	3000200	3000300	2
chr1	3000300	3000450	1
chr1	3000450	3000600	2
chr1	3000600	3000700	3
chr1	3000700	3000750	1
chr1	3000750	3000850	2
chr1	3000850	3000950	1
chr1	3000950	3001000	3
So is there anything wrong with –-scaleFactor of that version?  I will try the latest version to see if it can be fixed.
Thank you!

**Comment by Yuxuan0060** [comment]
Yes, version 2.5 works well.

**Comment by dpryan79** [comment]
Thanks for the update!
