### ISSUE TITLE
recommendation normalising set of bams into set of bigwig files

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#581]
I am reading the Read Coverage normalizations options page:
http://deeptools.readthedocs.io/en/latest/content/tools/bamCompare.html?highlight=normalizations#Read coverage normalization options

My user case is a collection of bam files each of a ChIP-seq like pulldown having different levels of sequencing. I would like to produce a set of bigwig files for these bam files so that they are normalized for sequencing coverage. After reading the documentation, I am in doubt as to which method to use. Should I use `–normalizeTo1x` or `–normalizeUsingRPKM`?

**Comment by dpryan79** [comment]
I find --normalizeTo1x to be more useful and I suggest that in cases like
this.

Devon

--
Devon Ryan, Ph.D.
Email: dpryan@dpryan.com
Data Manager/Bioinformatician
Max Planck Institute of Immunobiology and Epigenetics
Stübeweg 51
79108 Freiburg
Germany
<devon.ryan@dzne.de>
