### ISSUE TITLE
Have deeptools respect the TMPDIR-variable or have a --tmpdir flag?

### ISSUE THREAD

**Issue by endrebak** [fidelram/deepTools#584]
I am writing a pipeline which uses deeptools. I want to make it possible to set the tempdir for end users without them understanding anything about deeptools. However, since the only way to set the tempdir is through a config-file, this is not possible.

I see two solutions:

1) respect the TMPDIR shell variable
2) have a config flag that would let me set the tempdir

A hack would be to

3) create my own deeptools.cfg in the directory in which deeptools is run from and set the tmpdir  there. Dunno if deeptools tries to read the config file from the directory in which it is executed though? This is very hackish so it is an option I want to avoid.

This is a general problem in software engineering and not specific to deeptools: only having options configurable through config-files greatly reduces the reusability of any tool. Snakemake solved this problem beautifully by having a --config flag where you can list configuration options and set them on the command line. This lets you avoid adding many new flags to each tool, but still let you set any config flag from the cmd line. This is option number 4) and the best one as far as I can see.  Example:

```snakemake --config conf_var1=42 conf_var2="hello" tmpdir=/mtn/scratch/tmp```

**Comment by dpryan79** [comment]
DeepTools uses whatever python specifies as the temp directory (assuming people keep the default `tmp_dir: default` in the config file), which is set by a mixture of `TMPDIR` and so on environment variables.

**Comment by endrebak** [comment]
Thanks! Then Python does not respect my tmpdir... Will need to read up on how python handles tmpdirs. Will post a solution if I find one :)

**Comment by dpryan79** [comment]
Please do, I was recently trying to figure out which of the 4 or so environment variables python will use and the answer turned out to be "it's system dependent, set them all" :(

**Comment by kevinblighe** [comment]
Doing this on Ubuntu 16.04 seems to work at least:
```
TMPDIR="MyTemporaryDirectory/"
export TMPDIR
```
