### ISSUE TITLE
colors of "plot" in plotHeatmap function

### ISSUE THREAD

**Issue by gunjangala** [fidelram/deepTools#585]
Hello,
Is there a way to change the color of the "plot" that appears above heatmap while using plotHeatmap function? I tried different ```colorMap``` and ```colorList``` options but that just changed the colors in heatmap. I also noticed red/blue/green combination in one of your plots [here](http://deeptools.readthedocs.io/en/latest/content/example_gallery.html#normalized-chip-seq-signals-and-peak-regions). In my plots, there is yellow which makes it a little hard to visualize and would like to change it to some other color. 
Thanks,
Gunjan

**Comment by dpryan79** [comment]
That's currently hard-coded. If you need to change it, it's the line [here](https://github.com/fidelram/deepTools/blob/master/deeptools/plotHeatmap.py#L361). In general, if you want to tweak a profile plot then you'll have better luck using `plotProfile`.

**Comment by LeilyR** [comment]
I am facing a similar situation. I may consider adding this as an argument to be set by user.

**Comment by Oliverfeudj** [comment]
Hello @LeilyR and @dpryan79 
What solution have you adopted please? if any or we can't tweak the color of the plots above the heatmap?

Thank you for your answer

**Comment by VonAlphaBisZulu** [comment]
It would be great to port the --colors argument from plotProfile to plotHeatmap
