### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by tamerawwad** [fidelram/deepTools#587]
I am trying to install deeptools using pip, however I am getting the following error and I would like to know what is the problem actually:

$ pip install deeptools
Collecting deeptools
Collecting py2bit>=0.2.0 (from deeptools)
Collecting pyBigWig>=0.2.1 (from deeptools)
Collecting numpy>=1.9.0 (from deeptools)
  Using cached numpy-1.13.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: pysam>=0.8.2 in /Library/Python/2.7/site-packages (from deeptools)
Collecting matplotlib>=1.4.0 (from deeptools)
  Using cached matplotlib-2.0.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scipy>=0.17.0 (from deeptools)
  Using cached scipy-0.19.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpydoc>=0.5 (from deeptools)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from matplotlib>=1.4.0->deeptools)
Collecting functools32 (from matplotlib>=1.4.0->deeptools)
Requirement already satisfied: pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from matplotlib>=1.4.0->deeptools)
Collecting six>=1.10 (from matplotlib>=1.4.0->deeptools)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib>=1.4.0->deeptools)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting subprocess32 (from matplotlib>=1.4.0->deeptools)
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from matplotlib>=1.4.0->deeptools)
Collecting sphinx>=1.2.3 (from numpydoc>=0.5->deeptools)
  Using cached Sphinx-1.6.3-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from numpydoc>=0.5->deeptools)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached Babel-2.5.0-py2.py3-none-any.whl
Collecting typing; python_version < "3.5" (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached typing-3.6.2-py2-none-any.whl
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
Collecting requests>=2.0.0 (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting docutils>=0.11 (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached docutils-0.14-py2-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached alabaster-0.7.10-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting sphinxcontrib-websupport (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached sphinxcontrib_websupport-1.0.1-py2.py3-none-any.whl
Collecting imagesize (from sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached imagesize-0.7.1-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->numpydoc>=0.5->deeptools)
Collecting idna<2.7,>=2.5 (from requests>=2.0.0->sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.0.0->sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.0.0->sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->sphinx>=1.2.3->numpydoc>=0.5->deeptools)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: py2bit, pyBigWig, numpy, functools32, six, cycler, subprocess32, matplotlib, scipy, MarkupSafe, Jinja2, babel, typing, idna, urllib3, certifi, chardet, requests, docutils, alabaster, snowballstemmer, Pygments, sphinxcontrib-websupport, imagesize, sphinx, numpydoc, deeptools
  Found existing installation: numpy 1.8.0rc1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/14/4y3r94654g74qbsvym8s2t7m0000gn/T/pip-umhdUm-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'

**Comment by dpryan79** [comment]
For some reason `numpy` is causing a problem. I would recommend either installing `numpy` first and then deepTools or instead using conda, since deepTools is available in the bioconda channel.
