### ISSUE TITLE
bamCompare --scaleFactor console info

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#590]
I presume that "Normalization: depth" is still printed to the screen if one manually sets a `--scaleFactor`. A better method would be to just print whatever was specified by the user.

**Comment by vivekbhr** [comment]
As far as I saw, the scale factors would be multiplied by the `kept_reads/total_reads`, which in absence of blacklist would be 1, so `normalization: depth` is not correct there as well..

**Comment by dpryan79** [comment]
I think in `bamCompare` the scale factors override the depth normalization rather than getting multiplied by it (I'm double checking this now). But if not I totally agree that this needs to be fixed too.

**Comment by dpryan79** [comment]
Actually, it seems that "Normalization: depth" will only be printed with `bamCoverage`.

**Comment by dpryan79** [comment]
Gah, it's me who misread!

**Comment by dpryan79** [comment]
Hmm, it looks like "Normalization: none (signal scaled by percent alignment kept after filtering)" would be more appropriate. I added that in #366, so I guess I can take the initiative to change it.

**Comment by dpryan79** [comment]
@vivekbhr What's your opinion of the changed wording in [this commit](https://github.com/fidelram/deepTools/commit/6b788dd16abdfacee243ed687ea8898f239843ce)?

**Comment by vivekbhr** [comment]
Sounds ok to me.. Can also write : signal scaled by the `fraction` of alignment kept after filtering

**Comment by dpryan79** [comment]
@vivekbhr Sounds good, changed and merged :)
