### ISSUE TITLE
plotCoverage or BamCoverage doesnot work. Same Error !! Help!!

### ISSUE THREAD

**Issue by zusman** [fidelram/deepTools#591]
$ ./plotCoverage
Traceback (most recent call last):
  File "./plotCoverage", line 4, in <module>
    from deeptools.plotCoverage import main
ImportError: No module named deeptools.plotCoverage

$ ./bamCoverage --help
Traceback (most recent call last):
  File "./bamCoverage", line 4, in <module>
    from deeptools.bamCoverage import main
ImportError: No module named deeptools.bamCoverage

**Comment by dpryan79** [comment]
How did you install deepTools?

**Comment by dpryan79** [comment]
Feel free to reopen if it's still relevant.

**Comment by zusman** [comment]
I think deep tools is a package which works on many dependencies, despite deeptool installation it still gives this error..
Used sudo option during installation yet again when using plot coverage or bam coverage it displays this error..

**Comment by dpryan79** [comment]
`sudo` what though? Exactly what command did you issue to install it?

**Comment by hdharuri** [comment]
It looks like this issue has been closed, however I don't see a solution in the thread of messages. I am facing the same issue, can someone please comment on how this was resolved?

**Comment by dpryan79** [comment]
@hdharuri how did you install deepTools?

**Comment by hdharuri** [comment]
Thanks for getting back so quickly @dpryan79 . Yes, I did install deepTools and I just found out that the issue was with my python environment. Thanks once again for getting back so promptly.
