### ISSUE TITLE
Log2-transform bigwigs

### ISSUE THREAD

**Issue by endrebak** [fidelram/deepTools#592]
Before using bigwigs in a PCA plot I want to log2-transform them to avoid having regions with a high signal dominating. It would be useful to have the flag `--log2-transform` to be used in conjunction with `--normalizeUsingRPKM` in the bamCoverage script. Any chance you'll add this?

If not, can I do it with pyBigWig or some other tool?

Thanks.

**Comment by dpryan79** [comment]
I'd think a more convenient option would be to use `plotPCA --rowCenter`, which will 0-center the rows. Note that I've heavily revamped `plotPCA` for the 2.6 release (see the `develop` branch). I'd be happy to add a log2 option to `plotPCA` if it'd be useful.

**Comment by dpryan79** [comment]
I'll use this as an excuse to add a `--log2` option to `plotPCA` anyway, since I expect others have the same problem.

**Comment by dpryan79** [comment]
@endrebak Are you doing anything special with 0s when you log2? I planned to just add 0.01 to everything.

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch and will be in the 2.6 release.

**Comment by endrebak** [comment]
Yes, I also add a pseudocount. I am not a statistician though :)

**Comment by dpryan79** [comment]
> Yes, I also add a pseudocount. I am not a statistician though :)

My personal motto has long been "fake it 'till you make it."
