### ISSUE TITLE
computeGCBias doc issue?

### ISSUE THREAD

**Issue by mpi-pebert** [fidelram/deepTools#595]
Hi,
I am running `deepTools 2.5.3` and the `computeGCBias` command keeps failing asking for the `--fragmentLength` as additional parameter. The help says the frag length will be estimated given paired-end BAM files (yes, my BAM files are paired-end...) - problem with the docs or indeed problem in `computeGCBias`?
Best,
Peter

**Comment by dpryan79** [comment]
Indeed, the documentation is correct and the code is wrong for forcing you to specify it. I'll get this fixed for 2.6, thanks for pointing it out.

**Comment by dpryan79** [comment]
This is now fixed in `develop`. One no longer needs to specify a fragment length for PE datasets, instead the median fragment length from the file is used.
