### ISSUE TITLE
Formatting issue plotFingerprint / qual.metrics

### ISSUE THREAD

**Issue by mpi-pebert** [fidelram/deepTools#596]
Hi,
for `deepTools 2.5.3`, the quality metrics file of `plotFingerprint` contains a minor/ugly formatting issue:
```bash
Sample  AUC ...
[H3K27ac_1, 0.168068718464  ...
H3K27me3_1, 0.311867781307  ...
H3K36me3_1, 0.323477621852  ...
H3K4me1_1,  0.265763322287  ...
H3K4me3_1,  0.294727616325  ...
H3K9me3_1,  0.322187661557  ...
Input_1]    0.35945407455  
```
Note the commas and the `[ ]` around the labels. I used this tool last in version `2.5.0`, the output was fine back then.
Best,
Peter

**Comment by dpryan79** [comment]
That's really odd. What version of python are you using?

**Comment by mpi-pebert** [comment]
It's `Python 2.7.13` and `deepTools 2.5.3` set up via (Bio)Conda

**Comment by mpi-pebert** [comment]
Nevermind, I just realized that it's me who is passing the string representation of list instead of space-separated labels when assembling the command line to `plotFingerprint`. Closing this

**Comment by dpryan79** [comment]
OK, glad that got figured out.
