### ISSUE TITLE
bamCompare median cov zero error

### ISSUE THREAD

**Issue by mpi-pebert** [fidelram/deepTools#599]
Hi,
for `deepTools 2.5.3`, I get the following error from `bamCompare` for a couple of samples:
```bash
*ERROR*: The median coverage computed is zero for sample(s) #[1]
    Try selecting a larger sample size or a region with coverage
```
I am processing unfiltered BAM files (still contains duplicates etc.) for hg38. Any idea how to avoid that?
I can just tell you that this BAM file was processed (I assume, successfully) by `computeGCBias` and `plotFingerprint` w/o any error.
Best,
Peter

**Comment by dpryan79** [comment]
You must have been running `bamCompare` with SES normalization. If the coverage of the first file is too sparse then you'll get this sort of error. As indicated, try increasing `--sampleLength` and `--numberOfSamples`.

**Comment by mpi-pebert** [comment]
Ok, so in the `bamCompare` help where it says...
```
...to minimize the probability that zero-coverage regions are used.
```
This actually means that the regions won't be "used", but computation stops with this error, is that correct? So I misunderstood the docs, I'll proceed by adjusting the parameters, then. Thanks for the fast reply.

+Peter

**Comment by mpi-pebert** [comment]
- So for what it's worth, in case somebody else reads this, increasing the `--numberOfSamples` from default 100.000 to 500.000 and 1.000.000 did not help. Doubling the `--sampleLength` from 1.000 to 2.000 allowed to successfully process the data (H3K27ac)

- (Fixed title of issue from `bamCoverage` to `bamCompare`...)

Closing this now...
