### ISSUE TITLE
computeGCBias takes an extremely long time

### ISSUE THREAD

**Issue by c-guzman** [fidelram/deepTools#600]
I'm trying to run computeGCBias on a BAM file with approximately 24M reads. I'm running the latest version of deepTools on a cluster with 60 cores and ~70GB of RAM.

computeGCBias has been running for over 24 hours with all 60 cores on this BAM file and it still hasn't finished. This is in python2. I read a closed issue where it was suggested to use python3. Any ideas?

**Comment by dpryan79** [comment]
It's likely that one of the 60 forks died and python somehow didn't notice it. Try running it again.

**Comment by c-guzman** [comment]
I've figured out the issue. You  recommend including the repeat regions of the genome in the computeGCBias analysis, but the bed file is so huge that it causes problems.
