### ISSUE TITLE
Wrong link in help text: computeMatrix

### ISSUE THREAD

**Issue by joachimwolff** [fidelram/deepTools#601]
The help text of the wrapper computeMatrix contains a wrong link: 
In Line 273 of the [computeMatrix Galaxy wrapper](https://github.com/fidelram/deepTools/blob/master/galaxy/wrapper/computeMatrix.xml#L273)
it links to: 
file:///Users/frd2007/Documents/MPI/deepTools/docs/_build/html/content/tools/computeMatrix.html#details

instead to https://deeptools.readthedocs.io/en/latest/content/tools/computeMatrix.html.

**Comment by dpryan79** [comment]
Thanks @joachimwolff, I've fixed this for the 2.6 release (e.t.a. 2 weeks). Looks like this has been there for a while...
