### ISSUE TITLE
computeGCBias biasPlot y-axis

### ISSUE THREAD

**Issue by c-guzman** [fidelram/deepTools#604]
Is there anyway to set the y-axis for the biasPlot option? Some of the defaults make no sense ... such as setting a y-axis of 8 for a graph that doesn't really go over 2. Sometimes using floats instead of integers for no apparent reason, stuff like that.

Thanks!

**Comment by dpryan79** [comment]
Do you mean the log2 ratio plot (the one at the bottom)? I imagine that the issue is that the y-limits are set for the whole plot, but only what's between 0.2 and 0.7 are actually show.

**Comment by dpryan79** [comment]
I've fixed this for the 2.6 release.
