### ISSUE TITLE
RRPM calculation using deeptools

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#608]
Hi,

I am wondering if I can use deeptools to produce the Reference-adjusted Reads Per Million, RRPM given a pair of bam files from an enrichment experiment, one with the reads aligning to human and the other bam files with the reads aligning to the reference species (e.g. Drosophila).

From the paper: http://www.cell.com/action/showMethods?pii=S2211-1247%2814%2900872-9
A complete description of the basis and derivation of the ChIP-Rx normalization factor is provided in the Supplemental Experimental Procedures. In brief, we derived a normalization constant, α, such that after normalization the signal per-reference cell (β) is the same across all samples. The total ChIP-seq signal derived from reference cells is simply the count of reads (in millions) aligning to the Drosophila genome, which we represent as Nd. Because the percentage of reference cells as a fraction of the total number of cells is constant and we assume that the epigenome of the reference cells does not vary appreciably, we can derive α as

Math Eq
Because β is a constant, we can simply rewrite this as
Math Eq
or
Math Eq
multiplying the read counts by α produces a normalized read count in normalized RRPM.

**Comment by dpryan79** [comment]
Sure, you just end up manually specify the scaling factor. So you calculate it with the reference datasets and then just manually specify them for the non-reference datasets. You might need to specify `--verbose` for `bamCompare` to print out the final scaling factors it uses, I don't recall off-hand.
