### ISSUE TITLE
bamCorrelate in BED-file mode does not consider extended reads

### ISSUE THREAD

**Issue by fidelram** [fidelram/deepTools#61]
The computation of the number of reads overlapping with a BED region does not include reads that overlap with the region after being extended. The current implementation first identifies the reads that fall into a region (BED  or bin), then the reads are extended.

**Comment by dpryan79** [comment]
We should just document this and close the issue. Given blacklist regions, RNAseq datasets, and soon supporting GTF/BED12, getting all of the alignments that overlap a region after extension is often not desirable (not to mention that doing so makes everything single threaded per chromosome).

**Comment by fidelram** [comment]
Besides we are not extending reads by default any longer which alleviates this problem.
