### ISSUE TITLE
computeMatrixOperations cbind "ValueError: all the input array dimensions except for the concatenation axis must match exactly"

### ISSUE THREAD

**Issue by chiefcat** [fidelram/deepTools#610]
Hi guys,

I am getting an error when running the computeMatrixOperations.
Please find the error message as follow:

>   File "/Users/kylie_coding/miniconda3/envs/deeptools_env/bin/computeMatrixOperations", line 11, in <module>
    main(args)
  File "/Users/kylie_coding/miniconda3/envs/deeptools_env/lib/python3.5/site-packages/deeptools/computeMatrixOperations.py", line 677, in main
    cbindMatrices(hm, args)
  File "/Users/kylie_coding/miniconda3/envs/deeptools_env/lib/python3.5/site-packages/deeptools/computeMatrixOperations.py", line 408, in cbindMatrices
    hm.matrix.matrix = np.hstack((hm.matrix.matrix, np.empty(hm2.matrix.matrix.shape)))
  File "/Users/kylie_coding/miniconda3/envs/deeptools_env/lib/python3.5/site-packages/numpy/core/shape_base.py", line 293, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
(deeptools_env) 

The run was performed in an isolated enviroment
>   packages in environment at /Users/kylie_coding/miniconda3/envs/deeptools_env:
bcftools                  1.5                           3    bioconda
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py35_0    conda-forge
curl                      7.54.1                        0    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
deeptools                 2.5.3                    py35_0    bioconda
freetype                  2.7                           1    conda-forge
htslib                    1.5                           0    bioconda
krb5                      1.14.2                        0    conda-forge
libpng                    1.6.28                        0    conda-forge
libssh2                   1.8.0                         1    conda-forge
matplotlib                2.0.2                    py35_2    conda-forge
mkl                       2017.0.3                      0  
ncurses                   5.9                          10    conda-forge
numpy                     1.13.1                   py35_0  
openssl                   1.0.2l                        0    conda-forge
pip                       9.0.1                    py35_0    conda-forge
py2bit                    0.2.1                    py35_0    bioconda
pybigwig                  0.2.8                    py35_0    bioconda
pyparsing                 2.2.0                    py35_0    conda-forge
pysam                     0.12.0.1        py35_htslib1.5_1    bioconda
python                    3.5.4                         0    conda-forge
python-dateutil           2.3                      py35_0    bioconda
pytz                      2017.2                   py35_0    conda-forge
readline                  6.2                           0    conda-forge
samtools                  1.5                           1    bioconda
scipy                     0.19.1              np113py35_0  
setuptools                36.3.0                   py35_0    conda-forge
six                       1.11.0                   py35_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        2    conda-forge
tornado                   4.5.2                    py35_0    conda-forge
wheel                     0.30.0                     py_1    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
(deeptools_env)

I'm quite new in using command-line tools, therefore can't really figure out which part went wrong. Would you guys help on this? Thanks a lot!

**Comment by dpryan79** [comment]
If you're going to `cbind` to matrices then they need to have the same number of rows. If they don't, you'll get this error.

**Comment by chiefcat** [comment]
Hi Ryan,

Thank you for your prompt reply. I'm trying to sort ChIP-seq. signal by gene expression following the workflow suggested in [https://www.biostars.org/p/225831/].

bigwig files for ChIP were generated by `bamCompare`. However, those for RNA-seq. were generated by another package by my labmate.

I guess that the matrices did not have same no. of row would be caused by `--skipZeros` was used in the `computeMatrix` step, right?

Thanks!

**Comment by dpryan79** [comment]
That'd be a good guess.

**Comment by chiefcat** [comment]
Thanks Ryan,

I've re-run the `computeMatrix` without `--skipZeros` for all the seq. files. However, the same error message still came out during `computeMatrixOperations`.

Then, I separated the run into "RNA-seq. files only (2 files)" & "ChIP-seq. files only (4 files)". The `computeMatrixOperations` run was fine for the "ChIP-seq. files only" but not for the "RNA-seq. files only". As mentioned the bigwig for RNA-seq. was not generated by `bamCompare`. I am now guessing if the failure was originated from the bigwig files. 1) Is there anyway if I can check whether the bigwig files meet the requirement for deeptools? 2) Also, how could I make sure the bigwig for both RNA-seq. and ChIP-seq. are compatible if my goal is to combine them for `computeMatrixOperations`, `plotHeapmap` functions?

**Comment by dpryan79** [comment]
Can you post the matrices somewhere? My guess is that there are differences in the chromosomes in the bigwig files that’s causing differences in the output row number, which then makes things incompatible.

**Comment by chiefcat** [comment]
Hi Ryan,

How should I post the matrices or should I upload the matrix output file (.gz) somewhere? Thanks.

**Comment by dpryan79** [comment]
Just upload them somewhere (or if they're small then email them to me (dpryan79@gmail.com)).

**Comment by chiefcat** [comment]
Thanks Ryan,
I've done a simple check for the matrics. Your guess is right, the no. of chromosomes between the two RNA-seq. file is different as shown in the summary below. By the way, is it using the `bamCompare` or `bamCoverage` for bigwig generation is the most direct way to solve this chr. no. issue? 

  | RNA-seq | RNA-seq | ChIP-seq | ChIP-seq | ChIP-seq | ChIP-seq
-- | -- | -- | -- | -- | -- | --
  | Day0_01 | Day0_02 | T1_D0_J2b | T1_D0_K9 | T4_D0_J2b | T4_D0_K9
Row no. | 128706 | 128699 | 128718 | 128718 | 128718 | 128718
Chr. | 1 | 1 | 1 | 1 | 1 | 1
  | 2 | 2 | 2 | 2 | 2 | 2
  | X | X | X | X | X | X
  | 3 | 3 | 3 | 3 | 3 | 3
  | 4 | 4 | 4 | 4 | 4 | 4
  | 5 | 5 | 5 | 5 | 5 | 5
  | 6 | 6 | 6 | 6 | 6 | 6
  | 7 | 7 | 7 | 7 | 7 | 7
  | 10 | 10 | 10 | 10 | 10 | 10
  | 8 | 8 | 8 | 8 | 8 | 8
  | 14 | 14 | 14 | 14 | 14 | 14
  | 9 | 9 | 9 | 9 | 9 | 9
  | 11 | 11 | 11 | 11 | 11 | 11
  | 13 | 13 | 13 | 13 | 13 | 13
  | 12 | 12 | 12 | 12 | 12 | 12
  | 15 | 15 | 15 | 15 | 15 | 15
  | 16 | 16 | 16 | 16 | 16 | 16
  | 17 | 17 | 17 | 17 | 17 | 17
  | Y | Y | Y | Y | Y | Y
  | 18 | 18 | 18 | 18 | 18 | 18
  | 19 | 19 | 19 | 19 | 19 | 19
  | MT | MT | MT | MT | MT | MT
  | JH584299.1 | JH584299.1 | JH584299.1 | JH584299.1 | JH584299.1 | JH584299.1
  | GL456233.1 | GL456233.1 | GL456233.1 | GL456233.1 | GL456233.1 | GL456233.1
  | GL456211.1 | GL456211.1 | GL456211.1 | GL456211.1 | GL456211.1 | GL456211.1
  | GL456350.1 | GL456350.1 | GL456350.1 | GL456350.1 | GL456350.1 | GL456350.1
  | JH584293.1 | JH584293.1 | JH584293.1 | JH584293.1 | JH584293.1 | JH584293.1
  | GL456221.1 | GL456221.1 | GL456221.1 | GL456221.1 | GL456221.1 | GL456221.1
  | JH584297.1 | JH584297.1 | JH584297.1 | JH584297.1 | JH584297.1 | JH584297.1
  | JH584296.1 | JH584296.1 | JH584296.1 | JH584296.1 | JH584296.1 | JH584296.1
  | JH584294.1 | JH584294.1 | GL456354.1 | GL456354.1 | GL456354.1 | GL456354.1
  | JH584298.1 | JH584298.1 | JH584294.1 | JH584294.1 | JH584294.1 | JH584294.1
  | GL456219.1 | GL456210.1 | JH584298.1 | JH584298.1 | JH584298.1 | JH584298.1
  | GL456210.1 | GL456212.1 | GL456219.1 | GL456219.1 | GL456219.1 | GL456219.1
  | GL456212.1 | JH584304.1 | GL456210.1 | GL456210.1 | GL456210.1 | GL456210.1
  | JH584304.1 | GL456216.1 | JH584303.1 | JH584303.1 | JH584303.1 | JH584303.1
  | GL456216.1 | JH584295.1 | GL456212.1 | GL456212.1 | GL456212.1 | GL456212.1
  | JH584292.1 | JH584304.1 | JH584304.1 | JH584304.1 | JH584304.1
  | JH584295.1 | GL456216.1 | GL456216.1 | GL456216.1 | GL456216.1
  |   |   | GL456239.1 | GL456239.1 | GL456239.1 | GL456239.1
  |   |   | GL456385.1 | GL456385.1 | GL456385.1 | GL456385.1
  |   |   | GL456372.1 | GL456372.1 | GL456372.1 | GL456372.1
  |   |   | GL456381.1 | GL456381.1 | GL456381.1 | GL456381.1
  |   |   | JH584292.1 | JH584292.1 | JH584292.1 | JH584292.1
  |   |   | JH584295.1 | JH584295.1 | JH584295.1 | JH584295.1

**Comment by dpryan79** [comment]
Truth be told, the easiest way is to just remove the non-common chromosomes from the BED/GTF file(s) you're using with `computeMatrix`. Then you should have the same regions at the end and everything should `cbind` properly.
