### ISSUE TITLE
Are the deeptools_Groups in profileplots divided by group size or is the sum used?

### ISSUE THREAD

**Issue by endrebak** [fidelram/deepTools#620]
I am guessing the first, otherwise you might consider implementing the latter :)

**Comment by vivekbhr** [comment]
Didn't get the question.. The deeptools_Group comes either from clustering or is defined by you.. do you mean which order do the groups appear as lines in the profile plot?

**Comment by endrebak** [comment]
The y-value of the lines is decided by the signal in the respective groups. If some groups have more elements than others they will have a higher summed signal even though the average signal is the same.

**Comment by endrebak** [comment]
Here you see two groups:

![0f97ce0c-f6b6-4290-a7ce-616adc74c22e](https://user-images.githubusercontent.com/17778898/32019406-6002b90a-b9cd-11e7-8dfc-54e167468cc3.jpeg)

If the red group has twice as many members (lines in the bed region file), but the average signal for the red and the green groups are the same, the end result might look like the above. However if the values were normalized by group size they should be equal. 

Sorry for the crappy drawing. I do not have any paint programs on my iPhone so I used the built in screenshot-editing capabilities.

**Comment by dpryan79** [comment]
The `--averageType sum`/`--averageTypeSummaryPlot sum` options do a simple sum. I don't think we'd ever conceived of anyone using them for multiple groups for exactly the reason you mentioned. I'm not sure we can reasonably implement such a function, since the summary function is only aware of a single group of data within a single sample.

**Comment by endrebak** [comment]
But in the profileplots, you show the average right, not the sum? I am wondering if the profileplots are normalized by group size. This could be something to add to the docs.

**Comment by endrebak** [comment]
I have five groups in my region file: 0 expression, 0-25% expression, 25-50% expression etc. The 0 group is much larger than the others. I want to know whether this is adjusted for in the profileplots. Sorry for being so hard to understand.

**Comment by dpryan79** [comment]
By default we show the average, which means that no normalization is needed. If one chooses to show the sum and had multiple groups then such a normalization could be useful.
