### ISSUE TITLE
multiheatmapper: gene length is not drawn, NaN after region end does not work

### ISSUE THREAD

**Issue by friedue** [fidelram/deepTools#64]
Hi,

there are two related issues with the multiheatmapper:

1. the option --sort region_length does lead to regions sorted by the length, but the end of the region is not indicated by a dashed line as it is the case for the original heatmapper

2. the computeMatrix option --nanAfterEnd does not work for more than one heatmap - well, it works rather too thoroughly as you can see:
![multiheatmapper_nanafterend](https://cloud.githubusercontent.com/assets/4973546/4823385/b3ad0100-5f4e-11e4-8a8b-7efe41694d34.png)

**Comment by fidelram** [comment]
Issue solved. Now heatmapper (multiheatmapper branch) plots nanAfter end and plots the border of the regions (usually genes) if they are sorted by gene length.

<img src="https://cloud.githubusercontent.com/assets/4964309/6919285/1de31124-d7b6-11e4-8b3f-fe62c81f82ae.png" alt="Drawing" height="500"/>

<img src="https://cloud.githubusercontent.com/assets/4964309/6919292/2c371f7c-d7b6-11e4-8d17-4445f5f1e809.png" alt="Drawing" height="500"/>
