### ISSUE TITLE
 Deeptools compGCbias can't handle different chromosome names

### ISSUE THREAD

**Issue by vivekbhr** [fidelram/deepTools#65]
command for computeGC: /script/computeGCbias --genome mm9 

Error:
Bam and 2bit do not have matching chromosome names:
2bit:['1', '3', '2', '5', '4', '7', '6', '9', '8', 'Y', 'X', '11', '10', '13', '12', '15', '14', '17', '16', '19', '18', 'MT']

bam:('chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chrX', 'chrY')

**Comment by dpryan79** [comment]
@vivekbhr: Can you check and see if this is still an issue?

**Comment by dpryan79** [comment]
I can confirm that this is still an issue.

**Comment by dpryan79** [comment]
This means the correctGCbias also can't handle differing names

**Comment by fidelram** [comment]
Although we can fix the by adding or removing internally a prefix in the chromosome names (as we do in other tools), the workaround is simple. I don't think is a bug.

**Comment by dpryan79** [comment]
There will always be edge cases of this, but most of them should be covered by #243
