### ISSUE TITLE
computeGCBias returns "ValueError: The first argument cannot be empty" on test_corrGC dataset

### ISSUE THREAD

**Issue by benjasriga** [fidelram/deepTools#70]
Dear Developers,
I was troubleshooting the issue on my own bam files when I decided to try it on your test dataset. The same error message is returned on your test dataset.

# deepTools test directory
/home/benjamir/bin/deepTools-master/deeptools/test/test_corrGC
# computeGCBias version
computeGCBias 1.5.9.1
# python version
Python 2.7.3 -- EPD 7.3-2 (64-bit)
# command invoked
/home/benjamir/bin/deepTools-master/bin/computeGCBias --bamfile test.bam --biasPlot test.pdf --GCbiasFrequenciesFile test.txt --verbose --effectiveGenomeSize 990 --genome sequence.2bit --numberOfProcessors 1 --fragmentLength 200
# output
Bam and 2bit do not have matching chromosome names:
2bit:['chr2L']

bam:('2L',)

Adding 'chr' seems to solve the problem. Continuing ...reads_per_bp: 0.20303030303
genome_size: 1000
total_reads: 201
filter_out: None
2bit: sequence.2bit
extra_sampling_file: None
min_reads: 0.0
bam: test.bam
max_reads: 237.0
computing frequencies
[0.000] computing positions to sample
[0.432] caching reads
[0.669] finish caching reads.
MainProcess processing 0 (0.0 per sec) @ chr2L:0-1970149 1
MainProcess processing 801 (44215.1 per sec) @ chr2L:0-1970149 1
MainProcess total time 0.7 @ chr2L:0-1970149 1
[0.000] computing positions to sample
[0.432] caching reads
Traceback (most recent call last):
  File "/home/benjamir/bin/deepTools-master/bin/computeGCBias", line 814, in <module>
    main(args)
  File "/home/benjamir/bin/deepTools-master/bin/computeGCBias", line 730, in main
    region=args.region)
  File "/home/benjamir/bin/deepTools-master/bin/computeGCBias", line 472, in tabulateGCcontent
    region=region)
  File "/home/benjamir/.local/lib/python2.7/site-packages/lib/python2.7/site-packages/deeptools/mapReduce.py", line 118, in mapReduce
    res = map(func, TASKS)
  File "/home/benjamir/bin/deepTools-master/bin/computeGCBias", line 271, in tabulateGCcontent_wrapper
    return tabulateGCcontent_worker(*args)
  File "/home/benjamir/bin/deepTools-master/bin/computeGCBias", line 375, in tabulateGCcontent_worker
    minlength=end_pos - start_pos + 2)
ValueError: The first argument cannot be empty.

I am using deeptools on a cluster running RHEL 6. Another observation, possibly related, computeGCBias required a fragment length be specified when I gave it paired-end bam files (all reads properly paired).

Thanks,
Ben

**Comment by fidelram** [comment]
I tried the exact same command and I don't get the error. Which version of numpy and scipy do you have installed?

The fragment length is used for not properly paired cases. If in you data, all reads are properly paired, then this value will have no effect.

**Comment by benjasriga** [comment]
Thanks for your response.
I load numpy and scipy as modules on our cluster so I had never looked at them critically there before.

scipy 0.10.1
numpy 1.6.1
These appear to be from 2012 or earlier. Yikes.
Do you recommend I install my own updated versions?

Thanks,
Ben


On Jan 29, 2015, at 3:11 AM, Fidel Ramirez <notifications@github.com<mailto:notifications@github.com>>
 wrote:


I tried the exact same command and I don't get the error. Which version of numpy and scipy do you have installed?

The fragment length is used for not properly paired cases. If in you data, all reads are properly paired, then this value will have no effect.

**Comment by fidelram** [comment]
Are you using python 2.7?

In principle the requirements from deepTools are:

    "numpy >= 1.6.2",
      "scipy >= 0.10.0",
        "matplotlib >= 1.2",
        "pysam >= 0.7.7",
        "bx-python >= 0.5.0",

so you can try to update numpy.

Meanwhile, have you tried our deeptools galaxy instance (deeptools.ie-freiburg.mpg.de)

**Comment by benjasriga** [comment]
I am using Python 2.7.3 |EPD 7.3-2.
The only package whose version number meets that list of requirements on my cluster is bx-python.
I put in a request to update numpy and scipy.

Thanks for the suggesting the galaxy instance. Unfortunately I have no experience using galaxy and no one in my group does either.

I guess the appropriate thing is to close this issue until such a time I can meet the list of requirements.

Thank you so much for your help and your time.

Ben


On Jan 29, 2015, at 9:54 AM, Fidel Ramirez <notifications@github.com<mailto:notifications@github.com>>
 wrote:


Are you using python 2.7?

In principle the requirements from deepTools are:

"numpy >= 1.6.2",
  "scipy >= 0.10.0",
    "matplotlib >= 1.2",
    "pysam >= 0.7.7",
    "bx-python >= 0.5.0",


so you can try to update numpy.

Meanwhile, have you tried our deeptools galaxy instance (deeptools.ie-freiburg.mpg.de<http://deeptools.ie-freiburg.mpg.de>)
