### ISSUE TITLE
bamCorrelate: gtf as --BED-file input

### ISSUE THREAD

**Issue by adomingues** [fidelram/deepTools#71]
Is possible to use a GTF file as an argument for the bamCorrelate?

The reason that I am asking, is that frequently gene annotations come in that format. For instance, I am comparing bams form 2 sequencing runs mapped with the same GTF. I would make sense to use that GTF for the comparison of the sequencing runs.

Of course I can easily convert the GTF in bed, but what is the fun in that? :)

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch, which will become the 2.3 release.
