### ISSUE TITLE
ComputeMatrix galaxy wrapper does not properly catch some errors

### ISSUE THREAD

**Issue by lparsons** [fidelram/deepTools#73]
When running the computeMatrix tool in Galaxy, if the regionSize is not set to a multiple of binSize, an error occurs, but the dataset shows up as OK (green) in the history instead of indicating an error:

    The --regionBodyLength has to be a multiple of --binSize. Currently the values are 75 10 for regionsBodyLength and binSize respectively

Also, it would be good to indicate this restriction in the help text for regionBodyLength in the Galaxy wrapper so users are aware before running.

**Comment by bgruening** [comment]
Hi @lparsons thanks for your bug report, I will fix this as soon as possible.

**Comment by dpryan79** [comment]
This is fixed in the version 2.0 wrappers.
