### ISSUE TITLE
add possibility to use bed12 or gtf to construct metagene heatmap and profile

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#76]
add the possibility to join all the exons for construct transcript genebody with RNA-seq data

**Comment by fidelram** [comment]
Commit 738a840069e8435625874b48dee3b1244b2c50e1 initially address the issue by using a custom bed file reader. This is just one step into the solution of the issue.

**Comment by dpryan79** [comment]
It turns out that a side-effect of implementing this (I'm working on it and #71 now) will be to largely get rid of bx-python. That'll then make #237 easier :)

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch, which will become the 2.3 release.
