### ISSUE TITLE
add RNA-seq bam files processing

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#77]
you could add an option to BamCoverage to use CIGAR code "N" to split reads in order not to loose intron information in the bigwig coverage file

and

you could add an option to computeMatrix in order to use a gtf file or a bed12 file to remove intronic regions

**Comment by fidelram** [comment]
the release 1.6 branch can already understan split reads.

The option to use a gtf file or a bed12 file is still needed.
