### ISSUE TITLE
bamCompare should have an option to save scaled versions of the bam files

### ISSUE THREAD

**Issue by fidelram** [fidelram/deepTools#78]
(request submitted by a user) Instead of only saving the ratio (diff, log2ratio etc.), bamCompare additionally should output two bigwig files with the respective scaling factors applied.

**Comment by morganeTC** [comment]
Hello,
Indeed, we would like to normalize a ChIP and an input signal with the SES
method and directly obtain 2  bigwig files with scaled signals (without performing any operation).

This would be a huge plus for us !

**Comment by dpryan79** [comment]
This will now appear in the 2.3 release. There, one can use `--ratio first` or `--ratio second` to have the scaled signal from the first or second file output.
