### ISSUE TITLE
add possibility to filter the strand of RNA-seq to plot profile

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#79]
Hi,

I think a good idea is to allow us to separate forward and reverse reads. 

RNA-seq protocol is sense specific. For example, RNA polymerase produces divergent transcripts (sense and anti-sense reads) on TSS. It would be nice to be able to plot sense reads of a given gene and additionally its anti-sense reads.

To allow us to see that kind of profile it would be interesting to separate reads dependent on their strand and make a matrix with 3 different options : 
- same strand of features
- opposite strand of feature
- both strands

To do that, I think a good approach is to separate reads with bamCoverage algorithm to create "sample. .Forward.bw" and "sample.Reverse.bw". Then use computeMatrix with the one of the 3 options above. Now for the option "both strand" we use only one BigWig but for the other 2 the program has to use two BigWig (Forward and Reverse) to compute the matrix.

I hope I am clear and I thank you in advance.

**Comment by fidelram** [comment]
Hi,

What you are suggesting is part of the release 1.6 branch of deepTools. For bamCoverage and bamCompare now you can filter reads based on sam flag which allows you to select forward or reverse reads. 

Moreover, the 1.6 branch understands split reads that are important for RNAseq data. 

Be aware that the documentation for release 1.6 is not yet ready and Galaxy wrappers are missing. 

Best,

Fidel 


Fidel Ramírez

**Comment by lelouar** [comment]
Hi,

I just wonder if this issue was good understood (sorry for the delay).

What I want at the end is to have two matrix : 

1) matrix with forward read for forward features and reverse reads for reverse features (option: same strand)
2) matrix with forward read for reverse features and reverse reads for forward features (option: opposite strand)

Now, to do this I have to:
1) separate the feature based on their strand (feature.bed => feature.forward.bed + feature.reverse.bed)
2) computeCoverage for forward reads and reverse reads (reads.bam => read.forward.bw + reads.reverse.bw)
3) computeMatrix for:
   a) feature.forward.bed and read.forward.bw
   b) feature.reverse.bed and read.reverse.bw
   c) feature.forward.bed and read.reverse.bw
   d) feature.reverse.bed and read.forward.bw
4) Merge a+b and c+d

I can also make two matrix with only one bed file, then split them depending on the strand of the features in the bed file and finally merge them to have my result. 

My issue was opened to allow users to do this process in an easier way.

Have I missed something in the doc to do this more easily ? I'm sorry if it's the case.

thx a lot,
Raoul RAFFEL

**Comment by dpryan79** [comment]
The general procedure you outlined is generally how this would work and we don't intend to change that. The `computeMatrixOperations` tool that will be in the 2.4 release should make most of this simpler (i.e., no one needs custom code any more).

**Comment by lelouar** [comment]
ok, I see ;) thx
