### ISSUE TITLE
duplicate colors in bamFingerprint

### ISSUE THREAD

**Issue by pkhoueiry** [fidelram/deepTools#80]
Hi all,
When running bamFingerprint for more than 7 samples, we start getting the same colors again which render the analysis of replicates very confusing. Could it be possible to extend the color set or to allow the user to specify them ?
Thanks

**Comment by fidelram** [comment]
There are some ways to change this behaviour:

 * Find the matplotlibrc file and edit the line called axes.color_cycle 
 * Optionally the deepTools/bin/bamFingerprint code  can be changed as follows:
 
```python
import matplotlib as mpl
# Set the default color cycle
mpl.rcParams['axes.color_cycle'] = ['red', 'blue', 'green', 'orange'... etc]
```

It is not complicated to add a new parameter to the bamFingerprint to reflect this but I don't know if that is the best approach. The more colors the more difficult  is to match them with the legend and the legend also may grow too much.

I will like to hear alternative ideas if there are some.

**Comment by pkhoueiry** [comment]
Thanks for you fast reply,
I agree, but the number of samples is not limited and thus the legend is growing anyhow. 
What about alternating between full and dashed lines by keeping 7 colors or so. Like that you will have 14 distinguishable lines.
I will add colors locally for my purpose,
Thanks,

**Comment by fidelram** [comment]
I like the idea of alternating line types. I will implement that.

**Comment by dpryan79** [comment]
This is now implemented in `develop` and will appear in the version 2.2.0.
