### ISSUE TITLE
I have bedgraphToBigWig on my path, but bamCoverage always complains

### ISSUE THREAD

**Issue by crazyhottommy** [fidelram/deepTools#81]
How can I resolve this?
######################################################

The program *bedGraphToBigWig* was not found in your PATH. In
order for deeptools to work properly this program needs
to be installed. If you already have a copy of this
program please be sure that it is found in your PATH or
that is referred in the configuration file of deepTools
located at:

/Library/Python/2.7/site-packages/deeptools/config/deeptools.cfg

The program can be downloaded from here:
  http://hgdownload.cse.ucsc.edu/admin/exe/

#################################

in my .bashrc file, I have:
#### add the UCSC utilities into path https://github.com/ENCODE-DCC/kentUtils
export  PATH=$PATH:/usr/local/bin/kentUtils/linux.x86_64

Thank you!

**Comment by bgruening** [comment]
Hi,

actually this should work. Can you double check the binary
'bedGraphToBigWig' is included in /usr/local/bin/kentUtils/linux.x86_64
and is executable? Moreover, relead/restart your bash after you edit
.bashrc.

Hope this helps,
Bjoern

Am 29.05.2015 um 23:28 schrieb Ming Tang:

**Comment by crazyhottommy** [comment]
it looks like I did not have ucsc utilities installed correctly...

Thanks!
