### ISSUE TITLE
Galaxy toolshed deepTools fails due to bad dependencies

### ISSUE THREAD

**Issue by Unode** [fidelram/deepTools#84]
Hi everyone,

I'm not sure this is the most appropriate location for this but here goes:

The latest available version of deeptools on the [official toolshed](https://toolshed.g2.bx.psu.edu/view/bgruening/deeptools/3a2aab18a217) is almost 1 year old.

This wouldn't be a problem by itself but on newer systems, one of the dependencies (package_atlas) is failing with the following traceback:

    Fatal error: Exit code 1 ()
    Traceback (most recent call last):
      File "/GALAXY/galaxy_dist/tool_dependencies/deepTools/1.5.9.1/bgruening/deeptools/3a2aab18a217/bin/bamCorrelate", line 12, in <module>
        from scipy.stats import pearsonr, spearmanr
      File "/GALAXY/galaxy_dist/tool_dependencies/scipy/0.12.0/iuc/package_scipy_0_12/20d1dd0220d7/lib/python/scipy/stats/init.py", line 320, in <module>
        from .stats import *
      File "/GALAXY/galaxy_dist/tool_dependencies/scipy/0.12.0/iuc/package_scipy_0_12/20d1dd0220d7/lib/python/scipy/stats/stats.py", line 241, in <module>
        import scipy.special as special
      File "/GALAXY/galaxy_dist/tool_dependencies/scipy/0.12.0/iuc/package_scipy_0_12/20d1dd0220d7/lib/python/scipy/special/init.py", line 529, in <module>
        from ._ufuncs import *
    ImportError: /GALAXY/galaxy_dist/tool_dependencies/atlas/3.10.2/iuc/package_atlas_3_10/37ff27ea37ed/lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /GALAXY/galaxy_dist/tool_dependencies/scipy/0.12.0/iuc/package_scipy_0_12/20d1dd0220d7/lib/python/scipy/special/_ufuncs.so)
    
The problem of package_atlas is supposed to have been fixed [upstream](https://toolshed.g2.bx.psu.edu/repository/view_changeset?ctx_str=b36c9ee883e9&id=160ece1b639a6b45) but deepTools still points to the older version.

Would it be possible to update the deepTools toolshed repository to fix this problem?

Thanks

**Comment by bgruening** [comment]
@Unode are you sure this is not related to this error: https://github.com/galaxyproject/tools-iuc/issues/190
Galaxy has only one installable revision for packages. This means if you install atlas from the TS or deeptools it should get the latest version of atlas (with the additional export).

**Comment by Unode** [comment]
I'm pretty sure it's the same problem. But I thought the commit I linked before was enough to fix it.
Seems it wasn't... I'll leave this open and monitor the other one too since deeptools will have to update once atlas is fixed.

Thanks and sorry for the trouble.

**Comment by bgruening** [comment]
@Unode nothing to be sorry about. The atlas problems are really hard to fix. I guess we will discuss this at GCC in more detail. But to get back to my previous statement; if a `tool_dependency` is updated the tools does not need to be updated it should always take the latest (and the only one) that is installed.

**Comment by Unode** [comment]
@bgruening I wasn't sure about `tool_dependency`. Had some buggy issues in the past with updating `packages_*`. I'll try it out again when atlas is fixed upstream.
Thanks

**Comment by dpryan79** [comment]
This works in the 2.0 version, closing.
