### ISSUE TITLE
bamCorrelate BED-file np.isinfinite error

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#86]
I am trying to run bamCorrelate for a collection of bams, but it gives me the following error below. Any ideas?
```
# bamCorrelate BED-file  --BED /data/annotations/hg38.cpgIslandExt.edited.sorted.nochr.bed  --bamfiles  /data/HB_n_B_Rep1-26094141/HB-n-B-Rep1_S5_L001_R1_001.bam /data/HB_n_B_Rep2-26116098/HB-n-B-Rep2_S6_L001_R1_001.bam /data/NB_n_B_Rep2-26097143/NB-n-B-Rep2_S10_L001_R1_001.bam /data/NB_n_B_Rep1-26098136/NB-n-B-Rep1_S9_L001_R1_001.bam /data/NB_n_C_Rep1-26098137/NB-n-C-Rep1_S11_L001_R1_001.bam /data/NB_n_C_Rep2-26110110/NB-n-C-Rep2_S12_L001_R1_001.bam /data/HB_n_C_Rep2-26093166/HB-n-C-Rep2_S8_L001_R1_001.bam /data/HB_n_C_Rep1-26095144/HB-n-C-Rep1_S7_L001_R1_001.bam /data/HBxC_Rep1-26099135/HB-TS-C-Rep1_S1_L001_R1_001.bam /data/HBxC_Rep2-26097142/HB-TS-C-Rep2_S2_L001_R1_001.bam /data/NBxC_Rep2-26092162/NB-TS-C-Rep2_S4_L001_R1_001.bam /data/NBxC_Rep1-26091203/NB-TS-C-Rep1_S3_L001_R1_001.bam  --labels  HB_n_B_Rep1 HB_n_B_Rep2 NB_n_B_Rep2 NB_n_B_Rep1 NB_n_C_Rep1 NB_n_C_Rep2 HB_n_C_Rep2 HB_n_C_Rep1 HBxC_Rep1 HBxC_Rep2 NBxC_Rep2 NBxC_Rep1  --binSize 1000 --corMethod spearman -f 200  --colorMap Reds --zMin 0.5 --zMax 1  -o /data//bamCorrelate.correlation_spearman.pdf
Number of non zero bins found: 27243
Traceback (most recent call last):
  File "/opt/python/2.7.3/bin//bamCorrelate", line 435, in <module>
    main(ARGS)
  File "/opt/python/2.7.3/bin//bamCorrelate", line 431, in main
    plot_title=args.plotTitle)
  File "/opt/python/2.7.3/lib/python2.7/site-packages/deeptools/correlation_heatmap.py", line 94, in plot_correlation
    cobar = plt.colorbar(img_mat, cax=axcolor, orientation='horizontal')
  File "/opt/python/2.7.3/lib/python2.7/site-packages/matplotlib-1.4.0-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 2154, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
  File "/opt/python/2.7.3/lib/python2.7/site-packages/matplotlib-1.4.0-py2.7-linux-x86_64.egg/matplotlib/figure.py", line 1500, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **kw)
  File "/opt/python/2.7.3/lib/python2.7/site-packages/matplotlib-1.4.0-py2.7-linux-x86_64.egg/matplotlib/colorbar.py", line 1316, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/opt/python/2.7.3/lib/python2.7/site-packages/matplotlib-1.4.0-py2.7-linux-x86_64.egg/matplotlib/colorbar.py", line 892, in __init__
    ColorbarBase.__init__(self, ax, **kw)
  File "/opt/python/2.7.3/lib/python2.7/site-packages/matplotlib-1.4.0-py2.7-linux-x86_64.egg/matplotlib/colorbar.py", line 321, in __init__
      self.draw_all()
  File "/opt/python/2.7.3/lib/python2.7/site-packages/matplotlib-1.4.0-py2.7-linux-x86_64.egg/matplotlib/colorbar.py", line 342, in draw_all
    self._process_values()
  File "/opt/python/2.7.3/lib/python2.7/site-packages/matplotlib-1.4.0-py2.7-linux-x86_64.egg/matplotlib/colorbar.py", line 658, in _process_values
    expander=0.1)
  File "/opt/python/2.7.3/lib/python2.7/site-packages/matplotlib-1.4.0-py2.7-linux-x86_64.egg/matplotlib/transforms.py", line 2642, in nonsingular
    if (not np.isfinite(vmin)) or (not np.isfinite(vmax)):
TypeError: Not implemented for this type

**Comment by fidelram** [comment]
The error is happening when matplotlib should plot the resulting heatmap. The error may be caused by an empty matrix or by maybe by an issue with matplotlib. 

My suggestions are:

 * Try to use the branch release-1.6 of deepTools. For bamCorrelate we have split the computation of the matrix and the visualisation (first run bamCorrelate, then run plotCorrelation). This version is already stable but we don't have yet updated the wiki, manuals and galaxy. 
 * If you don't want to update deepTools, you may try to update to the latest version of matplotlib
  * With your current version, use the option to  save raw data. Because this is done before the plotting, you will be able to look at the values to try to spot any problem like all zeros.

**Comment by fidelram** [comment]
Any follow up on this problem?

**Comment by abretaud** [comment]
Hi,
I have the same error here, with:
Python 2.7.5
deeptools 1.5.11
matplotlib 1.5.0

I used the --outFileCorMatrix option, the matrix looks like this:

	    'Female_1'	'Female_2'
    'Female_1'	1.0000	0.8950
    'Female_2'	0.8950	1.0000

The --outRawCounts option gives something like this:

    'Female_1'	'Female_2'
    302	236
    156	193
    130	189
    141	175
    162	190
    180	191
    [...]

Do you think deeptools 1.6 would work better?

**Comment by fidelram** [comment]
there has been quite some updates on the way correlations are plotted in
the release-1.6 branch, so I will suggest that you try it. In the
release-1.6 branch you have to call two programms: first bamCorrelate (or
bigwigCorrelate) and then plotCorrelation (or plotPCA).

On Thu, Dec 3, 2015 at 11:32 AM, Anthony Bretaudeau <
notifications@github.com> wrote:

> Hi,
> I have the same error here, with:
> Python 2.7.5
> deeptools 1.5.11
> matplotlib 1.5.0
>
> I used the --outFileCorMatrix option, the matrix looks like this:
>
>     'Female_1'  'Female_2'
> 'Female_1'  1.0000  0.8950
> 'Female_2'  0.8950  1.0000
>
> The --outRawCounts option gives something like this:
>
> 'Female_1'  'Female_2'
> 302 236
> 156 193
> 130 189
> 141 175
> 162 190
> 180 191
> [...]
>
> Do you think deeptools 1.6 would work better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/86#issuecomment-161589203>.
>



-- 

Fidel Ramirez

**Comment by abretaud** [comment]
We just tested: it works with 1.6
Thanks a lot!
Anthony

**Comment by scholtalbers** [comment]
Not sure if this is the right place, but I'm running bamCorrelate in Galaxy and would like to get the 1.6 update that apparently resolves this issue. Is there an updated wrapper that includes this in the toolshed? - if so, which one?

**Comment by dpryan79** [comment]
@scholtalbers The most recent version of deeptools (2.0.1) is available in the toolshed. You can see it in action on our public Galaxy server (http://deeptools.ie-freiburg.mpg.de).

**Comment by scholtalbers** [comment]
@dpryan79 I guess I can just install the 2.0.1 version. However, if I'm correct the installation instructions still point to the old 1.5.11, i.e. http://deeptools.readthedocs.org/en/latest/content/installation.html points to https://toolshed.g2.bx.psu.edu/view/bgruening/deeptools/7889d260cc37 .
For 2.0.1 I see wrappers per tool, but no suite that has them all. Should I thus install each tool separately?

**Comment by dpryan79** [comment]
It's called "suite_deeptools".

**Comment by scholtalbers** [comment]
right...should have found that one. Thanks! :blush:

**Comment by dpryan79** [comment]
The documentation will get updated on our next branch merging, so probably today/tomorrow
