### ISSUE TITLE
mutliple profiles together in one plot

### ISSUE THREAD

**Issue by pkhoueiry** [fidelram/deepTools#88]
Hi guys,

In computeMatrix followed by profiler, is there a way to plot multiple profiles in on plot to compare them directly, with there "se" profiles. 
For instance, I have three bed files that I want to plot a bigwig profile over them and plot them on the same plot (not separated as in the example).
I believe that I asked this question long time ago and you were thinking of implementing this.
Thanks,

**Comment by fidelram** [comment]
I am not sure I follow you but this is something you can do. Lets say you
have bed1, bed2 and bed3. Then merge all the files in a single adding a
separation line that should have a '#' and a label. Then the profiler will
understand that you have three groups and will use the label that you put.

A overly simple bed file will look like this

chr1 10 100
chr2 20 200
# first group
chr1 100 200
chr2 200 300
# second group.

I hope this helps.



On Fri, Jul 3, 2015 at 11:49 AM, pkhoueiry <notifications@github.com> wrote:

> Hi guys,
>
> In computeMatrix followed by profiler, is there a way to plot multiple
> profiles in on plot to compare them directly, with there "se" profiles.
> For instance, I have three bed files that I want to plot a bigwig profile
> over them and plot them on the same plot (not separated as in the example).
> I believe that I asked this question long time ago and you were thinking
> of implementing this.
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/88>.
>



-- 

Fidel Ramirez

**Comment by pkhoueiry** [comment]
Thanks for the fast reply. Indeed, it works. Many thanks.
