### ISSUE TITLE
pysam import traceback

### ISSUE THREAD

**Issue by msxakk** [fidelram/deepTools#89]
Hello,
I've tried installing deepTools via pip and by python setup.py and I'm getting a traceback each time I call bamCorrelate function. 

msxakk@msngs:~$ bamCorrelate 
Traceback (most recent call last):
  File "/usr/local/bin/bamCorrelate", line 14, in <module>
    import deeptools.countReadsPerBin as countR
  File "/usr/local/lib/python2.7/dist-packages/deeptools/countReadsPerBin.py", line 7, in <module>
    import bamHandler
  File "/usr/local/lib/python2.7/dist-packages/deeptools/bamHandler.py", line 3, in <module>
    import pysam
ImportError: No module named pysam

I have therefore installed pysam via pip but I still have the problem. Any help?

**Comment by fidelram** [comment]
Was the pip pysam installation successful?

if you type 'pip freeze' can you see pysam? which version?

-fidel



On Tue, Jul 7, 2015 at 6:49 PM, msxakk <notifications@github.com> wrote:

> Hello,
> I've tried installing deepTools via pip and by python setup.py and I'm
> getting a traceback each time I call bamCorrelate function.
>
> msxakk@msngs:~$ bamCorrelate
> Traceback (most recent call last):
> File "/usr/local/bin/bamCorrelate", line 14, in
> import deeptools.countReadsPerBin as countR
> File
> "/usr/local/lib/python2.7/dist-packages/deeptools/countReadsPerBin.py",
> line 7, in
> import bamHandler
> File "/usr/local/lib/python2.7/dist-packages/deeptools/bamHandler.py",
> line 3, in
> import pysam
> ImportError: No module named pysam
>
> I have therefore installed pysam via pip but I still have the problem. Any
> help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/89>.
>



-- 

Fidel Ramirez

**Comment by msxakk** [comment]
All sorted now! Thanks anyway!
