### ISSUE TITLE
deepTool bamCoverage BigWig does not match expectation

### ISSUE THREAD

**Issue by igordot** [fidelram/deepTools#92]
I recently found deepTool bamCoverage tool and was excited to try it given all the options it offers. However, the output I am getting does not match the original BAM or the BigWigs that I generated by other means. See example below:
![image](https://cloud.githubusercontent.com/assets/6363505/9019339/d9776212-37b7-11e5-8207-7a0f26e29408.png)
* gray is BAM
* green is my own BigWig

The rest are using bamCoverage with various parameters:
* --binSize 1
* --binSize 1 --fragmentLength 0
* --binSize 10
* --binSize 10 --fragmentLength 0

Shouldn't bin size of 1 result in the same graph as the raw coverage? Also, shouldn't fragment length of 0 generate more narrow peaks than the default of 200?

**Comment by friedue** [comment]
Hi Igor,

some comments:
* what normalization parameter are you using? 
* what's the scale on the Genome Browser snapshot?
* do you have paired-end or single read data?

**Comment by fidelram** [comment]
The bigWig generated by deepTools is identical to the one seen in for
example the IGV genome browser when it is set not to extend read pairs.
Check that the option is not set and use a fragment length smaller than the
read size.

On Sun, Aug 2, 2015 at 1:48 AM, Friederike Dündar <notifications@github.com>
wrote:

> Hi Igor,
>
> some comments:
>
>    - what normalization parameter are you using?
>    - what's the scale on the Genome Browser snapshot?
>    - do you have paired-end or single read data?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/92#issuecomment-126964971>.
>



-- 

Fidel Ramirez

**Comment by igordot** [comment]
> what normalization parameter are you using?

--normalizeUsingRPKM but that should only affect the scale, not the distribution

> what's the scale on the Genome Browser snapshot?

the scale is auto-scale, so it goes from 0 to max

> do you have paired-end or single read data?

single read

> The bigWig generated by deepTools is identical to the one seen in for
> example the IGV genome browser when it is set not to extend read pairs.
> Check that the option is not set and use a fragment length smaller than the
> read size.

these are single-read sequences, so it shouldn't matter, right?

**Comment by friedue** [comment]
Single-read sequences will also be extended to match the fragment size.

I was asking about the scale because to me the image looks as if the deepTools-generated files are not fully displayed (the peaks look cropped).

**Comment by igordot** [comment]
I set fragmentLength to 0.

I am not worried about the peaks being cropped. My concern is that the deepTools tools are much wider than expected. If it's not due to binSize (set to 1) or fragmentLength (set to 0), what other parameter is adding that extra info?

**Comment by fidelram** [comment]
I just tried with paired-end data and as you can see the results are
identical to the ones from IGV coverage.

The parameters I used were: --fragmentLength 1 --doNotExtendPairedEnds
--binSize 1

Can you add --doNotExtendPairedEnds even if your data is single end?



On Tue, Aug 4, 2015 at 4:36 PM, igor <notifications@github.com> wrote:

> I set fragmentLength to 0.
>
> I am not worried about the peaks being cropped. My concern is that the
> deepTools tools are much wider than expected. If it's not due to binSize
> (set to 1) or fragmentLength (set to 0), what other parameter is adding
> that extra info?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/92#issuecomment-127634593>.
>



-- 

Fidel Ramirez

**Comment by fidelram** [comment]
I just checked and the problem may be the fragmentLength, if set to 0 it is converted to 300. Using a value of 1 is safe.

**Comment by igordot** [comment]
I just repeated setting fragmentLength to 1 and the BigWigs look as expected. Thank you for your help.

I have a followup question. If I create two BigWigs (no fragment length extension or smoothing), one with bin size 1 and the other with bin size 10, the larger bin size makes a slightly smaller file (~200 MB in my case). However, if I add smoothing, the size grows considerably. For bin size 1, setting smoothing length to 10 results in a file of almost 2 GB. I understand that some extra regions are added at the edges of peaks, but most of the bins should be the same with roughly similar values. It seems odd that the amount of data is 10X. Changing fragment length to the default of 200, which also expands the covered regions, increased the file size by only 10%.

**Comment by fidelram** [comment]
I will take a look at that.

On Sun, Aug 9, 2015 at 12:14 AM, igor <notifications@github.com> wrote:

> I just repeated setting fragmentLength to 1 and the BigWigs look as
> expected. Thank you for your help.
>
> I have a followup question. If I create two BigWigs (no fragment length
> extension or smoothing), one with bin size 1 and the other with bin size
> 10, the larger bin size makes a slightly smaller file (~200 MB in my case).
> However, if I add smoothing, the size grows considerably. For bin size 1,
> setting smoothing length to 10 results in a file of almost 2 GB. I
> understand that some extra regions are added at the edges of peaks, but
> most of the bins should be the same with roughly similar values. It seems
> odd that the amount of data is 10X. Changing fragment length to the default
> of 200, which also expands the covered regions, increased the file size by
> only 10%.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/92#issuecomment-129057869>.
>



-- 

Fidel Ramirez

**Comment by igordot** [comment]
Since this got closed, does it mean it was fixed or it was not a problem?

**Comment by fidelram** [comment]
I put a new issue. See: https://github.com/fidelram/deepTools/issues/99



On Tue, Sep 15, 2015 at 6:09 PM, igor <notifications@github.com> wrote:

> Since this got closed, does it mean it was fixed or it was not a problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/92#issuecomment-140446189>.
>



-- 

Fidel Ramirez
