### ISSUE TITLE
custom genome_2bits

### ISSUE THREAD

**Issue by radaniba** [fidelram/deepTools#93]
Hi 

Can you please add input on this issue ? We have a slightly different ref genome than hg19 and I'd like to know how to adapt the genome 2 bits to be consistent 

Where is the genome files saved ?

Cheers

**Comment by radaniba** [comment]
never mind :)

**Comment by fidelram** [comment]
You can create a 2bit file from a fasta file using the faToTwoBit program from UCSC. More info here: https://genome.ucsc.edu/goldenPath/help/twoBit.html

**Comment by radaniba** [comment]
@fidelram Fantastic, thanks for the tip
