### ISSUE TITLE
Traceback when running bamCorrelate

### ISSUE THREAD

**Issue by msxakk** [fidelram/deepTools#94]
Hello,
I'm trying to run bamCorrelate and I get the following traceback:

Traceback (most recent call last):
  File "/usr/local/bin/bamCorrelate", line 435, in <module>
    main(ARGS)
  File "/usr/local/bin/bamCorrelate", line 350, in main
    stepSize=stepsize)
  File "/usr/local/lib/python2.7/dist-packages/deeptools/countReadsPerBin.py", line 305, in getNumReadsPerBin
    numberOfProcessors=numberOfProcessors)
  File "/usr/local/lib/python2.7/dist-packages/deeptools/mapReduce.py", line 63, in mapReduce
    bed_interval_tree = BED_to_interval_tree(bedFile)
  File "/usr/local/lib/python2.7/dist-packages/deeptools/mapReduce.py", line 191, in BED_to_interval_tree
    from bx.intervals.intersection import IntervalTree, Interval

I installed numpy and scipy via
sudo apt-get install python-numpy python-scipy 

I aslo tried installing fastinterval via
pip install fastinterval 

Both installation looked successful but I'm still getting this error. Any help? Is it a path issue here?

**Comment by fidelram** [comment]
This is a problem with the installation of bx-python.

Try to install it: pip install bx-python

(also check their page for further installation options:
https://bitbucket.org/james_taylor/bx-python/wiki/HowToInstall)

-fidel

On Mon, Aug 17, 2015 at 3:29 PM, msxakk <notifications@github.com> wrote:

> Hello,
> I'm trying to run bamCorrelate and I get the following traceback:
>
> Traceback (most recent call last):
> File "/usr/local/bin/bamCorrelate", line 435, in
> main(ARGS)
> File "/usr/local/bin/bamCorrelate", line 350, in main
> stepSize=stepsize)
> File
> "/usr/local/lib/python2.7/dist-packages/deeptools/countReadsPerBin.py",
> line 305, in getNumReadsPerBin
> numberOfProcessors=numberOfProcessors)
> File "/usr/local/lib/python2.7/dist-packages/deeptools/mapReduce.py", line
> 63, in mapReduce
> bed_interval_tree = BED_to_interval_tree(bedFile)
> File "/usr/local/lib/python2.7/dist-packages/deeptools/mapReduce.py", line
> 191, in BED_to_interval_tree
> from bx.intervals.intersection import IntervalTree, Interval
>
> I installed numpy and scipy via
> sudo apt-get install python-numpy python-scipy
>
> I aslo tried installing fastinterval via
> pip install fastinterval
>
> Both installation looked successful but I'm still getting this error. Any
> help? Is it a path issue here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/94>.
>



-- 

Fidel Ramirez

**Comment by msxakk** [comment]
I tried installing bx-python and I got the following error:
Command /usr/bin/python -c "import setuptools;__file__='/home/msxakk/Downloads/build/bx-python/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-XnOjIY-record/install-record.txt failed with error code 1

Hence repeating bamCorrelate command resulted in the same error.

**Comment by fidelram** [comment]
I never had any problem installing bx-python. I can not help you there.



On Tue, Aug 25, 2015 at 3:40 PM, msxakk <notifications@github.com> wrote:

> I tried installing bx-python and I got the following error:
> Command /usr/bin/python -c "import setuptools;*file*
> ='/home/msxakk/Downloads/build/bx-python/setup.py';exec(compile(open(
> *file*).read().replace('\r\n', '\n'), *file*, 'exec'))" install
> --single-version-externally-managed --record
> /tmp/pip-XnOjIY-record/install-record.txt failed with error code 1
>
> Hence repeating bamCorrelate command resulted in the same error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/94#issuecomment-134589797>.
>



-- 

Fidel Ramirez
