### ISSUE TITLE
Use CWig instead of Bigwig

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#97]
The format uses on average one-third of the size of existing bigWig files and improves random query speed up to 100 times.
(CWig: compressed representation of Wiggle/BedGraph format)

You can also use cython to enhance performances.

**Comment by fidelram** [comment]
Thanks for letting us know about the CWig format. I will see what I can do.

**Comment by lelouar** [comment]
A new format for compression of wig is come out :
Wang, Zhiying, Tsachy Weissman, and Olgica Milenkovic. “smallWig: Parallel Compression of RNA-Seq WIG Files.” Bioinformatics, September 30, 2015, btv561. doi:10.1093/bioinformatics/btv561.

they argue that this format is (or seems to be) better than bigWig and Cwig.

**Comment by dpryan79** [comment]
I would suggest that we close this, since there's no point in making Cwig or smallWig files when IGV/et al. don't support them.
