### ISSUE TITLE
one bed over different bw

### ISSUE THREAD

**Issue by pkhoueiry** [fidelram/deepTools#98]
Hi Fidel,
You previously explained (issue  #88) how to plot the signal of one bigwig over different bed files.
Now, how can we plot signals of different bigwigs (say, PolII, H3K4me1, H3K27Ac ...) over one bed file (say TSS). Also in this context, how can we ask deeptools to take strandness into account assuming we have this information in the bed file ?

Many thanks,
Pierre

**Comment by fidelram** [comment]
To plot multiple bigwigs simply use the release-1.6 branch. That version can do what you want. Also, by default the heatmap computation takes strand into account if it is present on the bed file.
