### ISSUE TITLE
Size of bigwig file increases if smoothing is added.

### ISSUE THREAD

**Issue by fidelram** [fidelram/deepTools#99]
A user (igordot) reports the following:

If I create two BigWigs (no fragment length extension or smoothing), one with bin size 1 and the other with bin size 10, the larger bin size makes a slightly smaller file (~200 MB in my case). However, if I add smoothing, the size grows considerably. For bin size 1, setting smoothing length to 10 results in a file of almost 2 GB. I understand that some extra regions are added at the edges of peaks, but most of the bins should be the same with roughly similar values. It seems odd that the amount of data is 10X. Changing fragment length to the default of 200, which also expands the covered regions, increased the file size by only 10%.

**Comment by fidelram** [comment]
I ran a small test and didn't see any large differences. The smoothed file was slightly larger in my case but not 10 times as large. Which species did you use? can you share the bigwig files such that I can compare them and try to spot the reason for the difference?

**Comment by igordot** [comment]
Sorry. I didn't realize there was activity. How can I share the files with you?

**Comment by dpryan79** [comment]
@igordot: Dropbox or google drive would work.

**Comment by dpryan79** [comment]
Closing, go ahead and reopen this if you can get some test files to us.
